-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "catppuccin-mocha"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@constant.builtin", { fg = "#fab387" })
hi(0, "@constant.java", { fg = "#94e2d5" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#74c7ec" })
hi(0, "@constructor.lua", { fg = "#f2cdcd" })
hi(0, "@constructor.tsx", { fg = "#b4befe" })
hi(0, "@constructor.typescript", { fg = "#b4befe" })
hi(0, "@error", { link = "Error" })
hi(0, "@field", { fg = "#b4befe" })
hi(0, "@field.yaml", { fg = "#89b4fa" })
hi(0, "@function.builtin", { fg = "#fab387" })
hi(0, "@function.builtin.bash", { fg = "#f38ba8", italic = true })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { fg = "#94e2d5" })
hi(0, "@keyword.export", { fg = "#89dceb" })
hi(0, "@keyword.function", { fg = "#cba6f7" })
hi(0, "@keyword.operator", { fg = "#cba6f7" })
hi(0, "@keyword.return", { fg = "#cba6f7" })
hi(0, "@label.json", { fg = "#89b4fa" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.interface", { fg = "#f2cdcd" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@namespace", { fg = "#b4befe", italic = true })
hi(0, "@number.css", { fg = "#fab387" })
hi(0, "@parameter", { fg = "#eba0ac" })
hi(0, "@property", { fg = "#b4befe" })
hi(0, "@property.class.css", { fg = "#f9e2af" })
hi(0, "@property.cpp", { fg = "#cdd6f4" })
hi(0, "@property.css", { fg = "#b4befe" })
hi(0, "@property.id.css", { fg = "#89b4fa" })
hi(0, "@property.toml", { fg = "#89b4fa" })
hi(0, "@property.typescript", { fg = "#b4befe" })
hi(0, "@punctuation.bracket", { fg = "#9399b2" })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.escape", { fg = "#f5c2e7" })
hi(0, "@string.plain.css", { fg = "#fab387" })
hi(0, "@string.regex", { fg = "#fab387" })
hi(0, "@string.special", { link = "Special" })
hi(0, "@symbol", { fg = "#f2cdcd" })
hi(0, "@symbol.ruby", { fg = "#f2cdcd" })
hi(0, "@tag", { fg = "#cba6f7" })
hi(0, "@tag.attribute", { fg = "#94e2d5", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#cba6f7", italic = true })
hi(0, "@tag.delimiter", { fg = "#89dceb" })
hi(0, "@text", { fg = "#cdd6f4" })
hi(0, "@text.danger", { bg = "#f38ba8", fg = "#1e1e2e" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = "#eba0ac", italic = true })
hi(0, "@text.environment", { fg = "#f5c2e7" })
hi(0, "@text.environment.name", { fg = "#89b4fa" })
hi(0, "@text.literal", { fg = "#94e2d5" })
hi(0, "@text.math", { fg = "#89b4fa" })
hi(0, "@text.note", { bg = "#89b4fa", fg = "#1e1e2e" })
hi(0, "@text.reference", { link = "Tag" })
hi(0, "@text.strike", { fg = "#cdd6f4", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#eba0ac" })
hi(0, "@text.title", { bold = true, fg = "#89b4fa" })
hi(0, "@text.title.1.markdown", { link = "rainbow1" })
hi(0, "@text.title.2.markdown", { link = "rainbow2" })
hi(0, "@text.title.3.markdown", { link = "rainbow3" })
hi(0, "@text.title.4.markdown", { link = "rainbow4" })
hi(0, "@text.title.5.markdown", { link = "rainbow5" })
hi(0, "@text.title.6.markdown", { link = "rainbow6" })
hi(0, "@text.todo", { bg = "#f9e2af", fg = "#1e1e2e" })
hi(0, "@text.todo.checked", { fg = "#a6e3a1" })
hi(0, "@text.todo.unchecked", { fg = "#7f849c" })
hi(0, "@text.underline", { link = "Underline" })
hi(0, "@text.uri", { fg = "#f5e0dc", italic = true, underline = true })
hi(0, "@text.warning", { bg = "#f9e2af", fg = "#1e1e2e" })
hi(0, "@type.builtin", { fg = "#f9e2af" })
hi(0, "@type.builtin.c", { fg = "#f9e2af" })
hi(0, "@type.builtin.cpp", { fg = "#f9e2af" })
hi(0, "@type.css", { fg = "#b4befe" })
hi(0, "@type.definition", { link = "Type" })
hi(0, "@type.qualifier", { link = "Keyword" })
hi(0, "@type.tag.css", { fg = "#cba6f7" })
hi(0, "@variable", { fg = "#cdd6f4" })
hi(0, "@variable.builtin", { fg = "#f38ba8" })
hi(0, "AlphaButtons", { fg = "#b4befe" })
hi(0, "AlphaFooter", { fg = "#f9e2af", italic = true })
hi(0, "AlphaHeader", { fg = "#89b4fa" })
hi(0, "AlphaHeaderLabel", { fg = "#fab387" })
hi(0, "AlphaShortcut", { fg = "#a6e3a1" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#fab387" })
hi(0, "Character", { fg = "#94e2d5" })
hi(0, "CmpItemAbbr", { fg = "#9399b2" })
hi(0, "CmpItemAbbrDefault", { fg = "#9399b2" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#6c7086", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#6c7086" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#cdd6f4" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#9399b2" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#cdd6f4" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#9399b2" })
hi(0, "CmpItemKind", { fg = "#89b4fa" })
hi(0, "CmpItemKindClass", { fg = "#f9e2af" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#f38ba8" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#fab387" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#89b4fa" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#94e2d5" })
hi(0, "CmpItemKindDefault", { fg = "#f5c2e7" })
hi(0, "CmpItemKindEnum", { fg = "#a6e3a1" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#f38ba8" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#89b4fa" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#a6e3a1" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#89b4fa" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#89b4fa" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#89b4fa" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#f9e2af" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#f38ba8" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#89b4fa" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#89b4fa" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#89b4fa" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#a6e3a1" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#f38ba8" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#cba6f7" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#89b4fa" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#94e2d5" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#89b4fa" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#a6e3a1" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#fab387" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#f2cdcd" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#cdd6f4" })
hi(0, "CmpItemMenuDefault", { fg = "#9399b2" })
hi(0, "ColorColumn", { bg = "#313244" })
hi(0, "Comment", { fg = "#6c7086", italic = true })
hi(0, "Conceal", { fg = "#7f849c" })
hi(0, "Conditional", { fg = "#cba6f7", italic = true })
hi(0, "Constant", { fg = "#fab387" })
hi(0, "CurSearch", { bg = "#f38ba8", fg = "#181825" })
hi(0, "Cursor", { bg = "#cdd6f4", fg = "#1e1e2e" })
hi(0, "CursorColumn", { bg = "#181825" })
hi(0, "CursorIM", { bg = "#cdd6f4", fg = "#1e1e2e" })
hi(0, "CursorLine", { bg = "#2a2b3c" })
hi(0, "CursorLineNr", { fg = "#b4befe" })
hi(0, "DashboardCenter", { fg = "#a6e3a1" })
hi(0, "DashboardFiles", { fg = "#b4befe" })
hi(0, "DashboardFooter", { fg = "#f9e2af", italic = true })
hi(0, "DashboardHeader", { fg = "#89b4fa" })
hi(0, "DashboardMruTitle", { fg = "#89dceb" })
hi(0, "DashboardProjectTitle", { fg = "#89dceb" })
hi(0, "DashboardShortcut", { fg = "#f5c2e7" })
hi(0, "Delimiter", { fg = "#9399b2" })
hi(0, "DiagnosticError", { fg = "#f38ba8", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#f38ba8" })
hi(0, "DiagnosticFloatingHint", { fg = "#94e2d5" })
hi(0, "DiagnosticFloatingInfo", { fg = "#89dceb" })
hi(0, "DiagnosticFloatingWarn", { fg = "#f9e2af" })
hi(0, "DiagnosticHint", { fg = "#94e2d5", italic = true })
hi(0, "DiagnosticInfo", { fg = "#89dceb", italic = true })
hi(0, "DiagnosticSignError", { fg = "#f38ba8" })
hi(0, "DiagnosticSignHint", { fg = "#94e2d5" })
hi(0, "DiagnosticSignInfo", { fg = "#89dceb" })
hi(0, "DiagnosticSignWarn", { fg = "#f9e2af" })
hi(0, "DiagnosticUnderlineError", { sp = "#f38ba8", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#94e2d5", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#89dceb", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#f9e2af", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#32283a", fg = "#f38ba8", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#29313e", fg = "#94e2d5", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#283040", fg = "#89dceb", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#33313a", fg = "#f9e2af", italic = true })
hi(0, "DiagnosticWarn", { fg = "#f9e2af", italic = true })
hi(0, "DiffAdd", { bg = "#364143" })
hi(0, "DiffChange", { bg = "#25293c" })
hi(0, "DiffDelete", { bg = "#443244" })
hi(0, "DiffFile", { fg = "#89b4fa" })
hi(0, "DiffLine", { fg = "#6c7086" })
hi(0, "DiffNewFile", { fg = "#fab387" })
hi(0, "DiffText", { bg = "#3e4b6b" })
hi(0, "Directory", { fg = "#89b4fa" })
hi(0, "DropBarIconUISeparator", { fg = "#7f849c" })
hi(0, "DropBarKindArray", { fg = "#cdd6f4" })
hi(0, "DropBarKindBoolean", { fg = "#cdd6f4" })
hi(0, "DropBarKindBreakStatement", { fg = "#cdd6f4" })
hi(0, "DropBarKindCall", { fg = "#cdd6f4" })
hi(0, "DropBarKindCaseStatement", { fg = "#cdd6f4" })
hi(0, "DropBarKindClass", { fg = "#cdd6f4" })
hi(0, "DropBarKindConstant", { fg = "#cdd6f4" })
hi(0, "DropBarKindConstructor", { fg = "#cdd6f4" })
hi(0, "DropBarKindContinueStatement", { fg = "#cdd6f4" })
hi(0, "DropBarKindDeclaration", { fg = "#cdd6f4" })
hi(0, "DropBarKindDelete", { fg = "#cdd6f4" })
hi(0, "DropBarKindDoStatement", { fg = "#cdd6f4" })
hi(0, "DropBarKindElseStatement", { fg = "#cdd6f4" })
hi(0, "DropBarKindEnum", { fg = "#cdd6f4" })
hi(0, "DropBarKindEnumMember", { fg = "#cdd6f4" })
hi(0, "DropBarKindEvent", { fg = "#cdd6f4" })
hi(0, "DropBarKindField", { fg = "#cdd6f4" })
hi(0, "DropBarKindFile", { fg = "#cdd6f4" })
hi(0, "DropBarKindFolder", { fg = "#cdd6f4" })
hi(0, "DropBarKindForStatement", { fg = "#cdd6f4" })
hi(0, "DropBarKindFunction", { fg = "#cdd6f4" })
hi(0, "DropBarKindIdentifier", { fg = "#cdd6f4" })
hi(0, "DropBarKindIfStatement", { fg = "#cdd6f4" })
hi(0, "DropBarKindInterface", { fg = "#cdd6f4" })
hi(0, "DropBarKindKeyword", { fg = "#cdd6f4" })
hi(0, "DropBarKindList", { fg = "#cdd6f4" })
hi(0, "DropBarKindMacro", { fg = "#cdd6f4" })
hi(0, "DropBarKindMarkdownH1", { fg = "#cdd6f4" })
hi(0, "DropBarKindMarkdownH2", { fg = "#cdd6f4" })
hi(0, "DropBarKindMarkdownH3", { fg = "#cdd6f4" })
hi(0, "DropBarKindMarkdownH4", { fg = "#cdd6f4" })
hi(0, "DropBarKindMarkdownH5", { fg = "#cdd6f4" })
hi(0, "DropBarKindMarkdownH6", { fg = "#cdd6f4" })
hi(0, "DropBarKindMethod", { fg = "#cdd6f4" })
hi(0, "DropBarKindModule", { fg = "#cdd6f4" })
hi(0, "DropBarKindNamespace", { fg = "#cdd6f4" })
hi(0, "DropBarKindNull", { fg = "#cdd6f4" })
hi(0, "DropBarKindNumber", { fg = "#cdd6f4" })
hi(0, "DropBarKindObject", { fg = "#cdd6f4" })
hi(0, "DropBarKindOperator", { fg = "#cdd6f4" })
hi(0, "DropBarKindPackage", { fg = "#cdd6f4" })
hi(0, "DropBarKindProperty", { fg = "#cdd6f4" })
hi(0, "DropBarKindReference", { fg = "#cdd6f4" })
hi(0, "DropBarKindRepeat", { fg = "#cdd6f4" })
hi(0, "DropBarKindScope", { fg = "#cdd6f4" })
hi(0, "DropBarKindSpecifier", { fg = "#cdd6f4" })
hi(0, "DropBarKindStatement", { fg = "#cdd6f4" })
hi(0, "DropBarKindString", { fg = "#cdd6f4" })
hi(0, "DropBarKindStruct", { fg = "#cdd6f4" })
hi(0, "DropBarKindSwitchStatement", { fg = "#cdd6f4" })
hi(0, "DropBarKindType", { fg = "#cdd6f4" })
hi(0, "DropBarKindTypeParameter", { fg = "#cdd6f4" })
hi(0, "DropBarKindUnit", { fg = "#cdd6f4" })
hi(0, "DropBarKindValue", { fg = "#cdd6f4" })
hi(0, "DropBarKindVariable", { fg = "#cdd6f4" })
hi(0, "DropBarKindWhileStatement", { fg = "#cdd6f4" })
hi(0, "DropBarMenuHoverEntry", { link = "Visual" })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
hi(0, "EndOfBuffer", { fg = "#1e1e2e" })
hi(0, "Error", { fg = "#f38ba8" })
hi(0, "ErrorMsg", { bold = true, fg = "#f38ba8", italic = true })
hi(0, "Exception", { fg = "#cba6f7" })
hi(0, "FlashBackdrop", { fg = "#6c7086" })
hi(0, "FlashCurrent", { bg = "#1e1e2e", fg = "#fab387" })
hi(0, "FlashLabel", { bg = "#1e1e2e", bold = true, fg = "#a6e3a1" })
hi(0, "FlashMatch", { bg = "#1e1e2e", fg = "#b4befe" })
hi(0, "FloatBorder", { fg = "#89b4fa" })
hi(0, "FloatTitle", { fg = "#a6adc8" })
hi(0, "FoldColumn", { fg = "#6c7086" })
hi(0, "Folded", { bg = "#45475a", fg = "#89b4fa" })
hi(0, "Function", { fg = "#89b4fa" })
hi(0, "GitSignsAdd", { fg = "#a6e3a1" })
hi(0, "GitSignsAddInline", { reverse = true })
hi(0, "GitSignsAddLn", { bg = "#364143" })
hi(0, "GitSignsChange", { fg = "#f9e2af" })
hi(0, "GitSignsChangeInline", { reverse = true })
hi(0, "GitSignsChangeLn", { bg = "#25293c" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#45475a" })
hi(0, "GitSignsDelete", { fg = "#f38ba8" })
hi(0, "GitSignsDeleteInline", { reverse = true })
hi(0, "GitSignsStagedAdd", { fg = "#537150" })
hi(0, "GitSignsStagedAddLn", { bg = "#364143" })
hi(0, "GitSignsStagedAddNr", { fg = "#537150" })
hi(0, "GitSignsStagedChange", { fg = "#7c7157" })
hi(0, "GitSignsStagedChangeLn", { bg = "#25293c" })
hi(0, "GitSignsStagedChangeNr", { fg = "#7c7157" })
hi(0, "GitSignsStagedChangedelete", { fg = "#7c7157" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#25293c" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#7c7157" })
hi(0, "GitSignsStagedDelete", { fg = "#794554" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#794554" })
hi(0, "GitSignsStagedTopdelete", { fg = "#794554" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#794554" })
hi(0, "GitSignsUntracked", { fg = "#a6e3a1" })
hi(0, "GitSignsUntrackedLn", { bg = "#364143" })
hi(0, "GlyphPalette1", { fg = "#f38ba8" })
hi(0, "GlyphPalette2", { fg = "#94e2d5" })
hi(0, "GlyphPalette3", { fg = "#f9e2af" })
hi(0, "GlyphPalette4", { fg = "#89b4fa" })
hi(0, "GlyphPalette6", { fg = "#94e2d5" })
hi(0, "GlyphPalette7", { fg = "#cdd6f4" })
hi(0, "GlyphPalette9", { fg = "#f38ba8" })
hi(0, "Identifier", { fg = "#f2cdcd" })
hi(0, "IlluminatedWordRead", { bg = "#393b4d" })
hi(0, "IlluminatedWordText", { bg = "#393b4d" })
hi(0, "IlluminatedWordWrite", { bg = "#393b4d" })
hi(0, "IncSearch", { bg = "#7ec9d8", fg = "#181825" })
hi(0, "Include", { fg = "#cba6f7" })
hi(0, "IndentBlanklineChar", { fg = "#313244" })
hi(0, "IndentBlanklineContextChar", { fg = "#cdd6f4" })
hi(0, "IndentBlanklineContextStart", { sp = "#cdd6f4", underline = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#45475a", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#45475a", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#cba6f7" })
hi(0, "Label", { fg = "#74c7ec" })
hi(0, "LineNr", { fg = "#45475a" })
hi(0, "LspCodeLens", { fg = "#6c7086" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#f38ba8" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#94e2d5" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#89dceb" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#f9e2af" })
hi(0, "LspDiagnosticsError", { fg = "#f38ba8" })
hi(0, "LspDiagnosticsHint", { fg = "#94e2d5" })
hi(0, "LspDiagnosticsInformation", { fg = "#89dceb" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#f38ba8", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#94e2d5", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#89dceb", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#f9e2af", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#f38ba8", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#94e2d5", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#89dceb", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#f9e2af", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#f9e2af" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInlayHint", { bg = "#2a2b3c", fg = "#6c7086" })
hi(0, "LspReferenceRead", { bg = "#45475a" })
hi(0, "LspReferenceText", { bg = "#45475a" })
hi(0, "LspReferenceWrite", { bg = "#45475a" })
hi(0, "LspSignatureActiveParameter", { fg = "#fab387" })
hi(0, "Macro", { fg = "#cba6f7" })
hi(0, "MatchParen", { bg = "#45475a", bold = true, fg = "#fab387" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "ModeMsg", { bold = true, fg = "#cdd6f4" })
hi(0, "MoreMsg", { fg = "#89b4fa" })
hi(0, "MsgSeparator", {})
hi(0, "NeogitBranch", { bold = true, fg = "#fab387" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#a6e3a1" })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#f9e2af" })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#f5c2e7" })
hi(0, "NeogitChangeModified", { bold = true, fg = "#89b4fa" })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#a6e3a1" })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#cba6f7" })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#fab387" })
hi(0, "NeogitCommitViewHeader", { bg = "#3e4b6b", fg = "#97bbf9" })
hi(0, "NeogitDiffAdd", { bg = "#2b3139", fg = "#8bbc8a" })
hi(0, "NeogitDiffAddHighlight", { bg = "#4d6256", fg = "#ace1ad" })
hi(0, "NeogitDiffContextHighlight", { bg = "#25283b", fg = "#cdd6f4" })
hi(0, "NeogitDiffDelete", { bg = "#32283a", fg = "#c87590" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#674458", fg = "#ed96b3" })
hi(0, "NeogitHunkHeader", { bg = "#282c41", fg = "#546994" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#353e5a", fg = "#89b4fa" })
hi(0, "NeogitNotificationError", { fg = "#f38ba8" })
hi(0, "NeogitNotificationInfo", { fg = "#89b4fa" })
hi(0, "NeogitNotificationWarning", { fg = "#f9e2af" })
hi(0, "NeogitObjectId", { link = "Comment" })
hi(0, "NeogitRebaseDone", { link = "Comment" })
hi(0, "NeogitRebasing", { bold = true, fg = "#cba6f7" })
hi(0, "NeogitRecentcommits", { bold = true, fg = "#cba6f7" })
hi(0, "NeogitRemote", { bold = true, fg = "#a6e3a1" })
hi(0, "NeogitStagedchanges", { bold = true, fg = "#cba6f7" })
hi(0, "NeogitStash", { link = "Comment" })
hi(0, "NeogitStashes", { bold = true, fg = "#cba6f7" })
hi(0, "NeogitUnmergedInto", { link = "Function" })
hi(0, "NeogitUnmergedchanges", { bold = true, fg = "#cba6f7" })
hi(0, "NeogitUnpulledFrom", { link = "Function" })
hi(0, "NeogitUnpulledchanges", { bold = true, fg = "#cba6f7" })
hi(0, "NeogitUnstagedchanges", { bold = true, fg = "#cba6f7" })
hi(0, "NeogitUntrackedfiles", { bold = true, fg = "#cba6f7" })
hi(0, "NoiceAttr116", { fg = "#a8c9fb" })
hi(0, "NoiceAttr91", { fg = "#94cff4" })
hi(0, "NoiceCmdline", {})
hi(0, "NoiceCmdlineIcon", { fg = "#89dceb" })
hi(0, "NoiceCmdlineIconCalculator", { fg = "#89dceb" })
hi(0, "NoiceCmdlineIconCmdline", { fg = "#89dceb" })
hi(0, "NoiceCmdlineIconFilter", { fg = "#89dceb" })
hi(0, "NoiceCmdlineIconHelp", { fg = "#89dceb" })
hi(0, "NoiceCmdlineIconInput", { fg = "#89dceb" })
hi(0, "NoiceCmdlineIconLua", { fg = "#89dceb" })
hi(0, "NoiceCmdlineIconSearch", { fg = "#f9e2af" })
hi(0, "NoiceCmdlinePopup", { bg = "#1e1e2e", fg = "#cdd6f4" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#89dceb" })
hi(0, "NoiceCmdlinePopupBorderCalculator", { fg = "#89dceb" })
hi(0, "NoiceCmdlinePopupBorderCmdline", { fg = "#89dceb" })
hi(0, "NoiceCmdlinePopupBorderFilter", { fg = "#89dceb" })
hi(0, "NoiceCmdlinePopupBorderHelp", { fg = "#89dceb" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#89dceb" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#89dceb" })
hi(0, "NoiceCmdlinePopupBorderSearch", { fg = "#f9e2af" })
hi(0, "NoiceCmdlinePopupTitle", { fg = "#89dceb" })
hi(0, "NoiceCmdlinePrompt", { bold = true, fg = "#89b4fa" })
hi(0, "NoiceCompletionItemKindClass", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindColor", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindConstant", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindConstructor", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindEnum", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindEnumMember", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindField", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindFile", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindFolder", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindFunction", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindInterface", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindKeyword", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindMethod", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindModule", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindProperty", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindSnippet", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindStruct", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindText", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindUnit", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindValue", { fg = "#f5c2e7" })
hi(0, "NoiceCompletionItemKindVariable", { fg = "#f5c2e7" })
hi(0, "NoiceConfirm", { bg = "#1e1e2e", fg = "#cdd6f4" })
hi(0, "NoiceConfirmBorder", { fg = "#89dceb" })
hi(0, "NoiceCursor", { bg = "#cdd6f4", fg = "#1e1e2e" })
hi(0, "NoiceFormatConfirm", { bg = "#2a2b3c" })
hi(0, "NoiceFormatConfirmDefault", { bg = "#45475a", bold = true })
hi(0, "NoiceFormatDate", { fg = "#f5c2e7" })
hi(0, "NoiceFormatEvent", { fg = "#6c7086" })
hi(0, "NoiceFormatKind", { fg = "#6c7086" })
hi(0, "NoiceFormatLevelDebug", { fg = "#6c7086" })
hi(0, "NoiceFormatLevelError", { bg = "#32283a", fg = "#f38ba8", italic = true })
hi(0, "NoiceFormatLevelInfo", { bg = "#283040", fg = "#89dceb", italic = true })
hi(0, "NoiceFormatLevelOff", { fg = "#6c7086" })
hi(0, "NoiceFormatLevelTrace", { fg = "#6c7086" })
hi(0, "NoiceFormatLevelWarn", { bg = "#33313a", fg = "#f9e2af", italic = true })
hi(0, "NoiceFormatProgressDone", { bg = "#3e5767", fg = "#cdd6f4" })
hi(0, "NoiceFormatProgressTodo", { bg = "#2a2b3c" })
hi(0, "NoiceFormatTitle", { bold = true, fg = "#89b4fa" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NoiceLspProgressClient", { bold = true, fg = "#89b4fa" })
hi(0, "NoiceLspProgressSpinner", { fg = "#fab387" })
hi(0, "NoiceLspProgressTitle", { fg = "#6c7086" })
hi(0, "NoiceMini", {})
hi(0, "NoicePopup", { bg = "#181825", fg = "#cdd6f4" })
hi(0, "NoicePopupBorder", { fg = "#89b4fa" })
hi(0, "NoicePopupmenu", { bg = "#2b2b3c", fg = "#9399b2" })
hi(0, "NoicePopupmenuBorder", { fg = "#89b4fa" })
hi(0, "NoicePopupmenuMatch", { fg = "#f5c2e7" })
hi(0, "NoicePopupmenuSelected", { bg = "#45475a", bold = true })
hi(0, "NoiceScrollbar", { bg = "#45475a" })
hi(0, "NoiceScrollbarThumb", { bg = "#6c7086" })
hi(0, "NoiceSplit", { bg = "#181825", fg = "#cdd6f4" })
hi(0, "NoiceSplitBorder", { fg = "#89b4fa" })
hi(0, "NoiceVirtualText", { bg = "#283040", fg = "#89dceb", italic = true })
hi(0, "NonText", { fg = "#6c7086" })
hi(0, "Normal", { bg = "#1e1e2e", fg = "#cdd6f4" })
hi(0, "NormalFloat", { bg = "#181825", fg = "#cdd6f4" })
hi(0, "NormalNC", { bg = "#1e1e2e", fg = "#cdd6f4" })
hi(0, "NormalSB", { bg = "#11111b", fg = "#cdd6f4" })
hi(0, "NotifyDEBUGBorder", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGIcon", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGTitle", { fg = "#8b8b8b" })
hi(0, "NotifyERRORBorder", { fg = "#8a1f1f" })
hi(0, "NotifyERRORIcon", { fg = "#f70067" })
hi(0, "NotifyERRORTitle", { fg = "#f70067" })
hi(0, "NotifyINFOBorder", { fg = "#4f6752" })
hi(0, "NotifyINFOIcon", { fg = "#a9ff68" })
hi(0, "NotifyINFOTitle", { fg = "#a9ff68" })
hi(0, "NotifyTRACEBorder", { fg = "#4f3552" })
hi(0, "NotifyTRACEIcon", { fg = "#d484ff" })
hi(0, "NotifyTRACETitle", { fg = "#d484ff" })
hi(0, "NotifyWARNBody122", { bg = "#1e1e2e", fg = "#252536" })
hi(0, "NotifyWARNBorder", { fg = "#79491d" })
hi(0, "NotifyWARNBorder122", { fg = "#22202d" })
hi(0, "NotifyWARNIcon", { fg = "#f79000" })
hi(0, "NotifyWARNIcon122", { fg = "#27232c" })
hi(0, "NotifyWARNTitle", { fg = "#f79000" })
hi(0, "NotifyWARNTitle122", { fg = "#27232c" })
hi(0, "Number", { fg = "#fab387" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#89b4fa" })
hi(0, "NvimTreeFolderIcon", { fg = "#89b4fa" })
hi(0, "NvimTreeFolderName", { fg = "#89b4fa" })
hi(0, "NvimTreeGitDeleted", { fg = "#f38ba8" })
hi(0, "NvimTreeGitDirty", { fg = "#f9e2af" })
hi(0, "NvimTreeGitNew", { fg = "#89b4fa" })
hi(0, "NvimTreeImageFile", { fg = "#cdd6f4" })
hi(0, "NvimTreeIndentMarker", { fg = "#6c7086" })
hi(0, "NvimTreeNormal", { bg = "#181825", fg = "#cdd6f4" })
hi(0, "NvimTreeOpenedFile", { fg = "#f5c2e7" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#89b4fa" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#b4befe" })
hi(0, "NvimTreeSpecialFile", { fg = "#f2cdcd" })
hi(0, "NvimTreeStatuslineNc", { bg = "#181825", fg = "#181825" })
hi(0, "NvimTreeSymlink", { fg = "#f5c2e7" })
hi(0, "NvimTreeWinSeparator", { bg = "#1e1e2e", fg = "#1e1e2e" })
hi(0, "Operator", { fg = "#89dceb" })
hi(0, "Pmenu", { bg = "#2b2b3c", fg = "#9399b2" })
hi(0, "PmenuSbar", { bg = "#45475a" })
hi(0, "PmenuSel", { bg = "#45475a", bold = true })
hi(0, "PmenuThumb", { bg = "#6c7086" })
hi(0, "PreProc", { fg = "#f5c2e7" })
hi(0, "Question", { fg = "#89b4fa" })
hi(0, "QuickFixLine", { bg = "#45475a", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#89b4fa" })
hi(0, "RainbowDelimiterCyan", { fg = "#94e2d5" })
hi(0, "RainbowDelimiterGreen", { fg = "#a6e3a1" })
hi(0, "RainbowDelimiterOrange", { fg = "#fab387" })
hi(0, "RainbowDelimiterRed", { fg = "#f38ba8" })
hi(0, "RainbowDelimiterViolet", { fg = "#cba6f7" })
hi(0, "RainbowDelimiterYellow", { fg = "#f9e2af" })
hi(0, "Repeat", { fg = "#cba6f7" })
hi(0, "Search", { bg = "#3e5767", fg = "#cdd6f4" })
hi(0, "SignColumn", { fg = "#45475a" })
hi(0, "SignColumnSB", { bg = "#11111b", fg = "#45475a" })
hi(0, "Special", { fg = "#f5c2e7" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#f38ba8", undercurl = true })
hi(0, "SpellCap", { sp = "#f9e2af", undercurl = true })
hi(0, "SpellLocal", { sp = "#89b4fa", undercurl = true })
hi(0, "SpellRare", { sp = "#a6e3a1", undercurl = true })
hi(0, "Statement", { fg = "#cba6f7" })
hi(0, "StatusLine", { bg = "#181825", fg = "#cdd6f4" })
hi(0, "StatusLineNC", { bg = "#181825", fg = "#45475a" })
hi(0, "StorageClass", { fg = "#f9e2af" })
hi(0, "String", { fg = "#a6e3a1" })
hi(0, "Structure", { fg = "#f9e2af" })
hi(0, "Substitute", { bg = "#45475a", fg = "#f5c2e7" })
hi(0, "TabLine", { bg = "#181825", fg = "#45475a" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#45475a", fg = "#a6e3a1" })
hi(0, "Tag", { bold = true, fg = "#b4befe" })
hi(0, "TelescopeBorder", { link = "FloatBorder" })
hi(0, "TelescopeMatching", { fg = "#89b4fa" })
hi(0, "TelescopeSelection", { bg = "#313244", bold = true, fg = "#cdd6f4" })
hi(0, "TelescopeSelectionCaret", { fg = "#f2cdcd" })
hi(0, "Title", { bold = true, fg = "#89b4fa" })
hi(0, "Todo", { bg = "#f9e2af", bold = true, fg = "#1e1e2e" })
hi(0, "Type", { fg = "#f9e2af" })
hi(0, "UfoFoldedEllipsis", { bg = "#89b4fa", fg = "#11111b" })
hi(0, "UfoFoldedFg", { fg = "#b4befe" })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", { fg = "#11111b" })
hi(0, "Visual", { bg = "#45475a", bold = true })
hi(0, "VisualNOS", { bg = "#45475a", bold = true })
hi(0, "WarningMsg", { fg = "#f9e2af" })
hi(0, "Whitespace", { fg = "#45475a" })
hi(0, "WildMenu", { bg = "#6c7086" })
hi(0, "WinBar", { fg = "#f5e0dc" })
hi(0, "debugBreakpoint", { bg = "#1e1e2e", fg = "#6c7086" })
hi(0, "debugPC", { bg = "#11111b" })
hi(0, "diffAdded", { fg = "#a6e3a1" })
hi(0, "diffChanged", { fg = "#89b4fa" })
hi(0, "diffIndexLine", { fg = "#94e2d5" })
hi(0, "diffOldFile", { fg = "#f9e2af" })
hi(0, "diffRemoved", { fg = "#f38ba8" })
hi(0, "gitcommitSummary", { fg = "#f5e0dc", italic = true })
hi(0, "healthError", { fg = "#f38ba8" })
hi(0, "healthSuccess", { fg = "#94e2d5" })
hi(0, "healthWarning", { fg = "#f9e2af" })
hi(0, "htmlH1", { bold = true, fg = "#f5c2e7" })
hi(0, "htmlH2", { bold = true, fg = "#89b4fa" })
hi(0, "illuminatedCurWord", { bg = "#45475a" })
hi(0, "illuminatedWord", { bg = "#45475a" })
hi(0, "lCursor", { bg = "#cdd6f4", fg = "#1e1e2e" })
hi(0, "lualine_a_command", { bg = "#40ffff", bold = true, fg = "#000000" })
hi(0, "lualine_a_inactive", { bg = "#a9a9a9", bold = true, fg = "#000000" })
hi(0, "lualine_a_insert", { bg = "#ffa0a0", bold = true, fg = "#000000" })
hi(0, "lualine_a_normal", { bg = "#a9a9a9", bold = true, fg = "#000000" })
hi(0, "lualine_a_replace", { bg = "#ffa0a0", bold = true, fg = "#000000" })
hi(0, "lualine_a_terminal", { bg = "#40ffff", bold = true, fg = "#000000" })
hi(0, "lualine_a_visual", { bg = "#ffa500", bold = true, fg = "#000000" })
hi(0, "lualine_b_command", { bg = "#000000", fg = "#40ffff" })
hi(0, "lualine_b_fancy_diagnostics_error_command", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_b_fancy_diagnostics_error_inactive", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_b_fancy_diagnostics_error_insert", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_b_fancy_diagnostics_error_normal", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_b_fancy_diagnostics_error_replace", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_b_fancy_diagnostics_error_terminal", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_b_fancy_diagnostics_error_visual", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_b_fancy_diagnostics_hint_command", { bg = "#000000", fg = "#d3d3d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_inactive", { bg = "#000000", fg = "#d3d3d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_insert", { bg = "#000000", fg = "#d3d3d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_normal", { bg = "#000000", fg = "#d3d3d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_replace", { bg = "#000000", fg = "#d3d3d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_terminal", { bg = "#000000", fg = "#d3d3d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_visual", { bg = "#000000", fg = "#d3d3d3" })
hi(0, "lualine_b_fancy_diagnostics_info_command", { bg = "#000000", fg = "#add8e6" })
hi(0, "lualine_b_fancy_diagnostics_info_inactive", { bg = "#000000", fg = "#add8e6" })
hi(0, "lualine_b_fancy_diagnostics_info_insert", { bg = "#000000", fg = "#add8e6" })
hi(0, "lualine_b_fancy_diagnostics_info_normal", { bg = "#000000", fg = "#add8e6" })
hi(0, "lualine_b_fancy_diagnostics_info_replace", { bg = "#000000", fg = "#add8e6" })
hi(0, "lualine_b_fancy_diagnostics_info_terminal", { bg = "#000000", fg = "#add8e6" })
hi(0, "lualine_b_fancy_diagnostics_info_visual", { bg = "#000000", fg = "#add8e6" })
hi(0, "lualine_b_fancy_diagnostics_warn_command", { bg = "#000000", fg = "#ffa500" })
hi(0, "lualine_b_fancy_diagnostics_warn_inactive", { bg = "#000000", fg = "#ffa500" })
hi(0, "lualine_b_fancy_diagnostics_warn_insert", { bg = "#000000", fg = "#ffa500" })
hi(0, "lualine_b_fancy_diagnostics_warn_normal", { bg = "#000000", fg = "#ffa500" })
hi(0, "lualine_b_fancy_diagnostics_warn_replace", { bg = "#000000", fg = "#ffa500" })
hi(0, "lualine_b_fancy_diagnostics_warn_terminal", { bg = "#000000", fg = "#ffa500" })
hi(0, "lualine_b_fancy_diagnostics_warn_visual", { bg = "#000000", fg = "#ffa500" })
hi(0, "lualine_b_fancy_diff_added_command", { bg = "#000000", fg = "#90ee90" })
hi(0, "lualine_b_fancy_diff_added_inactive", { bg = "#000000", fg = "#90ee90" })
hi(0, "lualine_b_fancy_diff_added_insert", { bg = "#000000", fg = "#90ee90" })
hi(0, "lualine_b_fancy_diff_added_normal", { bg = "#000000", fg = "#90ee90" })
hi(0, "lualine_b_fancy_diff_added_replace", { bg = "#000000", fg = "#90ee90" })
hi(0, "lualine_b_fancy_diff_added_terminal", { bg = "#000000", fg = "#90ee90" })
hi(0, "lualine_b_fancy_diff_added_visual", { bg = "#000000", fg = "#90ee90" })
hi(0, "lualine_b_fancy_diff_modified_command", { bg = "#000000", fg = "#f0e130" })
hi(0, "lualine_b_fancy_diff_modified_inactive", { bg = "#000000", fg = "#f0e130" })
hi(0, "lualine_b_fancy_diff_modified_insert", { bg = "#000000", fg = "#f0e130" })
hi(0, "lualine_b_fancy_diff_modified_normal", { bg = "#000000", fg = "#f0e130" })
hi(0, "lualine_b_fancy_diff_modified_replace", { bg = "#000000", fg = "#f0e130" })
hi(0, "lualine_b_fancy_diff_modified_terminal", { bg = "#000000", fg = "#f0e130" })
hi(0, "lualine_b_fancy_diff_modified_visual", { bg = "#000000", fg = "#f0e130" })
hi(0, "lualine_b_fancy_diff_removed_command", { bg = "#000000", fg = "#0000ff" })
hi(0, "lualine_b_fancy_diff_removed_inactive", { bg = "#000000", fg = "#0000ff" })
hi(0, "lualine_b_fancy_diff_removed_insert", { bg = "#000000", fg = "#0000ff" })
hi(0, "lualine_b_fancy_diff_removed_normal", { bg = "#000000", fg = "#0000ff" })
hi(0, "lualine_b_fancy_diff_removed_replace", { bg = "#000000", fg = "#0000ff" })
hi(0, "lualine_b_fancy_diff_removed_terminal", { bg = "#000000", fg = "#0000ff" })
hi(0, "lualine_b_fancy_diff_removed_visual", { bg = "#000000", fg = "#0000ff" })
hi(0, "lualine_b_inactive", { bg = "#000000", fg = "#a9a9a9" })
hi(0, "lualine_b_insert", { bg = "#000000", fg = "#ffa0a0" })
hi(0, "lualine_b_normal", { bg = "#000000", fg = "#a9a9a9" })
hi(0, "lualine_b_replace", { bg = "#000000", fg = "#ffa0a0" })
hi(0, "lualine_b_terminal", { bg = "#000000", fg = "#40ffff" })
hi(0, "lualine_b_visual", { bg = "#000000", fg = "#ffa500" })
hi(0, "lualine_c_command", { bg = "#000000", fg = "#505050" })
hi(0, "lualine_c_inactive", { bg = "#000000", fg = "#505050" })
hi(0, "lualine_c_insert", { bg = "#000000", fg = "#505050" })
hi(0, "lualine_c_normal", { bg = "#000000", fg = "#505050" })
hi(0, "lualine_c_replace", { bg = "#000000", fg = "#505050" })
hi(0, "lualine_c_terminal", { bg = "#000000", fg = "#505050" })
hi(0, "lualine_c_visual", { bg = "#000000", fg = "#505050" })
hi(0, "lualine_x_fancy_macro_command", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_inactive", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_insert", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_normal", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_replace", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_terminal", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_visual", { bg = "#000000", fg = "#ff0000" })
hi(0, "lualine_y_fancy_filetype_ts_icon_command", { bg = "#000000", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_inactive", { bg = "#000000", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_insert", { bg = "#000000", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_normal", { bg = "#000000", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_replace", { bg = "#000000", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_terminal", { bg = "#000000", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_visual", { bg = "#000000", fg = "#41942c" })
hi(0, "markdownCode", { fg = "#f2cdcd" })
hi(0, "markdownCodeBlock", { fg = "#f2cdcd" })
hi(0, "markdownH1", { link = "rainbow1" })
hi(0, "markdownH2", { link = "rainbow2" })
hi(0, "markdownH3", { link = "rainbow3" })
hi(0, "markdownH4", { link = "rainbow4" })
hi(0, "markdownH5", { link = "rainbow5" })
hi(0, "markdownH6", { link = "rainbow6" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#fab387" })
hi(0, "markdownLinkText", { fg = "#89b4fa", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#1e1e2e", fg = "#cdd6f4" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#f2cdcd" })
hi(0, "mkdCodeStart", { bold = true, fg = "#f2cdcd" })
hi(0, "qfFileName", { fg = "#89b4fa" })
hi(0, "qfLineNr", { fg = "#f9e2af" })
hi(0, "rainbow1", { fg = "#f38ba8" })
hi(0, "rainbow2", { fg = "#fab387" })
hi(0, "rainbow3", { fg = "#f9e2af" })
hi(0, "rainbow4", { fg = "#a6e3a1" })
hi(0, "rainbow5", { fg = "#74c7ec" })
hi(0, "rainbow6", { fg = "#b4befe" })
hi(0, "zshKSHFunction", { link = "Function" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1a2331"
g.terminal_color_1 = "#f6b2ba"
g.terminal_color_2 = "#a6d5a8"
g.terminal_color_3 = "#d1c98c"
g.terminal_color_4 = "#94cff4"
g.terminal_color_5 = "#e3b5e3"
g.terminal_color_6 = "#87d8d3"
g.terminal_color_7 = "#c3c7cd"
g.terminal_color_8 = "#1a2331"
g.terminal_color_9 = "#f6b2ba"
g.terminal_color_10 = "#a6d5a8"
g.terminal_color_11 = "#d1c98c"
g.terminal_color_12 = "#94cff4"
g.terminal_color_13 = "#e3b5e3"
g.terminal_color_14 = "#87d8d3"
g.terminal_color_15 = "#c3c7cd"
