-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "nvim-dark2"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@diff.delta", { link = "Changed" })
hi(0, "@diff.minus", { link = "Removed" })
hi(0, "@diff.plus", { link = "Added" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@ibl.indent.char.1", { fg = "#4f5258" })
hi(0, "@ibl.scope.char.1", { fg = "#4f5258", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#4f5258", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#4f5258" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.heading.1", { bg = "#2c2e33", fg = "#8cf8f7" })
hi(0, "@markup.heading.2", { bg = "#2c2e33", fg = "#b3f6c0" })
hi(0, "@markup.heading.3", { bg = "#2c2e33" })
hi(0, "@markup.heading.4", { bg = "#2c2e33" })
hi(0, "@markup.heading.5", { bg = "#2c2e33" })
hi(0, "@markup.heading.6", { bg = "#2c2e33" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.escape", { link = "@string.special" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "CccHighlighterfce094", { bg = "#fce094", fg = "#000000" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#9b9ea4" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#8cf8f7" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "FzfLuaBackdrop", { bg = "#000000" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#98f5ff" })
hi(0, "FzfLuaBufFlagCur", { fg = "#ff4040" })
hi(0, "FzfLuaBufName", { fg = "#ffbbff" })
hi(0, "FzfLuaBufNr", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderBind", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderText", { fg = "#ff4040" })
hi(0, "FzfLuaLiveSym", { fg = "#ff4040" })
hi(0, "FzfLuaPathColNr", { fg = "#98f5ff" })
hi(0, "FzfLuaPathLineNr", { fg = "#90ee90" })
hi(0, "FzfLuaScrollBorderBackCompat", { bg = "#e0e2ea", fg = "#14161b" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#ffebcd" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#b0e2ff" })
hi(0, "GitSignsStagedAdd", { fg = "#597b60" })
hi(0, "GitSignsStagedAddCul", { fg = "#597b60" })
hi(0, "GitSignsStagedAddLn", { bg = "#005523", fg = "#77787c" })
hi(0, "GitSignsStagedAddNr", { fg = "#597b60" })
hi(0, "GitSignsStagedChange", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangeCul", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangeLn", { bg = "#4f5258", fg = "#77787c" })
hi(0, "GitSignsStagedChangeNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedelete", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#4f5258", fg = "#77787c" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedDelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#7f605c" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7f605c" })
hi(0, "IblIndent", { link = "NonText" })
hi(0, "IblScope", { fg = "#4f5258" })
hi(0, "IblWhitespace", { link = "NonText" })
hi(0, "IndentBlanklineChar", { fg = "#4f5258", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#e0e2ea", nocombine = true })
hi(0, "IndentBlanklineContextStart", { sp = "#e0e2ea", underline = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#4f5258", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#4f5258", nocombine = true })
hi(0, "MarkviewBlockQuoteDefault", { fg = "#9b9ea4" })
hi(0, "MarkviewBlockQuoteError", { fg = "#ffc0b9" })
hi(0, "MarkviewBlockQuoteNote", { fg = "#8cf8f7" })
hi(0, "MarkviewBlockQuoteOk", { fg = "#b3f6c0" })
hi(0, "MarkviewBlockQuoteSpecial", { fg = "#e0e2ea" })
hi(0, "MarkviewBlockQuoteWarn", { fg = "#fce094" })
hi(0, "MarkviewCheckboxCancelled", { fg = "#9b9ea4" })
hi(0, "MarkviewCheckboxChecked", { fg = "#b3f6c0" })
hi(0, "MarkviewCheckboxPending", { fg = "#fce094" })
hi(0, "MarkviewCheckboxProgress", { fg = "#e0e2ea" })
hi(0, "MarkviewCheckboxStriked", { fg = "#9b9ea4", strikethrough = true })
hi(0, "MarkviewCheckboxUnchecked", { fg = "#ffc0b9" })
hi(0, "MarkviewCode", { bg = "#1e2129" })
hi(0, "MarkviewCodeInfo", { bg = "#1e2129", fg = "#9b9ea4" })
hi(0, "MarkviewGradient1", { fg = "#14161b" })
hi(0, "MarkviewGradient10", { fg = "#e0e2ea" })
hi(0, "MarkviewGradient2", { fg = "#2a2c32" })
hi(0, "MarkviewGradient3", { fg = "#414349" })
hi(0, "MarkviewGradient4", { fg = "#585a60" })
hi(0, "MarkviewGradient5", { fg = "#6e7077" })
hi(0, "MarkviewGradient6", { fg = "#85878e" })
hi(0, "MarkviewGradient7", { fg = "#9c9ea5" })
hi(0, "MarkviewGradient8", { fg = "#b2b4bc" })
hi(0, "MarkviewGradient9", { fg = "#c9cbd3" })
hi(0, "MarkviewHeading1", { bg = "#395460", fg = "#8cf8f7" })
hi(0, "MarkviewHeading1Sign", { fg = "#8cf8f7" })
hi(0, "MarkviewHeading2", { bg = "#435452", fg = "#b3f6c0" })
hi(0, "MarkviewHeading2Sign", { fg = "#b3f6c0" })
hi(0, "MarkviewHeading3", { bg = "#4e4f5d", fg = "#e0e2ea" })
hi(0, "MarkviewHeading3Sign", { fg = "#e0e2ea" })
hi(0, "MarkviewHeading4", { bg = "#4e4f5d", fg = "#e0e2ea" })
hi(0, "MarkviewHeading4Sign", { fg = "#e0e2ea" })
hi(0, "MarkviewHeading5", { bg = "#4e4f5d", fg = "#e0e2ea" })
hi(0, "MarkviewHeading5Sign", { fg = "#e0e2ea" })
hi(0, "MarkviewHeading6", { bg = "#4e4f5d", fg = "#e0e2ea" })
hi(0, "MarkviewHeading6Sign", { fg = "#e0e2ea" })
hi(0, "MarkviewIcon1", { bg = "#1e2129", fg = "#8cf8f7" })
hi(0, "MarkviewIcon1Fg", { fg = "#8cf8f7" })
hi(0, "MarkviewIcon1Sign", { fg = "#8cf8f7" })
hi(0, "MarkviewIcon2", { bg = "#1e2129", fg = "#b3f6c0" })
hi(0, "MarkviewIcon2Fg", { fg = "#b3f6c0" })
hi(0, "MarkviewIcon2Sign", { fg = "#b3f6c0" })
hi(0, "MarkviewIcon3", { bg = "#1e2129", fg = "#e0e2ea" })
hi(0, "MarkviewIcon3Fg", { fg = "#e0e2ea" })
hi(0, "MarkviewIcon3Sign", { fg = "#e0e2ea" })
hi(0, "MarkviewIcon4", { bg = "#1e2129", fg = "#e0e2ea" })
hi(0, "MarkviewIcon4Fg", { fg = "#e0e2ea" })
hi(0, "MarkviewIcon4Sign", { fg = "#e0e2ea" })
hi(0, "MarkviewIcon5", { bg = "#1e2129", fg = "#e0e2ea" })
hi(0, "MarkviewIcon5Fg", { fg = "#e0e2ea" })
hi(0, "MarkviewIcon5Sign", { fg = "#e0e2ea" })
hi(0, "MarkviewIcon6", { bg = "#1e2129", fg = "#e0e2ea" })
hi(0, "MarkviewIcon6Fg", { fg = "#e0e2ea" })
hi(0, "MarkviewIcon6Sign", { fg = "#e0e2ea" })
hi(0, "MarkviewInlineCode", { bg = "#292d38" })
hi(0, "MarkviewLatexSubscript", { fg = "#9d9173", italic = true })
hi(0, "MarkviewLatexSuperscript", { fg = "#6b916b", italic = true })
hi(0, "MarkviewListItemMinus", { fg = "#fce094" })
hi(0, "MarkviewListItemPlus", { fg = "#b3f6c0" })
hi(0, "MarkviewListItemStar", { fg = "#8cf8f7" })
hi(0, "MarkviewTableAlignCenter", { fg = "#8cf8f7" })
hi(0, "MarkviewTableAlignLeft", { fg = "#8cf8f7" })
hi(0, "MarkviewTableAlignRight", { fg = "#8cf8f7" })
hi(0, "MarkviewTableBorder", { fg = "#8cf8f7" })
hi(0, "MarkviewTableHeader", { fg = "#8cf8f7" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniHipatternsFixme", { bold = true, ctermfg = 9, fg = "#ffc0b9", reverse = true })
hi(0, "MiniHipatternsHack", { bold = true, ctermfg = 11, fg = "#fce094", reverse = true })
hi(0, "MiniHipatternsNote", { bold = true, ctermfg = 12, fg = "#a6dbff", reverse = true })
hi(0, "MiniHipatternsTodo", { bold = true, ctermfg = 14, fg = "#8cf8f7", reverse = true })
hi(0, "NoiceFormatProgressDone", { bg = "#6b5300", fg = "#eef1f8" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NotifyDEBUGBorder", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGIcon", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGTitle", { fg = "#8b8b8b" })
hi(0, "NotifyERRORBody2", { bg = "#14161b", fg = "#1c1e23" })
hi(0, "NotifyERRORBorder", { fg = "#8a1f1f" })
hi(0, "NotifyERRORBorder2", { fg = "#19161b" })
hi(0, "NotifyERRORIcon", { fg = "#f70067" })
hi(0, "NotifyERRORIcon2", { fg = "#1d151e" })
hi(0, "NotifyERRORTitle", { fg = "#f70067" })
hi(0, "NotifyERRORTitle2", { fg = "#1d151e" })
hi(0, "NotifyINFOBody4", { bg = "#14161b", fg = "#1c1e23" })
hi(0, "NotifyINFOBorder", { fg = "#4f6752" })
hi(0, "NotifyINFOBorder4", { fg = "#16191d" })
hi(0, "NotifyINFOIcon", { fg = "#a9ff68" })
hi(0, "NotifyINFOIcon4", { fg = "#1a1f1e" })
hi(0, "NotifyINFOTitle", { fg = "#a9ff68" })
hi(0, "NotifyINFOTitle4", { fg = "#1a1f1e" })
hi(0, "NotifyTRACEBorder", { fg = "#4f3552" })
hi(0, "NotifyTRACEIcon", { fg = "#d484ff" })
hi(0, "NotifyTRACETitle", { fg = "#d484ff" })
hi(0, "NotifyWARNBorder", { fg = "#79491d" })
hi(0, "NotifyWARNIcon", { fg = "#f79000" })
hi(0, "NotifyWARNTitle", { fg = "#f79000" })
hi(0, "StatusLine", { link = "NormalFloat" })
hi(0, "bg_.bg1_fg_.bg1_", { bg = "#2a2c32", fg = "#2a2c32" })
hi(0, "bg_.bg1_fg_.blue_", { bg = "#2a2c32", fg = "#c4c6cd" })
hi(0, "bg_.bg1_fg_.green_", { bg = "#2a2c32", fg = "#90ee90" })
hi(0, "bg_.bg1_fg__", { bg = "#2a2c32" })
hi(0, "bg_.bg1_fg_bg1_", { bg = "#2a2c32", fg = "#2a2c32" })
hi(0, "bg_.bg2_fg_.bg2_", { bg = "#414349", fg = "#414349" })
hi(0, "bg_.bg2_fg_.blue_", { bg = "#414349", fg = "#c4c6cd" })
hi(0, "bg_.bg2_fg__", { bg = "#414349" })
hi(0, "bg_.blue_fg_.bg_", { bg = "#c4c6cd", fg = "#14161b" })
hi(0, "bg_.blue_fg_.blue_", { bg = "#c4c6cd", fg = "#c4c6cd" })
hi(0, "bg_.cyan_fg_07080d_", { bg = "#98f5ff", fg = "#07080d" })
hi(0, "bg_.yellow_fg_07080d_", { bg = "#fce094", fg = "#07080d" })
hi(0, "bg_07080d_fg_07080d_", { bg = "#07080d", fg = "#07080d" })
hi(0, "bg_07080d_fg__", { bg = "#07080d" })
hi(0, "bg_blue_fg_bg1_", { bg = "#c4c6cd", fg = "#2a2c32" })
hi(0, "bg_cyan_fg_bg1_", { bg = "#98f5ff", fg = "#2a2c32" })
hi(0, "bg_green_fg_bg1_", { bg = "#90ee90", fg = "#2a2c32" })
hi(0, "incline__gui_bold", { bold = true })
hi(0, "incline__guibg_353b4c", { bg = "#14161b" })
hi(0, "incline__guibg_51a0cf__guifg_000000", { bg = "#51a0cf", fg = "#000000" })
hi(0, "incline__guibg_8cf8f7__guifg_000000", { bg = "#8cf8f7", fg = "#000000" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#07080d"
g.terminal_color_1 = "#ff4040"
g.terminal_color_2 = "#90ee90"
g.terminal_color_3 = "#fce094"
g.terminal_color_4 = "#c4c6cd"
g.terminal_color_5 = "#ffbbff"
g.terminal_color_6 = "#98f5ff"
g.terminal_color_8 = "#14161b"
g.terminal_color_9 = "#ff4040"
g.terminal_color_10 = "#90ee90"
g.terminal_color_11 = "#fce094"
g.terminal_color_12 = "#c4c6cd"
g.terminal_color_13 = "#ffbbff"
g.terminal_color_14 = "#98f5ff"
g.terminal_color_15 = "#e0e2ea"
