-- Made with 'mini.colors' module of https://nvim-mini.org/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "poimandres-custom"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@constant.builtin", { fg = "#add7ff" })
hi(0, "@constant.falsy", { fg = "#d0679d" })
hi(0, "@constructor", { fg = "#5de4c7" })
hi(0, "@function.builtin", { fg = "#add7ff" })
hi(0, "@function.call", { fg = "#a6accd" })
hi(0, "@ibl.indent.char.1", { fg = "#506477", nocombine = true })
hi(0, "@ibl.scope.char.1", { fg = "#506477", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#506477", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#506477", nocombine = true })
hi(0, "@import.identifier.tsx", { fg = "#add7ff" })
hi(0, "@import.identifier.typescript", { fg = "#add7ff" })
hi(0, "@keyword.export.tsx", { fg = "#5de4c7" })
hi(0, "@keyword.export.typescript", { fg = "#5de4c7" })
hi(0, "@keyword.function", { fg = "#add7ff" })
hi(0, "@keyword.import.tsx", { fg = "#5de4c7" })
hi(0, "@keyword.import.typescript", { fg = "#5de4c7" })
hi(0, "@keyword.operator", { fg = "#5de4c7" })
hi(0, "@keyword.return", { fg = "#5fb3a1" })
hi(0, "@label", { fg = "#91b4d5" })
hi(0, "@markup.heading.1", { fg = "#e4f0fb", bg = "#1e2a38", bold = true })
hi(0, "@markup.heading.2", { fg = "#5de4c7", bg = "#1e2a38", bold = true })
hi(0, "@markup.heading.3", { fg = "#89ddff", bg = "#1e2a38" })
hi(0, "@markup.heading.4", { fg = "#add7ff", bg = "#1e2a38" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#1b1e28", fg = "#1b1e28", nocombine = true, sp = "#e4f0fb", underdouble = true })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#1b1e28", fg = "#1b1e28", nocombine = true, sp = "#e4f0fb", underline = true })
hi(0, "@method", { fg = "#5de4c7" })
hi(0, "@parameter", { fg = "#e4f0fb" })
hi(0, "@property", { fg = "#add7ff" })
hi(0, "@punctuation.bracket", { fg = "#e4f0fb" })
hi(0, "@punctuation.delimiter", { fg = "#91b4d5" })
hi(0, "@punctuation.special", { fg = "#91b4d5" })
hi(0, "@string.escape", { fg = "#d0679d" })
hi(0, "@tag", { fg = "#5de4c7" })
hi(0, "@tag.attribute", { fg = "#91b4d5", italic = true })
hi(0, "@tag.delimiter", { fg = "#e4f0fb" })
hi(0, "@text", { fg = "#e4f0fb" })
hi(0, "@title", { bold = true, fg = "#5fb3a1" })
hi(0, "@type.builtin", { link = "Type" })
hi(0, "@variable", { fg = "#e4f0fb" })
hi(0, "@variable.builtin", { fg = "#add7ff" })
hi(0, "ActionPreviewBorder", { link = "SagaBorder" })
hi(0, "ActionPreviewNormal", { link = "SagaNormal" })
hi(0, "ActionPreviewTitle", { bg = "#1b1e28", fg = "#767c9d" })
hi(0, "BlinkCmpSignatureHelpBorder", { link = "CursorLine" })
hi(0, "BlinkCmpSignatureHelp", { link = "CursorLine" })
hi(0, "BlinkCmpDocBorder", { link = "CursorLine" })
hi(0, "BlinkCmpDocSeparator", { link = "CursorLine" })
hi(0, "BlinkCmpDoc", { link = "CursorLine" })
hi(0, "BlinkCmpKind", { link = "CursorLineSign" })
hi(0, "BlinkCmpMenu", { link = "CursorLine" })
hi(0, "BlinkCmpMenuSelection", { link = "Cursor" })
hi(0, "BlinkCmpCursorLineMenuHack", { bg = "#303340" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#5de4c7" })
hi(0, "BufferCurrent", { bg = "#1b1e28", fg = "#e4f0fb" })
hi(0, "BufferCurrentIndex", { bg = "#1b1e28", fg = "#e4f0fb" })
hi(0, "BufferCurrentMod", { bg = "#1b1e28", fg = "#5de4c7" })
hi(0, "BufferCurrentSign", { bg = "#1b1e28", fg = "#a6accd" })
hi(0, "BufferCurrentTarget", { bg = "#1b1e28", fg = "#fffac2" })
hi(0, "BufferInactive", { fg = "#a6accd" })
hi(0, "BufferInactiveIndex", { fg = "#a6accd" })
hi(0, "BufferInactiveMod", { fg = "#5de4c7" })
hi(0, "BufferInactiveSign", { fg = "#767c9d" })
hi(0, "BufferInactiveTarget", { fg = "#fffac2" })
hi(0, "BufferTabpageFill", { bg = "#1b1e28", fg = "#1b1e28" })
hi(0, "BufferVisible", { fg = "#a6accd" })
hi(0, "BufferVisibleIndex", { fg = "#a6accd" })
hi(0, "BufferVisibleMod", { fg = "#5de4c7" })
hi(0, "BufferVisibleSign", { fg = "#767c9d" })
hi(0, "BufferVisibleTarget", { fg = "#fffac2" })
hi(0, "CallHierarchyBorder", { link = "SagaBorder" })
hi(0, "CallHierarchyIcon", { fg = "#fcc5e9" })
hi(0, "CallHierarchyNormal", { link = "SagaNormal" })
hi(0, "CallHierarchyTitle", { fg = "#fcc5e9" })
hi(0, "Character", { fg = "#d0679d" })
hi(0, "CmpItemAbbr", { fg = "#767c9d" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#d0679d", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e4f0fb" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#5de4c7" })
hi(0, "CmpItemKind", { fg = "#91b4d5" })
hi(0, "CmpItemKindClass", { fg = "#fffac2" })
hi(0, "CmpItemKindFunction", { fg = "#89ddff" })
hi(0, "CmpItemKindInterface", { fg = "#add7ff" })
hi(0, "CmpItemKindMethod", { fg = "#d0679d" })
hi(0, "CmpItemKindSnippet", { fg = "#a6accd" })
hi(0, "CmpItemKindVariable", { fg = "#5de4c7" })
hi(0, "CodeActionBorder", { link = "SagaBorder" })
hi(0, "CodeActionNormal", { link = "SagaNormal" })
hi(0, "CodeActionNumber", { fg = "#91b4d5" })
hi(0, "CodeActionText", { fg = "#fffac2" })
hi(0, "ColorColumn", { bg = "#a6accd" })
hi(0, "Comment", { fg = "#a6accd" })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#a6accd" })
hi(0, "Constant", { fg = "#e4f0fb" })
hi(0, "CurSearch", { bg = "#add7ff", fg = "#171922" })
hi(0, "Cursor", { bg = "#a6accd", fg = "#171922" })
hi(0, "CursorColumn", { bg = "#303340" })
hi(0, "CursorLine", { bg = "#303340" })
hi(0, "CursorLineNr", { fg = "#e4f0fb" })
hi(0, "DarkenedPanel", { bg = "#171922" })
hi(0, "DarkenedStatusline", { bg = "#171922" })
hi(0, "DefinitionBorder", { link = "SagaBorder" })
hi(0, "DefinitionNormal", { link = "SagaNormal" })
hi(0, "DefinitionSearch", { link = "Search" })
hi(0, "Delimiter", { fg = "#a6accd" })
hi(0, "DiagnosticBorder", { link = "SagaBorder" })
hi(0, "DiagnosticDefaultError", { fg = "#d0679d" })
hi(0, "DiagnosticDefaultHint", { fg = "#89ddff" })
hi(0, "DiagnosticDefaultInfo", { fg = "#91b4d5" })
hi(0, "DiagnosticDefaultWarn", { fg = "#fffac2" })
hi(0, "DiagnosticError", { ctermfg = 9, fg = "#d0679d" })
hi(0, "DiagnosticErrorBorder", { link = "DiagnosticError" })
hi(0, "DiagnosticFloatingError", { fg = "#d0679d" })
hi(0, "DiagnosticFloatingHint", { fg = "#89ddff" })
hi(0, "DiagnosticFloatingInfo", { fg = "#91b4d5" })
hi(0, "DiagnosticFloatingWarn", { fg = "#fffac2" })
hi(0, "DiagnosticHint", { ctermfg = 12, fg = "#89ddff" })
hi(0, "DiagnosticHintBorder", { link = "DiagnosticHint" })
hi(0, "DiagnosticInfo", { ctermfg = 14, fg = "#91b4d5" })
hi(0, "DiagnosticInfoBorder", { link = "DiagnosticInfo" })
hi(0, "DiagnosticNormal", { link = "SagaNormal" })
hi(0, "DiagnosticPos", { fg = "#767c9d" })
hi(0, "DiagnosticSignError", { fg = "#d0679d" })
hi(0, "DiagnosticSignHint", { fg = "#89ddff" })
hi(0, "DiagnosticSignInfo", { fg = "#91b4d5" })
hi(0, "DiagnosticSignWarn", { fg = "#fffac2" })
hi(0, "DiagnosticSource", { fg = "#767c9d" })
hi(0, "DiagnosticStatusLineError", { bg = "#171922", fg = "#d0679d" })
hi(0, "DiagnosticStatusLineHint", { bg = "#171922", fg = "#89ddff" })
hi(0, "DiagnosticStatusLineInfo", { bg = "#171922", fg = "#91b4d5" })
hi(0, "DiagnosticStatusLineWarn", { bg = "#171922", fg = "#fffac2" })
hi(0, "DiagnosticUnderlineError", { sp = "#d0679d", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#89ddff", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#91b4d5", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#fffac2", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { fg = "#d0679d" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#89ddff" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#91b4d5" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#fffac2" })
hi(0, "DiagnosticWarn", { ctermfg = 11, fg = "#fffac2" })
hi(0, "DiagnosticWarnBorder", { link = "DiagnosticWarn" })
hi(0, "DiagnosticWord", { fg = "#ffffff" })
hi(0, "DiffAdd", { bg = "#3c8178", ctermbg = 10, ctermfg = 0 })
hi(0, "DiffChange", { bg = "#a6accd" })
hi(0, "DiffDelete", { bg = "#764363", ctermfg = 9 })
hi(0, "DiffText", { bg = "#3d6965", ctermbg = 14, ctermfg = 0 })
hi(0, "Directory", { ctermfg = 14, fg = "#91b4d5" })
hi(0, "Error", { ctermbg = 9, ctermfg = 0, fg = "#d0679d" })
hi(0, "ErrorMsg", { bold = true, ctermfg = 9, fg = "#d0679d" })
hi(0, "Exception", { fg = "#91b4d5" })
hi(0, "FinderBorder", { link = "SagaBorder" })
hi(0, "FinderCount", { link = "Label" })
hi(0, "FinderFileName", { fg = "#ffffff" })
hi(0, "FinderIcon", { fg = "#fffac2" })
hi(0, "FinderNormal", { link = "SagaNormal" })
hi(0, "FinderPreviewBorder", { link = "SagaBorder" })
hi(0, "FinderPreviewSearch", { link = "Search" })
hi(0, "FinderSelection", { fg = "#767c9d" })
hi(0, "FinderSpinner", { fg = "#d0679d" })
hi(0, "FinderSpinnerTitle", { fg = "#d0679d" })
hi(0, "FinderType", { fg = "#5de4c7" })
hi(0, "FinderVirtText", { fg = "#89ddff" })
hi(0, "Float", { fg = "#5de4c7" })
hi(0, "FloatBorder", { fg = "#171922" })
hi(0, "FloatTitle", { fg = "#767c9d" })
hi(0, "FoldColumn", { fg = "#767c9d" })
hi(0, "Folded", { bg = "#171922", fg = "#e4f0fb" })
hi(0, "Function", { ctermfg = 14, fg = "#add7ff" })
hi(0, "FzfLuaBackdrop", { bg = "#000000" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#98f5ff" })
hi(0, "FzfLuaBufFlagCur", { fg = "#ff4040" })
hi(0, "FzfLuaBufNr", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderBind", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderText", { fg = "#ff4040" })
hi(0, "FzfLuaLivePrompt", { fg = "#ff82ab" })
hi(0, "FzfLuaLiveSym", { fg = "#ff82ab" })
hi(0, "FzfLuaPathColNr", { fg = "#98f5ff" })
hi(0, "FzfLuaPathLineNr", { fg = "#90ee90" })
hi(0, "FzfLuaScrollBorderBackCompat", { bg = "#e4f0fb", fg = "#1b1e28" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#ffebcd" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#b0e2ff" })
hi(0, "GitSignsAdd", { fg = "#5de4c7" })
hi(0, "GitSignsChange", { fg = "#add7ff" })
hi(0, "GitSignsDelete", { fg = "#d0679d" })
hi(0, "GitSignsStagedAdd", { fg = "#2e7263" })
hi(0, "GitSignsStagedAddCul", { fg = "#2e7263" })
hi(0, "GitSignsStagedAddLn", { bg = "#3c8178" })
hi(0, "GitSignsStagedAddNr", { fg = "#2e7263" })
hi(0, "GitSignsStagedChange", { fg = "#566b7f" })
hi(0, "GitSignsStagedChangeCul", { fg = "#566b7f" })
hi(0, "GitSignsStagedChangeLn", { bg = "#a6accd" })
hi(0, "GitSignsStagedChangeNr", { fg = "#566b7f" })
hi(0, "GitSignsStagedChangedelete", { fg = "#566b7f" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#566b7f" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#a6accd" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#566b7f" })
hi(0, "GitSignsStagedDelete", { fg = "#68334e" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#68334e" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#68334e" })
hi(0, "GitSignsStagedTopdelete", { fg = "#68334e" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#68334e" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#68334e" })
hi(0, "GitSignsStagedUntracked", { fg = "#2e7263" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#2e7263" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#3c8178" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#2e7263" })
hi(0, "HeaderGradient1", { fg = "#84ddf8" })
hi(0, "HeaderGradient2", { fg = "#7fdef2" })
hi(0, "HeaderGradient3", { fg = "#7adfec" })
hi(0, "HeaderGradient4", { fg = "#75e0e6" })
hi(0, "HeaderGradient5", { fg = "#70e0df" })
hi(0, "HeaderGradient6", { fg = "#6be1d9" })
hi(0, "HeaderGradient7", { fg = "#66e2d3" })
hi(0, "HeaderGradient8", { fg = "#61e3cd" })
hi(0, "HeaderGradient9", { fg = "#5de4c7" })
hi(0, "HopCursor", { fg = "#91b4d5" })
hi(0, "HopNextKey", { fg = "#89ddff" })
hi(0, "HopNextKey1", { fg = "#5de4c7" })
hi(0, "HopNextKey2", { fg = "#5fb3a1" })
hi(0, "HopUnmatched", { fg = "#506477" })
hi(0, "HoverBorder", { link = "SagaBorder" })
hi(0, "HoverNormal", { link = "SagaNormal" })
hi(0, "IblIndent", { fg = "#506477" })
hi(0, "IblScope", { fg = "#506477" })
hi(0, "IblWhitespace", { fg = "#506477" })
hi(0, "Identifier", { ctermfg = 12, fg = "#a6accd" })
hi(0, "IncSearch", { bg = "#add7ff", fg = "#171922" })
hi(0, "Include", { fg = "#a6accd" })
hi(0, "IndentBlanklineChar", { fg = "#303340" })
hi(0, "IndentBlanklineContextChar", { fg = "#fffac2" })
hi(0, "IndentBlanklineContextStart", { fg = "#fffac2" })
hi(0, "IndentBlanklineSpaceChar", { link = "Whitespace" })
hi(0, "IndentBlanklineSpaceCharBlankline", { link = "Whitespace" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#91b4d5" })
hi(0, "Label", { fg = "#e4f0fb" })
hi(0, "LeapBackground", { bg = "#303340" })
hi(0, "LeapLabelPrimary", { bg = "#5de4c7", fg = "#1b1e28" })
hi(0, "LeapLabelSecondary", { bg = "#89ddff", fg = "#1b1e28" })
hi(0, "LeapLabelSelected", { bg = "#fffac2", fg = "#1b1e28" })
hi(0, "LeapMatch", { bg = "#fcc5e9", fg = "#1b1e28" })
hi(0, "LineNr", { fg = "#506477" })
hi(0, "LspCodeLens", { fg = "#a6accd" })
hi(0, "LspCodeLensSeparator", { fg = "#506477" })
hi(0, "LspReferenceRead", { bg = "#add7ff" })
hi(0, "LspReferenceText", { bg = "#add7ff" })
hi(0, "LspReferenceWrite", { bg = "#add7ff" })
hi(0, "LspSagaLightBulb", { link = "DiagnosticSignHint" })
hi(0, "LspSignatureActiveParameter", { bg = "#a6accd" })
hi(0, "MarkviewBlockQuoteDefault", { link = "MarkviewPalette0Fg" })
hi(0, "MarkviewBlockQuoteError", { link = "MarkviewPalette1Fg" })
hi(0, "MarkviewBlockQuoteNote", { link = "MarkviewPalette5Fg" })
hi(0, "MarkviewBlockQuoteOk", { link = "MarkviewPalette4Fg" })
hi(0, "MarkviewBlockQuoteSpecial", { link = "MarkviewPalette3Fg" })
hi(0, "MarkviewBlockQuoteWarn", { link = "MarkviewPalette2Fg" })
hi(0, "MarkviewCheckboxCancelled", { link = "MarkviewPalette0Fg" })
hi(0, "MarkviewCheckboxChecked", { link = "MarkviewPalette4Fg" })
hi(0, "MarkviewCheckboxPending", { link = "MarkviewPalette2Fg" })
hi(0, "MarkviewCheckboxProgress", { link = "MarkviewPalette6Fg" })
hi(0, "MarkviewCheckboxStriked", { fg = "#a6abcc", strikethrough = true })
hi(0, "MarkviewCheckboxUnchecked", { link = "MarkviewPalette1Fg" })
hi(0, "MarkviewCode", { bg = "#292d3a" })
hi(0, "MarkviewCodeFg", { fg = "#292d3a" })
hi(0, "MarkviewCodeInfo", { bg = "#292d3a", fg = "#a6accd" })
hi(0, "MarkviewEmail", { link = "@markup.link.url.markdown_inline" })
hi(0, "MarkviewGradient0", { fg = "#1b1d27" })
hi(0, "MarkviewGradient1", { fg = "#252934" })
hi(0, "MarkviewGradient2", { fg = "#323643" })
hi(0, "MarkviewGradient3", { fg = "#414754" })
hi(0, "MarkviewGradient4", { fg = "#545a68" })
hi(0, "MarkviewGradient5", { fg = "#69707f" })
hi(0, "MarkviewGradient6", { fg = "#828a98" })
hi(0, "MarkviewGradient7", { fg = "#9fa8b6" })
hi(0, "MarkviewGradient8", { fg = "#bfcad6" })
hi(0, "MarkviewGradient9", { fg = "#e4effa" })
hi(0, "MarkviewHeading1", { link = "@markup.heading.1" })
hi(0, "MarkviewHeading1Sign", { link = "MarkviewPalette1Sign" })
hi(0, "MarkviewHeading2", { link = "@markup.heading.2" })
hi(0, "MarkviewHeading2Sign", { link = "MarkviewPalette2Sign" })
hi(0, "MarkviewHeading3", { link = "@markup.heading.3" })
hi(0, "MarkviewHeading3Sign", { link = "MarkviewPalette3Sign" })
hi(0, "MarkviewHeading4", { link = "@markup.heading.4" })
hi(0, "MarkviewHeading4Sign", { link = "MarkviewPalette4Sign" })
hi(0, "MarkviewHeading5", { link = "MarkviewPalette5" })
hi(0, "MarkviewHeading5Sign", { link = "MarkviewPalette5Sign" })
hi(0, "MarkviewHeading6", { link = "MarkviewPalette6" })
hi(0, "MarkviewHeading6Sign", { link = "MarkviewPalette6Sign" })
hi(0, "MarkviewHyperlink", { link = "@markup.link.label.markdown_inline" })
hi(0, "MarkviewIcon0", { bg = "#292d3a", fg = "#a6abcc" })
hi(0, "MarkviewIcon1", { bg = "#292d3a", fg = "#e4effa" })
hi(0, "MarkviewIcon2", { bg = "#292d3a", fg = "#e4effa" })
hi(0, "MarkviewIcon3", { bg = "#292d3a", fg = "#e4effa" })
hi(0, "MarkviewIcon4", { bg = "#292d3a", fg = "#e4effa" })
hi(0, "MarkviewIcon5", { bg = "#292d3a", fg = "#e4effa" })
hi(0, "MarkviewIcon6", { bg = "#292d3a", fg = "#e4effa" })
hi(0, "MarkviewImage", { link = "@markup.link.label.markdown_inline" })
hi(0, "MarkviewInlineCode", { bg = "#2f3342" })
hi(0, "MarkviewListItemMinus", { link = "MarkviewPalette2Fg" })
hi(0, "MarkviewListItemPlus", { link = "MarkviewPalette4Fg" })
hi(0, "MarkviewListItemStar", { link = "MarkviewPalette6Fg" })
hi(0, "MarkviewPalette0", { bg = "#262936", fg = "#a6abcc" })
hi(0, "MarkviewPalette0Bg", { bg = "#262936" })
hi(0, "MarkviewPalette0Fg", { fg = "#a6abcc" })
hi(0, "MarkviewPalette0Sign", { fg = "#a6abcc" })
hi(0, "MarkviewPalette1", { bg = "#292d39", fg = "#e4effa" })
hi(0, "MarkviewPalette1Bg", { bg = "#292d39" })
hi(0, "MarkviewPalette1Fg", { fg = "#e4effa" })
hi(0, "MarkviewPalette1Sign", { fg = "#e4effa" })
hi(0, "MarkviewPalette2", { bg = "#292d39", fg = "#e4effa" })
hi(0, "MarkviewPalette2Bg", { bg = "#292d39" })
hi(0, "MarkviewPalette2Fg", { fg = "#e4effa" })
hi(0, "MarkviewPalette2Sign", { fg = "#e4effa" })
hi(0, "MarkviewPalette3", { bg = "#292d39", fg = "#e4effa" })
hi(0, "MarkviewPalette3Bg", { bg = "#292d39" })
hi(0, "MarkviewPalette3Fg", { fg = "#e4effa" })
hi(0, "MarkviewPalette3Sign", { fg = "#e4effa" })
hi(0, "MarkviewPalette4", { bg = "#292d39", fg = "#e4effa" })
hi(0, "MarkviewPalette4Bg", { bg = "#292d39" })
hi(0, "MarkviewPalette4Fg", { fg = "#e4effa" })
hi(0, "MarkviewPalette4Sign", { fg = "#e4effa" })
hi(0, "MarkviewPalette5", { bg = "#292d39", fg = "#e4effa" })
hi(0, "MarkviewPalette5Bg", { bg = "#292d39" })
hi(0, "MarkviewPalette5Fg", { fg = "#e4effa" })
hi(0, "MarkviewPalette5Sign", { fg = "#e4effa" })
hi(0, "MarkviewPalette6", { bg = "#292d39", fg = "#e4effa" })
hi(0, "MarkviewPalette6Bg", { bg = "#292d39" })
hi(0, "MarkviewPalette6Fg", { fg = "#e4effa" })
hi(0, "MarkviewPalette6Sign", { fg = "#e4effa" })
hi(0, "MarkviewPalette7", { bg = "#252a37", fg = "#91b3d4" })
hi(0, "MarkviewPalette7Bg", { bg = "#252a37" })
hi(0, "MarkviewPalette7Fg", { fg = "#91b3d4" })
hi(0, "MarkviewPalette7Sign", { fg = "#91b3d4" })
hi(0, "MarkviewSubscript", { link = "MarkviewPalette3Fg" })
hi(0, "MarkviewSuperscript", { link = "MarkviewPalette6Fg" })
hi(0, "MarkviewTableAlignCenter", { link = "@markup.heading" })
hi(0, "MarkviewTableAlignLeft", { link = "@markup.heading" })
hi(0, "MarkviewTableAlignRight", { link = "@markup.heading" })
hi(0, "MarkviewTableBorder", { link = "MarkviewPalette5Fg" })
hi(0, "MarkviewTableHeader", { link = "@markup.heading" })
hi(0, "MatchParen", { bg = "#506477", fg = "#171922" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniHipatternsFixme", { bold = true, ctermfg = 9, fg = "#d0679d", reverse = true })
hi(0, "MiniHipatternsHack", { bold = true, ctermfg = 11, fg = "#fffac2", reverse = true })
hi(0, "MiniHipatternsNote", { bold = true, ctermfg = 12, fg = "#89ddff", reverse = true })
hi(0, "MiniHipatternsTodo", { bold = true, ctermfg = 14, fg = "#91b4d5", reverse = true })
hi(0, "ModeMsg", { ctermfg = 10, fg = "#91b4d5" })
hi(0, "ModesCopy", { bg = "#fffac2" })
hi(0, "ModesDelete", { bg = "#d0679d" })
hi(0, "ModesInsert", { bg = "#5de4c7" })
hi(0, "ModesVisual", { bg = "#fffac2" })
hi(0, "MoreMsg", { ctermfg = 14, fg = "#91b4d5" })
hi(0, "NoiceFormatProgressDone", { bg = "#506477", fg = "#ffffff" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#7390aa" })
hi(0, "Normal", { bg = "#1b1e28", fg = "#e4f0fb" })
hi(0, "NormalFloat", { bg = "#171922", fg = "#e4f0fb" })
hi(0, "NormalNC", { bg = "#1b1e28", fg = "#e4f0fb" })
hi(0, "NotifyDEBUGBorder", { fg = "#89ddff" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#d0679d" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#5de4c7" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#89ddff" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#fffac2" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "Number", { fg = "#5de4c7" })
hi(0, "NvimInternalError", { bg = "#d0679d", ctermbg = 9, ctermfg = 9, fg = "#ffffff" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#506477" })
hi(0, "NvimTreeFileDeleted", { fg = "#d0679d" })
hi(0, "NvimTreeFileDirty", { fg = "#7390aa" })
hi(0, "NvimTreeFileMerge", { fg = "#add7ff" })
hi(0, "NvimTreeFileNew", { fg = "#5de4c7" })
hi(0, "NvimTreeFileRenamed", { fg = "#506477" })
hi(0, "NvimTreeFileStaged", { fg = "#89ddff" })
hi(0, "NvimTreeFolderIcon", { fg = "#91b4d5" })
hi(0, "NvimTreeFolderName", { fg = "#91b4d5" })
hi(0, "NvimTreeGitDeleted", { fg = "#d0679d" })
hi(0, "NvimTreeGitDirty", { fg = "#7390aa" })
hi(0, "NvimTreeGitMerge", { fg = "#add7ff" })
hi(0, "NvimTreeGitNew", { fg = "#5de4c7" })
hi(0, "NvimTreeGitRenamed", { fg = "#42675a" })
hi(0, "NvimTreeGitStaged", { fg = "#89ddff" })
hi(0, "NvimTreeImageFile", { fg = "#e4f0fb" })
hi(0, "NvimTreeNormal", { fg = "#e4f0fb" })
hi(0, "NvimTreeOpenedFile", { bg = "#303340", fg = "#e4f0fb" })
hi(0, "NvimTreeOpenedFolderName", { link = "NvimTreeFolderName" })
hi(0, "NvimTreeRootFolder", { fg = "#5de4c7" })
hi(0, "NvimTreeSpecialFile", { link = "NvimTreeNormal" })
hi(0, "NvimTreeWindowPicker", { bg = "#a6accd" })
hi(0, "Operator", { fg = "#add7ff" })
hi(0, "OutlineIndent", { fg = "#add7ff" })
hi(0, "OutlinePreviewBorder", { link = "SagaNormal" })
hi(0, "OutlinePreviewNormal", { link = "SagaBorder" })
hi(0, "Pmenu", { bg = "#171922", fg = "#a6accd" })
hi(0, "PmenuSbar", { bg = "#767c9d" })
hi(0, "PmenuSel", { bg = "#303340", blend = 0, fg = "#e4f0fb" })
hi(0, "PmenuThumb", { bg = "#506477" })
hi(0, "PounceAccept", { bg = "#e4f0fb", fg = "#d0679d" })
hi(0, "PounceAcceptBest", { bg = "#e4f0fb", fg = "#e4f0fb" })
hi(0, "PounceGap", { link = "Search" })
hi(0, "PounceMatch", { link = "Search" })
hi(0, "PreProc", { fg = "#e4f0fb" })
hi(0, "Question", { ctermfg = 14, fg = "#fffac2" })
hi(0, "RedrawDebugClear", { bg = "#fffac2", ctermbg = 11, ctermfg = 0, fg = "#ffffff" })
hi(0, "RedrawDebugComposed", { bg = "#5fb3a1", ctermbg = 10, ctermfg = 0, fg = "#ffffff" })
hi(0, "RedrawDebugRecompose", { bg = "#d0679d", ctermbg = 9, ctermfg = 0, fg = "#ffffff" })
hi(0, "RenameBorder", { link = "SagaBorder" })
hi(0, "RenameMatch", { link = "Search" })
hi(0, "RenameNormal", { fg = "#ffffff" })
hi(0, "Repeat", { fg = "#91b4d5" })
hi(0, "SagaBeacon", { bg = "#fffac2" })
hi(0, "SagaBorder", { bg = "#1b1e28", fg = "#767c9d" })
hi(0, "SagaCollapse", { fg = "#5fb3a1" })
hi(0, "SagaExpand", { fg = "#5fb3a1" })
hi(0, "SagaNormal", { bg = "#1b1e28" })
hi(0, "SagaShadow", { bg = "#171922" })
hi(0, "Search", { bg = "#506477", ctermbg = 11, ctermfg = 0, fg = "#ffffff" })
hi(0, "SignAdd", { link = "GitSignsAdd" })
hi(0, "SignChange", { link = "GitSignsChange" })
hi(0, "SignColumn", { fg = "#e4f0fb" })
hi(0, "SignDelete", { link = "GitSignsDelete" })
hi(0, "SnacksBackdrop", { bg = "#000000" })
hi(0, "SnacksImageMath", { fg = "#767c9d" })
hi(0, "Special", { ctermfg = 14, fg = "#767c9d" })
hi(0, "SpecialComment", { fg = "#a6accd" })
hi(0, "SpecialKey", { fg = "#5de4c7" })
hi(0, "SpellBad", { sp = "#d0679d", undercurl = true })
hi(0, "SpellCap", { sp = "#89ddff", undercurl = true })
hi(0, "SpellLocal", { sp = "#fffac2", undercurl = true })
hi(0, "SpellRare", { sp = "#89ddff", undercurl = true })
hi(0, "Statement", { fg = "#e4f0fb" })
hi(0, "StatusLine", { bg = "#171922", fg = "#91b4d5" })
hi(0, "StatusLineNC", { bg = "#1b1e28", fg = "#91b4d5" })
hi(0, "String", { ctermfg = 10, fg = "#5de4c7" })
hi(0, "TSInclude", { fg = "#add7ff" })
hi(0, "TSURI", { fg = "#91b4d5" })
hi(0, "TabLine", { bg = "#171922", fg = "#91b4d5" })
hi(0, "TabLineFill", { bg = "#171922" })
hi(0, "TabLineSel", { bg = "#303340", fg = "#e4f0fb" })
hi(0, "Tag", { fg = "#e4f0fb" })
hi(0, "TelescopeBorder", { fg = "#303340" })
hi(0, "TelescopeMatching", { fg = "#5de4c7" })
hi(0, "TelescopeNormal", { fg = "#e4f0fb" })
hi(0, "TelescopePreviewTitle", { bg = "#5de4c7", fg = "#1b1e28" })
hi(0, "TelescopePromptBorder", { fg = "#303340" })
hi(0, "TelescopePromptNormal", { fg = "#e4f0fb" })
hi(0, "TelescopePromptPrefix", { fg = "#767c9d" })
hi(0, "TelescopePromptTitle", { bg = "#89ddff", fg = "#1b1e28" })
hi(0, "TelescopeResultsDiffAdd", { fg = "#5de4c7" })
hi(0, "TelescopeResultsDiffChange", { fg = "#fffac2" })
hi(0, "TelescopeResultsDiffDelete", { fg = "#d0679d" })
hi(0, "TelescopeSelection", { bg = "#303340", fg = "#e4f0fb" })
hi(0, "TelescopeTitle", { fg = "#767c9d" })
hi(0, "TerminalBorder", { link = "SagaBorder" })
hi(0, "TerminalNormal", { link = "SagaNormal" })
hi(0, "Title", { fg = "#e4f0fb" })
hi(0, "TitleIcon", { fg = "#add7ff" })
hi(0, "TitleString", { fg = "#add7ff" })
hi(0, "Todo", { bg = "#fffac2", fg = "#171922" })
hi(0, "Type", { fg = "#a6accd" })
hi(0, "VertSplit", { fg = "#171922" })
hi(0, "Visual", { bg = "#506477", ctermbg = 15, ctermfg = 0, fg = "#e4f0fb" })
hi(0, "WarningMsg", { ctermfg = 11, fg = "#fffac2" })
hi(0, "WhichKey", { fg = "#e4f0fb" })
hi(0, "WhichKeyDesc", { fg = "#e4f0fb" })
hi(0, "WhichKeyFloat", { bg = "#171922" })
hi(0, "WhichKeyGroup", { fg = "#e4f0fb" })
hi(0, "WhichKeyIconAzure", { link = "MiniIconsAzure" })
hi(0, "WhichKeyIconBlue", { link = "MiniIconsBlue" })
hi(0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
hi(0, "WhichKeyIconGreen", { link = "MiniIconsGreen" })
hi(0, "WhichKeyIconGrey", { link = "MiniIconsGrey" })
hi(0, "WhichKeyIconOrange", { link = "MiniIconsOrange" })
hi(0, "WhichKeyIconPurple", { link = "MiniIconsPurple" })
hi(0, "WhichKeyIconRed", { link = "MiniIconsRed" })
hi(0, "WhichKeyIconYellow", { link = "MiniIconsYellow" })
hi(0, "WhichKeySeparator", { fg = "#e4f0fb" })
hi(0, "WhichKeyValue", { fg = "#e4f0fb" })
hi(0, "Whitespace", { fg = "#506477" })
hi(0, "WildMenu", { link = "IncSearch" })
hi(0, "bg_.bg1_fg_.bg1_", { bg = "#31353f", fg = "#31353f" })
hi(0, "bg_.bg1_fg_91b4d5_", { bg = "#31353f", fg = "#91b4d5" })
hi(0, "bg_.bg2_fg_.bg2_", { bg = "#474c56", fg = "#474c56" })
hi(0, "bg_.bg2_fg_.blue_", { bg = "#474c56", fg = "#add7ff" })
hi(0, "bg_.bg2_fg_91b4d5_", { bg = "#474c56", fg = "#91b4d5" })
hi(0, "bg_171922_fg_171922_", { bg = "#171922", fg = "#171922" })
hi(0, "bg_171922_fg_91b4d5_", { bg = "#171922", fg = "#91b4d5" })
hi(0, "bg_171922_fg_a6dbff_", { bg = "#171922", fg = "#a6dbff" })
hi(0, "bg_171922_fg_yellow_", { bg = "#171922", fg = "#fffac2" })
hi(0, "bg_blue_fg_bg1_", { bg = "#add7ff", fg = "#31353f" })
hi(0, "bg_blue_fg_blue_", { bg = "#add7ff", fg = "#add7ff" })
hi(0, "bg_cyan_fg_bg1_", { bg = "#add7ff", fg = "#31353f" })
hi(0, "bg_cyan_fg_cyan_", { bg = "#add7ff", fg = "#add7ff" })
hi(0, "bg_magenta_fg_bg1_", { bg = "#fcc5e9", fg = "#31353f" })
hi(0, "bg_magenta_fg_magenta_", { bg = "#fcc5e9", fg = "#fcc5e9" })
hi(0, "cssClassName", { fg = "#5fb3a1", italic = true })
hi(0, "cssDefinition", { fg = "#add7ff" })
hi(0, "cssPseudoClass", { fg = "#91b4d5", italic = true })
hi(0, "cssTSError", { link = "cssClassName" })
hi(0, "cssTSFunction", { fg = "#a6accd" })
hi(0, "cssTSKeyword", { fg = "#a6accd" })
hi(0, "cssTSProperty", { fg = "#add7ff" })
hi(0, "cssTSType", { fg = "#5de4c7" })
hi(0, "debugBreakpoint", { bg = "#1b1e28", fg = "#d0679d" })
hi(0, "debugPC", { bg = "#303340" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "field", { fg = "#e4f0fb" })
hi(0, "fzf1", { bg = "#565656", ctermbg = 8, ctermfg = 1, fg = "#e12672" })
hi(0, "fzf2", { bg = "#565656", ctermbg = 8, ctermfg = 2, fg = "#bcddbd" })
hi(0, "fzf3", { bg = "#565656", ctermbg = 8, ctermfg = 7, fg = "#d9d9d9" })
hi(0, "htmlH1", { bold = true, fg = "#5de4c7" })
hi(0, "htmlH2", { bold = true, fg = "#5de4c7" })
hi(0, "incline__gui_bold", { bold = true })
hi(0, "incline__guibg_353b4c", { bg = "#353b4c" })
hi(0, "incline__guibg_add7ff__guifg_000000", { bg = "#add7ff", fg = "#000000" })
hi(0, "lCursor", { bg = "#e4f0fb", fg = "#1b1e28" })
hi(0, "luaTSConstructor", { fg = "#a6accd" })
hi(0, "markdownCode", { fg = "#a6accd" })
hi(0, "markdownCodeBlock", { fg = "#5fb3a1" })
hi(0, "markdownH1", { link = "@markup.heading.1" })
hi(0, "markdownH2", { link = "@markup.heading.2" })
hi(0, "markdownH3", { link = "@markup.heading.3" })
hi(0, "markdownH4", { link = "@markup.heading.4" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#7390aa" })
hi(0, "markdownLinkText", { fg = "#89ddff", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#171922", fg = "#e4f0fb" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#5fb3a1" })
hi(0, "mkdCodeStart", { bold = true, fg = "#5fb3a1" })
hi(0, "mkdLink", { fg = "#89ddff", underline = true })
hi(0, "qfFileName", { fg = "#767c9d" })
hi(0, "qfLineNr", { fg = "#506477" })
hi(0, "rainbowcol1", { fg = "#89ddff" })
hi(0, "rainbowcol2", { fg = "#5de4c7" })
hi(0, "rainbowcol3", { fg = "#fffac2" })
hi(0, "rainbowcol4", { fg = "#add7ff" })
hi(0, "rainbowcol5", { fg = "#5fb3a1" })
hi(0, "rainbowcol6", { fg = "#d0679d" })
hi(0, "rainbowcol7", { fg = "#91b4d5" })
hi(0, "typescriptBlock", { fg = "#e4f0fb" })
hi(0, "typescriptCastKeyword", { fg = "#767c9d" })
hi(0, "typescriptConstraint", { fg = "#5de4c7" })
hi(0, "typescriptDefault", { fg = "#5de4c7" })
hi(0, "typescriptEnum", { fg = "#7390aa" })
hi(0, "typescriptExport", { fg = "#5de4c7" })
hi(0, "typescriptIdentifierName", { fg = "#767c9d" })
hi(0, "typescriptObjectType", { fg = "#a6accd" })
hi(0, "typescriptParenExp", { fg = "#767c9d" })
hi(0, "typescriptTSInclude", { fg = "#5de4c7" })
hi(0, "typescriptTypeCast", { fg = "#767c9d" })
hi(0, "typescriptVariable", { fg = "#add7ff" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#171922"
g.terminal_color_1 = "#d0679d"
g.terminal_color_2 = "#5de4c7"
g.terminal_color_3 = "#fffac2"
g.terminal_color_4 = "#89ddff"
g.terminal_color_5 = "#fcc5e9"
g.terminal_color_6 = "#89ddff"
g.terminal_color_7 = "#ffffff"
g.terminal_color_8 = "#171922"
g.terminal_color_9 = "#d0679d"
g.terminal_color_10 = "#5de4c7"
g.terminal_color_11 = "#fffac2"
g.terminal_color_12 = "#add7ff"
g.terminal_color_13 = "#fcc5e9"
g.terminal_color_14 = "#add7ff"
g.terminal_color_15 = "#ffffff"
