-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "randomhue2"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@keyword.return", { bold = true, fg = "#efba93" })
hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
hi(0, "@lsp.mod.deprecated", { fg = "#f6b2b8" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.comment", { link = "Comment" })
hi(0, "@lsp.type.decorator", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@lsp.type" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.struct", { link = "@structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", {})
hi(0, "@method.call", { link = "Function" })
hi(0, "@parameter", { fg = "#bfc1fa" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@structure", { link = "Structure" })
hi(0, "@symbol", { link = "Keyword" })
hi(0, "@text.danger", { link = "ErrorMsg" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { link = "Comment" })
hi(0, "@text.note", { link = "MoreMsg" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@variable", { fg = "#c8c5cc" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "Beacon", { bg = "#eeebf2" })
hi(0, "Bold", { bold = true })
hi(0, "BufferCurrent", { bg = "#261f2e", bold = true, fg = "#d3baf1" })
hi(0, "BufferCurrentIcon", { bg = "#261f2e" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#3f3848", bold = true, fg = "#d3baf1" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#5a5264", bold = true, fg = "#d3baf1" })
hi(0, "BufferInactive", { bg = "#1a1321", fg = "#c8c5cc" })
hi(0, "BufferInactiveIcon", { bg = "#1a1321" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#3f3848", fg = "#c8c5cc" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#5a5264", fg = "#c8c5cc" })
hi(0, "BufferLineBuffer", { fg = "#8e8b91" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#c8c5cc" })
hi(0, "BufferLineBufferVisible", { fg = "#c8c5cc" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#a4d6aa", fg = "#261f2e" })
hi(0, "BufferLineTabSelected", { bg = "#a4d6aa", bold = true, fg = "#261f2e" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#a4d6aa", bold = true, fg = "#261f2e" })
hi(0, "BufferVisible", { bg = "#261f2e", bold = true, fg = "#c8c5cc" })
hi(0, "BufferVisibleIcon", { bg = "#261f2e" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#3f3848", bold = true, fg = "#c8c5cc" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#5a5264", bold = true, fg = "#c8c5cc" })
hi(0, "CmpItemAbbr", { fg = "#c8c5cc" })
hi(0, "CmpItemAbbrDefault", { fg = "#c8c5cc" })
hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#8e8b91" })
hi(0, "CmpItemAbbrMatch", { bold = true })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c8c5cc" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c8c5cc" })
hi(0, "CmpItemKind", { fg = "#c8c5cc" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#86d8d5" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "Normal" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#c8c5cc" })
hi(0, "CmpItemMenuDefault", { fg = "#c8c5cc" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocErrorFloat", { link = "DiagnosticFloatingError" })
hi(0, "CocErrorHighlight", { link = "DiagnosticError" })
hi(0, "CocErrorSign", { link = "DiagnosticSignError" })
hi(0, "CocHintFloat", { link = "DiagnosticFloatingHint" })
hi(0, "CocHintHighlight", { link = "DiagnosticHint" })
hi(0, "CocHintSign", { link = "DiagnosticSignHint" })
hi(0, "CocInfoFloat", { link = "DiagnosticFloatingInfo" })
hi(0, "CocInfoHighlight", { link = "DiagnosticInfo" })
hi(0, "CocInfoSign", { link = "DiagnosticSignInfo" })
hi(0, "CocMarkdownLink", { fg = "#bfc1fa" })
hi(0, "CocMenuSel", { bg = "#5a5264" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#bfc1fa" })
hi(0, "CocSelectedText", { fg = "#d0c98c" })
hi(0, "CocWarningFloat", { link = "DiagnosticFloatingWarn" })
hi(0, "CocWarningHighlight", { link = "DiagnosticWarn" })
hi(0, "CocWarningSign", { link = "DiagnosticSignWarn" })
hi(0, "ColorColumn", { bg = "#5a5264" })
hi(0, "Comment", { fg = "#8e8b91" })
hi(0, "Conceal", { fg = "#95cff5" })
hi(0, "Constant", { fg = "#e4b5e1" })
hi(0, "CurSearch", { bg = "#d0c98c", fg = "#261f2e" })
hi(0, "Cursor", { bg = "#c8c5cc", fg = "#261f2e" })
hi(0, "CursorColumn", { bg = "#3f3848" })
hi(0, "CursorIM", { link = "Cursor" })
hi(0, "CursorLine", { bg = "#3f3848" })
hi(0, "CursorLineFold", { fg = "#5a5264" })
hi(0, "CursorLineNr", { bold = true, fg = "#d3baf1" })
hi(0, "CursorLineSign", { fg = "#5a5264" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#a4d6aa" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#efba93" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Comment" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortcut", { link = "WarningMsg" })
hi(0, "Definitions", { fg = "#a4d6aa" })
hi(0, "DefinitionsIcon", { fg = "#95cff5" })
hi(0, "Delimiter", { fg = "#efba93" })
hi(0, "DiagnosticDeprecated", { sp = "#f6b2b8", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#f6b2b8" })
hi(0, "DiagnosticFloatingError", { bg = "#1a1321", fg = "#f6b2b8" })
hi(0, "DiagnosticFloatingHint", { bg = "#1a1321", fg = "#86d8d5" })
hi(0, "DiagnosticFloatingInfo", { bg = "#1a1321", fg = "#bfc1fa" })
hi(0, "DiagnosticFloatingOk", { bg = "#1a1321", fg = "#a4d6aa" })
hi(0, "DiagnosticFloatingWarn", { bg = "#1a1321", fg = "#d0c98c" })
hi(0, "DiagnosticHint", { fg = "#86d8d5" })
hi(0, "DiagnosticInfo", { fg = "#bfc1fa" })
hi(0, "DiagnosticOk", { fg = "#a4d6aa" })
hi(0, "DiagnosticUnderlineError", { sp = "#f6b2b8", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#86d8d5", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#bfc1fa", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#a4d6aa", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#d0c98c", underline = true })
hi(0, "DiagnosticWarn", { fg = "#d0c98c" })
hi(0, "DiffAdd", { bg = "#00300e" })
hi(0, "DiffChange", { bg = "#3d3700" })
hi(0, "DiffDelete", { bg = "#410d17" })
hi(0, "DiffFile", { bg = "#3d3700" })
hi(0, "DiffLine", { bg = "#1f1b47" })
hi(0, "DiffNewFile", { link = "diffAdded" })
hi(0, "DiffText", { bg = "#5a5264" })
hi(0, "Directory", { fg = "#95cff5" })
hi(0, "EndOfBuffer", { fg = "#5a5264" })
hi(0, "Error", { bg = "#410d17" })
hi(0, "ErrorMsg", { fg = "#f6b2b8" })
hi(0, "FinderParam", { fg = "#d0c98c" })
hi(0, "FinderSpinner", { fg = "#a4d6aa" })
hi(0, "FinderSpinnerBorder", { fg = "#d3baf1" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#efba93" })
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { bg = "#1a1321", fg = "#d3baf1" })
hi(0, "FloatTitle", { bg = "#1a1321", bold = true, fg = "#d3baf1" })
hi(0, "FoldColumn", { fg = "#5a5264" })
hi(0, "Folded", { bg = "#3f3848", fg = "#8e8b91" })
hi(0, "Function", { fg = "#95cff5" })
hi(0, "GitSignsAdd", { fg = "#a4d6aa" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLnInline", { fg = "#a4d6aa" })
hi(0, "GitSignsAddNr", { fg = "#a4d6aa" })
hi(0, "GitSignsAddPreview", { bg = "#00300e" })
hi(0, "GitSignsChange", { fg = "#d0c98c" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLnInline", { fg = "#d0c98c" })
hi(0, "GitSignsChangeNr", { fg = "#d0c98c" })
hi(0, "GitSignsChangedelete", { fg = "#d0c98c" })
hi(0, "GitSignsChangedeleteLn", { fg = "#d0c98c" })
hi(0, "GitSignsChangedeleteNr", { fg = "#d0c98c" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#5a5264" })
hi(0, "GitSignsDelete", { fg = "#f6b2b8" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLnInline", { fg = "#f6b2b8" })
hi(0, "GitSignsDeleteNr", { fg = "#f6b2b8" })
hi(0, "GitSignsDeletePreview", { bg = "#410d17" })
hi(0, "GitSignsDeleteVirtLn", { bg = "#410d17" })
hi(0, "GitSignsDeleteVirtLnInLine", { fg = "#f6b2b8" })
hi(0, "GitSignsStagedAdd", { fg = "#526b55" })
hi(0, "GitSignsStagedAddLn", { fg = "#526b55" })
hi(0, "GitSignsStagedAddNr", { fg = "#526b55" })
hi(0, "GitSignsStagedChange", { fg = "#686446" })
hi(0, "GitSignsStagedChangeLn", { fg = "#686446" })
hi(0, "GitSignsStagedChangeNr", { fg = "#686446" })
hi(0, "GitSignsStagedChangedelete", { fg = "#686446" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#686446" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#686446" })
hi(0, "GitSignsStagedDelete", { fg = "#7b595c" })
hi(0, "GitSignsStagedDeleteLn", { fg = "#7b595c" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7b595c" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7b595c" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7b595c" })
hi(0, "GitSignsTopdelete", { fg = "#f6b2b8" })
hi(0, "GitSignsTopdeleteNr", { fg = "#f6b2b8" })
hi(0, "GitSignsUntracked", { fg = "#95cff5" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedNr", { fg = "#a4d6aa" })
hi(0, "GitSignsVirtLnum", { bg = "#410d17" })
hi(0, "HopNextKey", { bold = true, fg = "#a4d6aa", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#efba93", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#aba8af", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#d0c98c", nocombine = true })
hi(0, "HopUnmatched", { fg = "#5a5264" })
hi(0, "HydraAmaranth", { fg = "#e4b5e1" })
hi(0, "HydraBlue", { fg = "#95cff5" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#efba93" })
hi(0, "HydraRed", { fg = "#f6b2b8" })
hi(0, "HydraTeal", { fg = "#86d8d5" })
hi(0, "Identifier", { fg = "#d0c98c" })
hi(0, "Ignore", {})
hi(0, "IncSearch", { bg = "#d0c98c", fg = "#261f2e" })
hi(0, "IndentBlanklineChar", { fg = "#5a5264", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#d3baf1", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#d3baf1", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#bfc1fa", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#86d8d5", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#d0c98c", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#f6b2b8", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#95cff5", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#a4d6aa", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#efba93", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#e4b5e1", nocombine = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#5a5264", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#5a5264", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "LSOutlinePreviewBorder", { fg = "#d3baf1" })
hi(0, "LazyButton", { bg = "#3f3848" })
hi(0, "LazyButtonActive", { bg = "#5a5264" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#5a5264", bold = true, fg = "#d3baf1" })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabelPrimary", { bold = true, fg = "#d0c98c", nocombine = true })
hi(0, "LeapLabelSecondary", { bold = true, fg = "#c8c5cc", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#86d8d5", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#a4d6aa", nocombine = true })
hi(0, "LineNr", { fg = "#5a5264" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspInfoBorder", { bold = true })
hi(0, "LspInfoFiletype", { fg = "#c8c5cc" })
hi(0, "LspInfoList", { fg = "#95cff5" })
hi(0, "LspInfoTip", { fg = "#8e8b91" })
hi(0, "LspInfoTitle", { fg = "#d3baf1" })
hi(0, "LspReferenceRead", { link = "LspReferenceText" })
hi(0, "LspReferenceText", { bg = "#5a5264" })
hi(0, "LspReferenceWrite", { link = "LspReferenceText" })
hi(0, "LspSagaAutoPreview", { fg = "#bfc1fa" })
hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
hi(0, "LspSagaCodeActionBorder", { fg = "#d3baf1" })
hi(0, "LspSagaCodeActionContent", { fg = "#c8c5cc" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#95cff5" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#d3baf1" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#d3baf1" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#efba93" })
hi(0, "LspSagaFinderSelection", { fg = "#86d8d5" })
hi(0, "LspSagaHoverBorder", { fg = "#d3baf1" })
hi(0, "LspSagaLspFinderBorder", { fg = "#d3baf1" })
hi(0, "LspSagaRenameBorder", { fg = "#d3baf1" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#d3baf1" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "MasonError", { fg = "#f6b2b8" })
hi(0, "MasonHeader", { bg = "#95cff5", bold = true, fg = "#261f2e" })
hi(0, "MasonHeaderSecondary", { bg = "#bfc1fa", bold = true, fg = "#261f2e" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#d3baf1" })
hi(0, "MasonHighlightBlock", { bg = "#d3baf1", fg = "#261f2e" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#95cff5", fg = "#261f2e" })
hi(0, "MasonHighlightSecondary", { fg = "#95cff5" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#5a5264", fg = "#261f2e" })
hi(0, "MasonMutedBlockBold", { bg = "#5a5264", bold = true, fg = "#261f2e" })
hi(0, "MatchParen", { bg = "#5a5264", bold = true })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { bg = "#5a5264" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniFilesFile", { fg = "#c8c5cc" })
hi(0, "MiniFilesTitleFocused", { bg = "#1a1321", bold = true, fg = "#c8c5cc" })
hi(0, "MiniHipatternsFixme", { bg = "#f6b2b8", bold = true, fg = "#261f2e" })
hi(0, "MiniHipatternsHack", { bg = "#d0c98c", bold = true, fg = "#261f2e" })
hi(0, "MiniHipatternsNote", { bg = "#86d8d5", bold = true, fg = "#261f2e" })
hi(0, "MiniHipatternsTodo", { bg = "#bfc1fa", bold = true, fg = "#261f2e" })
hi(0, "MiniIndentscopeSymbol", { fg = "#d3baf1" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#f6b2b8" })
hi(0, "MiniJump", { sp = "#d3baf1", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#5a5264" })
hi(0, "MiniJump2dSpot", { bg = "#0b0612", bold = true, fg = "#eeebf2", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#0b0612", fg = "#dad7de", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#1a1321", fg = "#8e8b91" })
hi(0, "MiniMapSymbolCount", { fg = "#8e8b91" })
hi(0, "MiniMapSymbolLine", { fg = "#d3baf1" })
hi(0, "MiniMapSymbolView", { fg = "#d3baf1" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniStarterCurrent", { link = "MiniStarterItem" })
hi(0, "MiniStarterFooter", { link = "Comment" })
hi(0, "MiniStarterHeader", { bold = true, fg = "#d3baf1" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItemBullet", { fg = "#8e8b91" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#d0c98c" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#a4d6aa" })
hi(0, "MiniStarterSection", { fg = "#e4b5e1" })
hi(0, "MiniStatuslineDevinfo", { bg = "#3f3848", fg = "#aba8af" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#261f2e", fg = "#aba8af" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { bg = "#d0c98c", bold = true, fg = "#261f2e" })
hi(0, "MiniStatuslineModeInsert", { bg = "#95cff5", bold = true, fg = "#261f2e" })
hi(0, "MiniStatuslineModeNormal", { bg = "#c8c5cc", bold = true, fg = "#261f2e" })
hi(0, "MiniStatuslineModeOther", { bg = "#86d8d5", bold = true, fg = "#261f2e" })
hi(0, "MiniStatuslineModeReplace", { bg = "#f6b2b8", bold = true, fg = "#261f2e" })
hi(0, "MiniStatuslineModeVisual", { bg = "#a4d6aa", bold = true, fg = "#261f2e" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#261f2e", bold = true, fg = "#d3baf1" })
hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
hi(0, "MiniTablineHidden", { bg = "#1a1321", fg = "#aba8af" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#d3baf1", bold = true, fg = "#261f2e" })
hi(0, "MiniTablineModifiedHidden", { bg = "#aba8af", fg = "#1a1321" })
hi(0, "MiniTablineModifiedVisible", { bg = "#aba8af", bold = true, fg = "#1a1321" })
hi(0, "MiniTablineTabpagesection", { bg = "#a4d6aa", bold = true, fg = "#261f2e" })
hi(0, "MiniTablineVisible", { bg = "#1a1321", bold = true, fg = "#aba8af" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#f6b2b8" })
hi(0, "MiniTestPass", { bold = true, fg = "#a4d6aa" })
hi(0, "MiniTrailspace", { bg = "#410d17" })
hi(0, "ModeMsg", { fg = "#a4d6aa" })
hi(0, "MoreMsg", { fg = "#95cff5" })
hi(0, "MsgArea", { link = "Normal" })
hi(0, "MsgSeparator", { bg = "#5a5264", fg = "#8e8b91" })
hi(0, "NeoTreeDimText", { fg = "#5a5264" })
hi(0, "NeoTreeDotfile", { fg = "#aba8af" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#5a5264" })
hi(0, "NeoTreeGitAdded", { fg = "#a4d6aa" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#efba93" })
hi(0, "NeoTreeGitDeleted", { fg = "#f6b2b8" })
hi(0, "NeoTreeGitModified", { fg = "#d0c98c" })
hi(0, "NeoTreeGitUnstaged", { fg = "#e4b5e1" })
hi(0, "NeoTreeGitUntracked", { fg = "#86d8d5" })
hi(0, "NeoTreeMessage", { bg = "#3f3848", fg = "#c8c5cc" })
hi(0, "NeoTreeModified", { fg = "#dad7de" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#d3baf1" })
hi(0, "NeoTreeTabInactive", { fg = "#8e8b91" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#5a5264", fg = "#8e8b91" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#3f3848", fg = "#3f3848" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#d3baf1" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#d3baf1" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceAttr344", { fg = "#f6b2b8" })
hi(0, "NoiceCmdline", { bg = "#261f2e", fg = "#c8c5cc" })
hi(0, "NoiceCmdlineIcon", { fg = "#bfc1fa" })
hi(0, "NoiceCmdlineIconCalculator", { fg = "#bfc1fa" })
hi(0, "NoiceCmdlineIconCmdline", { fg = "#bfc1fa" })
hi(0, "NoiceCmdlineIconFilter", { fg = "#bfc1fa" })
hi(0, "NoiceCmdlineIconHelp", { fg = "#bfc1fa" })
hi(0, "NoiceCmdlineIconInput", { fg = "#bfc1fa" })
hi(0, "NoiceCmdlineIconLua", { fg = "#bfc1fa" })
hi(0, "NoiceCmdlineIconSearch", { fg = "#d0c98c" })
hi(0, "NoiceCmdlinePopup", { bg = "#261f2e", fg = "#c8c5cc" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#95cff5" })
hi(0, "NoiceCmdlinePopupBorderCalculator", { fg = "#95cff5" })
hi(0, "NoiceCmdlinePopupBorderCmdline", { fg = "#95cff5" })
hi(0, "NoiceCmdlinePopupBorderFilter", { fg = "#95cff5" })
hi(0, "NoiceCmdlinePopupBorderHelp", { fg = "#95cff5" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#95cff5" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#95cff5" })
hi(0, "NoiceCmdlinePopupBorderSearch", { fg = "#d0c98c" })
hi(0, "NoiceCmdlinePopupTitle", { fg = "#bfc1fa" })
hi(0, "NoiceCmdlinePrompt", { fg = "#d3baf1" })
hi(0, "NoiceCompletionItemKindClass", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindColor", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindConstant", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindConstructor", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindEnum", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindEnumMember", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindField", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindFile", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindFolder", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindFunction", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindInterface", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindKeyword", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindMethod", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindModule", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindProperty", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindSnippet", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindStruct", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindText", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindUnit", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindValue", { fg = "#86d8d5" })
hi(0, "NoiceCompletionItemKindVariable", { fg = "#86d8d5" })
hi(0, "NoiceConfirm", { bg = "#261f2e", fg = "#c8c5cc" })
hi(0, "NoiceConfirmBorder", { fg = "#d0c98c" })
hi(0, "NoiceCursor", { bg = "#c8c5cc", fg = "#261f2e" })
hi(0, "NoiceFormatConfirm", { bg = "#3f3848" })
hi(0, "NoiceFormatConfirmDefault", { bg = "#5a5264" })
hi(0, "NoiceFormatDate", { fg = "#86d8d5" })
hi(0, "NoiceFormatEvent", { fg = "#5a5264" })
hi(0, "NoiceFormatKind", { fg = "#5a5264" })
hi(0, "NoiceFormatLevelDebug", { fg = "#5a5264" })
hi(0, "NoiceFormatLevelError", { fg = "#f6b2b8" })
hi(0, "NoiceFormatLevelInfo", { fg = "#bfc1fa" })
hi(0, "NoiceFormatLevelOff", { fg = "#5a5264" })
hi(0, "NoiceFormatLevelTrace", { fg = "#5a5264" })
hi(0, "NoiceFormatLevelWarn", { fg = "#d0c98c" })
hi(0, "NoiceFormatProgressDone", { bg = "#d3baf1", fg = "#261f2e" })
hi(0, "NoiceFormatProgressTodo", { bg = "#3f3848" })
hi(0, "NoiceFormatTitle", { fg = "#d3baf1" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NoiceLspProgressClient", { fg = "#d3baf1" })
hi(0, "NoiceLspProgressSpinner", { fg = "#e4b5e1" })
hi(0, "NoiceLspProgressTitle", { fg = "#5a5264" })
hi(0, "NoiceMini", { bg = "#261f2e", fg = "#c8c5cc" })
hi(0, "NoicePopup", { bg = "#1a1321", fg = "#c8c5cc" })
hi(0, "NoicePopupBorder", { bg = "#1a1321", fg = "#d3baf1" })
hi(0, "NoicePopupmenu", { bg = "#3f3848", fg = "#c8c5cc" })
hi(0, "NoicePopupmenuBorder", { bg = "#1a1321", fg = "#d3baf1" })
hi(0, "NoicePopupmenuMatch", { fg = "#86d8d5" })
hi(0, "NoicePopupmenuSelected", { bg = "#c8c5cc", blend = 0, fg = "#261f2e" })
hi(0, "NoiceScrollbar", { bg = "#3f3848", fg = "#c8c5cc" })
hi(0, "NoiceScrollbarThumb", { bg = "#5a5264" })
hi(0, "NoiceSplit", { bg = "#1a1321", fg = "#c8c5cc" })
hi(0, "NoiceSplitBorder", { bg = "#1a1321", fg = "#d3baf1" })
hi(0, "NoiceVirtualText", { fg = "#bfc1fa" })
hi(0, "NonText", { fg = "#5a5264" })
hi(0, "Normal", { bg = "#261f2e", fg = "#c8c5cc" })
hi(0, "NormalFloat", { bg = "#1a1321", fg = "#c8c5cc" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#a4d6aa" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBody240", { bg = "#261f2e", fg = "#2c2634" })
hi(0, "NotifyERRORBody322", { bg = "#261f2e", fg = "#2c2634" })
hi(0, "NotifyERRORBorder", { fg = "#f6b2b8" })
hi(0, "NotifyERRORBorder240", { fg = "#2e2533" })
hi(0, "NotifyERRORBorder322", { fg = "#2e2533" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORIcon240", { fg = "#2e2533" })
hi(0, "NotifyERRORIcon322", { fg = "#2e2533" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle240", { fg = "#2e2533" })
hi(0, "NotifyERRORTitle322", { fg = "#2e2533" })
hi(0, "NotifyINFOBody257", { bg = "#261f2e", fg = "#2c2634" })
hi(0, "NotifyINFOBody261", { bg = "#261f2e", fg = "#2c2634" })
hi(0, "NotifyINFOBorder", { fg = "#bfc1fa" })
hi(0, "NotifyINFOBorder257", { fg = "#2c2536" })
hi(0, "NotifyINFOBorder261", { fg = "#2c2536" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOIcon257", { fg = "#2c2536" })
hi(0, "NotifyINFOIcon261", { fg = "#2c2536" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle257", { fg = "#2c2536" })
hi(0, "NotifyINFOTitle261", { fg = "#2c2536" })
hi(0, "NotifyTRACEBorder", { fg = "#86d8d5" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBody268", { bg = "#261f2e", fg = "#2c2634" })
hi(0, "NotifyWARNBorder", { fg = "#d0c98c" })
hi(0, "NotifyWARNBorder268", { fg = "#2d2632" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNIcon268", { fg = "#2d2632" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle268", { fg = "#2d2632" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#a4d6aa" })
hi(0, "NvimTreeFolderIcon", { fg = "#8e8b91" })
hi(0, "NvimTreeGitDeleted", { fg = "#f6b2b8" })
hi(0, "NvimTreeGitDirty", { fg = "#d0c98c" })
hi(0, "NvimTreeGitMerge", { fg = "#efba93" })
hi(0, "NvimTreeGitNew", { fg = "#86d8d5" })
hi(0, "NvimTreeGitRenamed", { fg = "#e4b5e1" })
hi(0, "NvimTreeGitStaged", { fg = "#a4d6aa" })
hi(0, "NvimTreeImageFile", { fg = "#efba93" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#d3baf1" })
hi(0, "NvimTreeSpecialFile", { fg = "#d3baf1", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#bfc1fa" })
hi(0, "NvimTreeWindowPicker", { bg = "#5a5264", bold = true, fg = "#c8c5cc" })
hi(0, "Operator", { fg = "#c8c5cc" })
hi(0, "OutlineDetail", { fg = "#5a5264" })
hi(0, "OutlineFoldPrefix", { fg = "#d0c98c" })
hi(0, "OutlineIndentEvn", { fg = "#8e8b91" })
hi(0, "OutlineIndentOdd", { fg = "#c8c5cc" })
hi(0, "Pmenu", { bg = "#3f3848", fg = "#c8c5cc" })
hi(0, "PmenuSbar", { link = "Pmenu" })
hi(0, "PmenuSel", { bg = "#c8c5cc", blend = 0, fg = "#261f2e" })
hi(0, "PmenuThumb", { bg = "#5a5264" })
hi(0, "PounceAccept", { bg = "#d0c98c", bold = true, fg = "#261f2e", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#a4d6aa", bold = true, fg = "#261f2e", nocombine = true })
hi(0, "PounceGap", { bg = "#5a5264", bold = true, fg = "#261f2e", nocombine = true })
hi(0, "PounceMatch", { bg = "#c8c5cc", bold = true, fg = "#261f2e", nocombine = true })
hi(0, "PreProc", { fg = "#bfc1fa" })
hi(0, "Question", { fg = "#95cff5" })
hi(0, "QuickFixLine", { bg = "#3f3848" })
hi(0, "RainbowDelimiterBlue", { fg = "#95cff5" })
hi(0, "RainbowDelimiterCyan", { fg = "#86d8d5" })
hi(0, "RainbowDelimiterGreen", { fg = "#a4d6aa" })
hi(0, "RainbowDelimiterOrange", { fg = "#efba93" })
hi(0, "RainbowDelimiterRed", { fg = "#f6b2b8" })
hi(0, "RainbowDelimiterViolet", { fg = "#e4b5e1" })
hi(0, "RainbowDelimiterYellow", { fg = "#d0c98c" })
hi(0, "References", { fg = "#a4d6aa" })
hi(0, "ReferencesIcon", { fg = "#95cff5" })
hi(0, "Search", { bg = "#d3baf1", fg = "#261f2e" })
hi(0, "SignColumn", { fg = "#5a5264" })
hi(0, "Sneak", { bg = "#efba93", fg = "#261f2e" })
hi(0, "SneakLabel", { bg = "#efba93", bold = true, fg = "#261f2e" })
hi(0, "SneakScope", { bg = "#eeebf2", fg = "#261f2e" })
hi(0, "Special", { fg = "#86d8d5" })
hi(0, "SpecialKey", { fg = "#5a5264" })
hi(0, "SpellBad", { sp = "#f6b2b8", undercurl = true })
hi(0, "SpellCap", { sp = "#86d8d5", undercurl = true })
hi(0, "SpellLocal", { sp = "#d0c98c", undercurl = true })
hi(0, "SpellRare", { sp = "#bfc1fa", undercurl = true })
hi(0, "Statement", { bold = true })
hi(0, "StatusLine", { bg = "#261f2e", fg = "#aba8af" })
hi(0, "StatusLineNC", { bg = "#1a1321", fg = "#aba8af" })
hi(0, "String", { fg = "#a4d6aa" })
hi(0, "Substitute", { bg = "#bfc1fa", fg = "#261f2e" })
hi(0, "TSRainbowBlue", { fg = "#95cff5" })
hi(0, "TSRainbowCyan", { fg = "#86d8d5" })
hi(0, "TSRainbowGreen", { fg = "#a4d6aa" })
hi(0, "TSRainbowOrange", { fg = "#efba93" })
hi(0, "TSRainbowRed", { fg = "#f6b2b8" })
hi(0, "TSRainbowViolet", { fg = "#e4b5e1" })
hi(0, "TSRainbowYellow", { fg = "#d0c98c" })
hi(0, "TabLine", { bg = "#1a1321", fg = "#aba8af" })
hi(0, "TabLineFill", { link = "TabLine" })
hi(0, "TabLineSel", { bg = "#1a1321", fg = "#d3baf1" })
hi(0, "TargetFileName", { fg = "#c8c5cc" })
hi(0, "TelescopeBorder", { fg = "#d3baf1" })
hi(0, "TelescopeMatching", { bold = true })
hi(0, "TelescopeMultiSelection", { bg = "#5a5264" })
hi(0, "TelescopeNormal", { link = "NormalFloat" })
hi(0, "TelescopePromptNormal", { link = "NormalFloat" })
hi(0, "TelescopeSelection", { bg = "#3f3848" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { fg = "#d3baf1" })
hi(0, "Todo", { bg = "#261f2e", bold = true, fg = "#d3baf1" })
hi(0, "TroubleCount", { bold = true, fg = "#d3baf1" })
hi(0, "TroubleFoldIcon", { bold = true, fg = "#d3baf1" })
hi(0, "TroubleIndent", { fg = "#5a5264" })
hi(0, "TroubleLocation", { fg = "#aba8af" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#c8c5cc" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#c8c5cc" })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", { fg = "#d3baf1" })
hi(0, "Visual", { bg = "#5a5264" })
hi(0, "VisualNOS", { bg = "#3f3848" })
hi(0, "WarningMsg", { fg = "#d0c98c" })
hi(0, "WhichKey", { fg = "#86d8d5" })
hi(0, "WhichKeyDesc", { fg = "#c8c5cc" })
hi(0, "WhichKeyFloat", { bg = "#1a1321", fg = "#c8c5cc" })
hi(0, "WhichKeyGroup", { fg = "#f6b2b8" })
hi(0, "WhichKeySeparator", { fg = "#a4d6aa" })
hi(0, "WhichKeyValue", { link = "Comment" })
hi(0, "Whitespace", { fg = "#5a5264" })
hi(0, "WildMenu", { link = "PmenuSel" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { fg = "#d3baf1" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffRemoved", { link = "DiffFile" })
hi(0, "gitcommitBranch", { bold = true, fg = "#efba93" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#d0c98c" })
hi(0, "gitcommitDiscardedType", { fg = "#95cff5" })
hi(0, "gitcommitHeader", { link = "Title" })
hi(0, "gitcommitOverflow", { fg = "#d0c98c" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#a4d6aa" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#a4d6aa" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#86d8d5" })
hi(0, "lCursor", { bg = "#c8c5cc", fg = "#261f2e" })
hi(0, "lualine_a_command", { bg = "#e4dd9a", bold = true, fg = "#292232" })
hi(0, "lualine_a_inactive", { bg = "#dcd8e0", bold = true, fg = "#292232" })
hi(0, "lualine_a_insert", { bg = "#b4ebbb", bold = true, fg = "#292232" })
hi(0, "lualine_a_normal", { bg = "#dcd8e0", bold = true, fg = "#292232" })
hi(0, "lualine_a_replace", { bg = "#fac7f7", bold = true, fg = "#292232" })
hi(0, "lualine_a_terminal", { bg = "#e4dd9a", bold = true, fg = "#292232" })
hi(0, "lualine_a_visual", { bg = "#93edea", bold = true, fg = "#292232" })
hi(0, "lualine_b_command", { bg = "#292232", fg = "#e4dd9a" })
hi(0, "lualine_b_fancy_diagnostics_error_command", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diagnostics_error_inactive", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diagnostics_error_insert", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diagnostics_error_normal", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diagnostics_error_replace", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diagnostics_error_terminal", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diagnostics_error_visual", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diagnostics_hint_command", { bg = "#292232", fg = "#86d8d5" })
hi(0, "lualine_b_fancy_diagnostics_hint_inactive", { bg = "#292232", fg = "#86d8d5" })
hi(0, "lualine_b_fancy_diagnostics_hint_insert", { bg = "#292232", fg = "#86d8d5" })
hi(0, "lualine_b_fancy_diagnostics_hint_normal", { bg = "#292232", fg = "#86d8d5" })
hi(0, "lualine_b_fancy_diagnostics_hint_replace", { bg = "#292232", fg = "#86d8d5" })
hi(0, "lualine_b_fancy_diagnostics_hint_terminal", { bg = "#292232", fg = "#86d8d5" })
hi(0, "lualine_b_fancy_diagnostics_hint_visual", { bg = "#292232", fg = "#86d8d5" })
hi(0, "lualine_b_fancy_diagnostics_info_command", { bg = "#292232", fg = "#bfc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_inactive", { bg = "#292232", fg = "#bfc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_insert", { bg = "#292232", fg = "#bfc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_normal", { bg = "#292232", fg = "#bfc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_replace", { bg = "#292232", fg = "#bfc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_terminal", { bg = "#292232", fg = "#bfc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_visual", { bg = "#292232", fg = "#bfc1fa" })
hi(0, "lualine_b_fancy_diagnostics_warn_command", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_inactive", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_insert", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_normal", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_replace", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_terminal", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_visual", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diff_added_command", { bg = "#292232", fg = "#a4d6aa" })
hi(0, "lualine_b_fancy_diff_added_inactive", { bg = "#292232", fg = "#a4d6aa" })
hi(0, "lualine_b_fancy_diff_added_insert", { bg = "#292232", fg = "#a4d6aa" })
hi(0, "lualine_b_fancy_diff_added_normal", { bg = "#292232", fg = "#a4d6aa" })
hi(0, "lualine_b_fancy_diff_added_replace", { bg = "#292232", fg = "#a4d6aa" })
hi(0, "lualine_b_fancy_diff_added_terminal", { bg = "#292232", fg = "#a4d6aa" })
hi(0, "lualine_b_fancy_diff_added_visual", { bg = "#292232", fg = "#a4d6aa" })
hi(0, "lualine_b_fancy_diff_modified_command", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diff_modified_inactive", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diff_modified_insert", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diff_modified_normal", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diff_modified_replace", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diff_modified_terminal", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diff_modified_visual", { bg = "#292232", fg = "#d0c98c" })
hi(0, "lualine_b_fancy_diff_removed_command", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diff_removed_inactive", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diff_removed_insert", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diff_removed_normal", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diff_removed_replace", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diff_removed_terminal", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_fancy_diff_removed_visual", { bg = "#292232", fg = "#f6b2b8" })
hi(0, "lualine_b_inactive", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_b_insert", { bg = "#292232", fg = "#b4ebbb" })
hi(0, "lualine_b_normal", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_b_replace", { bg = "#292232", fg = "#fac7f7" })
hi(0, "lualine_b_terminal", { bg = "#292232", fg = "#e4dd9a" })
hi(0, "lualine_b_visual", { bg = "#292232", fg = "#93edea" })
hi(0, "lualine_c_command", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_c_inactive", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_c_insert", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_c_normal", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_c_replace", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_c_terminal", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_c_visual", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#292232", fg = "#e4dd9a" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_y_fancy_filetype_ts_icon_command", { bg = "#292232", fg = "#e4dd9a" })
hi(0, "lualine_transitional_lualine_a_insert_to_lualine_b_insert", { bg = "#292232", fg = "#b4ebbb" })
hi(0, "lualine_transitional_lualine_a_insert_to_lualine_y_fancy_filetype_ts_icon_insert", { bg = "#292232", fg = "#b4ebbb" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_y_fancy_filetype_ts_icon_normal", { bg = "#292232", fg = "#dcd8e0" })
hi(0, "lualine_x_fancy_macro_command", { bg = "#292232", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_inactive", { bg = "#292232", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_insert", { bg = "#292232", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_normal", { bg = "#292232", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_replace", { bg = "#292232", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_terminal", { bg = "#292232", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_visual", { bg = "#292232", fg = "#ff0000" })
hi(0, "lualine_y_fancy_filetype_DevIconLua_command", { bg = "#292232", fg = "#51a0cf" })
hi(0, "lualine_y_fancy_filetype_DevIconLua_inactive", { bg = "#292232", fg = "#51a0cf" })
hi(0, "lualine_y_fancy_filetype_DevIconLua_insert", { bg = "#292232", fg = "#51a0cf" })
hi(0, "lualine_y_fancy_filetype_DevIconLua_normal", { bg = "#292232", fg = "#51a0cf" })
hi(0, "lualine_y_fancy_filetype_DevIconLua_replace", { bg = "#292232", fg = "#51a0cf" })
hi(0, "lualine_y_fancy_filetype_DevIconLua_terminal", { bg = "#292232", fg = "#51a0cf" })
hi(0, "lualine_y_fancy_filetype_DevIconLua_visual", { bg = "#292232", fg = "#51a0cf" })
hi(0, "lualine_y_fancy_filetype_ts_icon_command", { bg = "#292232", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_inactive", { bg = "#292232", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_insert", { bg = "#292232", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_normal", { bg = "#292232", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_replace", { bg = "#292232", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_terminal", { bg = "#292232", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_visual", { bg = "#292232", fg = "#41942c" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#261f2e"
g.terminal_color_1 = "#f6b2b8"
g.terminal_color_2 = "#a4d6aa"
g.terminal_color_3 = "#d0c98c"
g.terminal_color_4 = "#95cff5"
g.terminal_color_5 = "#e4b5e1"
g.terminal_color_6 = "#86d8d5"
g.terminal_color_7 = "#c8c5cc"
g.terminal_color_8 = "#261f2e"
g.terminal_color_9 = "#f6b2b8"
g.terminal_color_10 = "#a4d6aa"
g.terminal_color_11 = "#d0c98c"
g.terminal_color_12 = "#95cff5"
g.terminal_color_13 = "#e4b5e1"
g.terminal_color_14 = "#86d8d5"
g.terminal_color_15 = "#c8c5cc"
