-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "rosey"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@keyword.return", { bold = true, fg = "#bcd096" })
hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
hi(0, "@lsp.mod.deprecated", { fg = "#92d8be" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.decorator", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@lsp.type" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.struct", { link = "@structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", {})
hi(0, "@method.call", { link = "Function" })
hi(0, "@parameter", { fg = "#a7c8fb" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@structure", { link = "Structure" })
hi(0, "@symbol", { link = "Keyword" })
hi(0, "@text.danger", { link = "ErrorMsg" })
hi(0, "@text.emphasis", { fg = "#f5b5a5", italic = true })
hi(0, "@text.literal", { link = "Comment" })
hi(0, "@text.note", { link = "MoreMsg" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#efb2cf" })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.title.1.markdown", { link = "rainbow1" })
hi(0, "@text.title.2.markdown", { link = "rainbow2" })
hi(0, "@text.title.3.markdown", { link = "rainbow3" })
hi(0, "@text.title.4.markdown", { link = "rainbow4" })
hi(0, "@text.title.5.markdown", { link = "rainbow5" })
hi(0, "@text.title.6.markdown", { link = "rainbow6" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@variable", { fg = "#c5c6cd" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "Beacon", { bg = "#ececf3" })
hi(0, "Bold", { bold = true })
hi(0, "BufferCurrent", { bg = "#202131", bold = true, fg = "#bec2fa" })
hi(0, "BufferCurrentIcon", { bg = "#202131" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#383a4c", bold = true, fg = "#bec2fa" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#535467", bold = true, fg = "#bec2fa" })
hi(0, "BufferInactive", { bg = "#151524", fg = "#c5c6cd" })
hi(0, "BufferInactiveIcon", { bg = "#151524" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#383a4c", fg = "#c5c6cd" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#535467", fg = "#c5c6cd" })
hi(0, "BufferLineBuffer", { fg = "#8c8c92" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#c5c6cd" })
hi(0, "BufferLineBufferVisible", { fg = "#c5c6cd" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#f5b5a5", fg = "#202131" })
hi(0, "BufferLineTabSelected", { bg = "#f5b5a5", bold = true, fg = "#202131" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#f5b5a5", bold = true, fg = "#202131" })
hi(0, "BufferVisible", { bg = "#202131", bold = true, fg = "#c5c6cd" })
hi(0, "BufferVisibleIcon", { bg = "#202131" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#383a4c", bold = true, fg = "#c5c6cd" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#535467", bold = true, fg = "#c5c6cd" })
hi(0, "CmpItemAbbr", { fg = "#c5c6cd" })
hi(0, "CmpItemAbbrDefault", { fg = "#c5c6cd" })
hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#8c8c92" })
hi(0, "CmpItemAbbrMatch", { bold = true })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c5c6cd" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c5c6cd" })
hi(0, "CmpItemKind", { fg = "#c5c6cd" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#efb2cf" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "Normal" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#c5c6cd" })
hi(0, "CmpItemMenuDefault", { fg = "#c5c6cd" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocErrorFloat", { link = "DiagnosticFloatingError" })
hi(0, "CocErrorHighlight", { link = "DiagnosticError" })
hi(0, "CocErrorSign", { link = "DiagnosticSignError" })
hi(0, "CocHintFloat", { link = "DiagnosticFloatingHint" })
hi(0, "CocHintHighlight", { link = "DiagnosticHint" })
hi(0, "CocHintSign", { link = "DiagnosticSignHint" })
hi(0, "CocInfoFloat", { link = "DiagnosticFloatingInfo" })
hi(0, "CocInfoHighlight", { link = "DiagnosticInfo" })
hi(0, "CocInfoSign", { link = "DiagnosticSignInfo" })
hi(0, "CocMarkdownLink", { fg = "#a7c8fb" })
hi(0, "CocMenuSel", { bg = "#535467" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#a7c8fb" })
hi(0, "CocSelectedText", { fg = "#e3c18b" })
hi(0, "CocWarningFloat", { link = "DiagnosticFloatingWarn" })
hi(0, "CocWarningHighlight", { link = "DiagnosticWarn" })
hi(0, "CocWarningSign", { link = "DiagnosticSignWarn" })
hi(0, "ColorColumn", { bg = "#535467" })
hi(0, "Comment", { fg = "#8c8c92" })
hi(0, "Conceal", { fg = "#d1baf2" })
hi(0, "Constant", { fg = "#87d5e7" })
hi(0, "CurSearch", { bg = "#e3c18b", fg = "#202131" })
hi(0, "Cursor", { bg = "#c5c6cd", fg = "#202131" })
hi(0, "CursorColumn", { bg = "#383a4c" })
hi(0, "CursorIM", { link = "Cursor" })
hi(0, "CursorLine", { bg = "#383a4c" })
hi(0, "CursorLineFold", { fg = "#535467" })
hi(0, "CursorLineNr", { bold = true, fg = "#bec2fa" })
hi(0, "CursorLineSign", { fg = "#535467" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#f5b5a5" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#bcd096" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Comment" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "WarningMsg" })
hi(0, "Definitions", { fg = "#f5b5a5" })
hi(0, "DefinitionsIcon", { fg = "#d1baf2" })
hi(0, "Delimiter", { fg = "#bcd096" })
hi(0, "DiagnosticDeprecated", { sp = "#92d8be", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#92d8be" })
hi(0, "DiagnosticFloatingError", { bg = "#151524", fg = "#92d8be" })
hi(0, "DiagnosticFloatingHint", { bg = "#151524", fg = "#efb2cf" })
hi(0, "DiagnosticFloatingInfo", { bg = "#151524", fg = "#a7c8fb" })
hi(0, "DiagnosticFloatingOk", { bg = "#151524", fg = "#f5b5a5" })
hi(0, "DiagnosticFloatingWarn", { bg = "#151524", fg = "#e3c18b" })
hi(0, "DiagnosticHint", { fg = "#efb2cf" })
hi(0, "DiagnosticInfo", { fg = "#a7c8fb" })
hi(0, "DiagnosticOk", { fg = "#f5b5a5" })
hi(0, "DiagnosticUnderlineError", { sp = "#92d8be", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#efb2cf", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#a7c8fb", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#f5b5a5", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#e3c18b", underline = true })
hi(0, "DiagnosticWarn", { fg = "#e3c18b" })
hi(0, "DiffAdd", { bg = "#421106" })
hi(0, "DiffAdded", { link = "DiffAdd" })
hi(0, "DiffChange", { bg = "#493200" })
hi(0, "DiffDelete", { bg = "#002b1e" })
hi(0, "DiffFile", { bg = "#493200" })
hi(0, "DiffRemoved", { link = "DiffFile" })
hi(0, "DiffText", { bg = "#535467" })
hi(0, "Directory", { fg = "#d1baf2" })
hi(0, "EndOfBuffer", { fg = "#535467" })
hi(0, "Error", { bg = "#002b1e" })
hi(0, "ErrorMsg", { fg = "#92d8be" })
hi(0, "FinderParam", { fg = "#e3c18b" })
hi(0, "FinderSpinner", { fg = "#f5b5a5" })
hi(0, "FinderSpinnerBorder", { fg = "#bec2fa" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#bcd096" })
hi(0, "FlashBackdrop", {})
hi(0, "FlashCurrent", {})
hi(0, "FlashLabel", {})
hi(0, "FlashMatch", {})
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { bg = "#151524", fg = "#bec2fa" })
hi(0, "FloatTitle", { bg = "#151524", bold = true, fg = "#bec2fa" })
hi(0, "FoldColumn", { fg = "#535467" })
hi(0, "Folded", { bg = "#383a4c", fg = "#8c8c92" })
hi(0, "Function", { fg = "#d1baf2" })
hi(0, "GitSignsAdd", { fg = "#f5b5a5" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { fg = "#e3c18b" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { fg = "#92d8be" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsStagedAdd", { fg = "#7a5a52" })
hi(0, "GitSignsStagedAddLn", { fg = "#7a5a52" })
hi(0, "GitSignsStagedAddNr", { fg = "#7a5a52" })
hi(0, "GitSignsStagedChange", { fg = "#716046" })
hi(0, "GitSignsStagedChangeLn", { fg = "#716046" })
hi(0, "GitSignsStagedChangeNr", { fg = "#716046" })
hi(0, "GitSignsStagedChangedelete", { fg = "#716046" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#716046" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#716046" })
hi(0, "GitSignsStagedDelete", { fg = "#496c5f" })
hi(0, "GitSignsStagedDeleteLn", { fg = "#496c5f" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#496c5f" })
hi(0, "GitSignsStagedTopdelete", { fg = "#496c5f" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#496c5f" })
hi(0, "GitSignsUntracked", { fg = "#d1baf2" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HopNextKey", { bold = true, fg = "#f5b5a5", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#bcd096", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#a8a9b0", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#e3c18b", nocombine = true })
hi(0, "HopUnmatched", { fg = "#535467" })
hi(0, "HydraAmaranth", { fg = "#87d5e7" })
hi(0, "HydraBlue", { fg = "#d1baf2" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#bcd096" })
hi(0, "HydraRed", { fg = "#92d8be" })
hi(0, "HydraTeal", { fg = "#efb2cf" })
hi(0, "Identifier", { fg = "#e3c18b" })
hi(0, "Ignore", {})
hi(0, "IncSearch", { bg = "#e3c18b", fg = "#202131" })
hi(0, "IndentBlanklineChar", { fg = "#535467", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#bec2fa", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#bec2fa", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#a7c8fb", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#efb2cf", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#e3c18b", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#92d8be", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#d1baf2", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#f5b5a5", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#bcd096", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#87d5e7", nocombine = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#535467", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#535467", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "LSOutlinePreviewBorder", { fg = "#bec2fa" })
hi(0, "LazyButton", { bg = "#383a4c" })
hi(0, "LazyButtonActive", { bg = "#535467" })
hi(0, "LazyComment", { fg = "#8c8c92" })
hi(0, "LazyCommit", { fg = "#efb2cf" })
hi(0, "LazyCommitIssue", { fg = "#87d5e7" })
hi(0, "LazyCommitScope", { italic = true })
hi(0, "LazyCommitType", { fg = "#bec2fa" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyDir", { fg = "#e3c18b" })
hi(0, "LazyH1", { bg = "#535467", bold = true, fg = "#bec2fa" })
hi(0, "LazyH2", { bold = true })
hi(0, "LazyLocal", { fg = "#87d5e7" })
hi(0, "LazyNoCond", { fg = "#e3c18b" })
hi(0, "LazyNormal", { bg = "#151524", fg = "#c5c6cd" })
hi(0, "LazyProgressDone", { fg = "#87d5e7" })
hi(0, "LazyProgressTodo", { fg = "#535467" })
hi(0, "LazyProp", { fg = "#d1baf2" })
hi(0, "LazyReasonCmd", { fg = "#c5c6cd" })
hi(0, "LazyReasonEvent", { fg = "#87d5e7" })
hi(0, "LazyReasonFt", { fg = "#87d5e7" })
hi(0, "LazyReasonImport", { fg = "#e3c18b" })
hi(0, "LazyReasonKeys", { bold = true })
hi(0, "LazyReasonPlugin", { fg = "#efb2cf" })
hi(0, "LazyReasonRuntime", { fg = "#a7c8fb" })
hi(0, "LazyReasonSource", { fg = "#87d5e7" })
hi(0, "LazyReasonStart", { fg = "#e3c18b" })
hi(0, "LazySpecial", { fg = "#bcd096" })
hi(0, "LazyTaskError", { fg = "#92d8be" })
hi(0, "LazyTaskOutput", { bg = "#202131", fg = "#c5c6cd" })
hi(0, "LazyUrl", { fg = "#e3c18b" })
hi(0, "LazyValue", { fg = "#f5b5a5" })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabelPrimary", { bold = true, fg = "#e3c18b", nocombine = true })
hi(0, "LeapLabelSecondary", { bold = true, fg = "#c5c6cd", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#efb2cf", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#f5b5a5", nocombine = true })
hi(0, "LineNr", { fg = "#535467" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceRead", { link = "LspReferenceText" })
hi(0, "LspReferenceText", { bg = "#535467" })
hi(0, "LspReferenceWrite", { link = "LspReferenceText" })
hi(0, "LspSagaAutoPreview", { fg = "#a7c8fb" })
hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
hi(0, "LspSagaCodeActionBorder", { fg = "#bec2fa" })
hi(0, "LspSagaCodeActionContent", { fg = "#c5c6cd" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#d1baf2" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#bec2fa" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#bec2fa" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#bcd096" })
hi(0, "LspSagaFinderSelection", { fg = "#efb2cf" })
hi(0, "LspSagaHoverBorder", { fg = "#bec2fa" })
hi(0, "LspSagaLspFinderBorder", { fg = "#bec2fa" })
hi(0, "LspSagaRenameBorder", { fg = "#bec2fa" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#bec2fa" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "MasonError", { fg = "#92d8be" })
hi(0, "MasonHeader", { bg = "#d1baf2", bold = true, fg = "#202131" })
hi(0, "MasonHeaderSecondary", { bg = "#a7c8fb", bold = true, fg = "#202131" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#bec2fa" })
hi(0, "MasonHighlightBlock", { bg = "#bec2fa", fg = "#202131" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#d1baf2", fg = "#202131" })
hi(0, "MasonHighlightSecondary", { fg = "#d1baf2" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#535467", fg = "#202131" })
hi(0, "MasonMutedBlockBold", { bg = "#535467", bold = true, fg = "#202131" })
hi(0, "MatchParen", { bg = "#535467", bold = true })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { bg = "#535467" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniFilesFile", { fg = "#c5c6cd" })
hi(0, "MiniFilesTitleFocused", { bg = "#151524", bold = true, fg = "#c5c6cd" })
hi(0, "MiniHipatternsFixme", { bg = "#92d8be", bold = true, fg = "#202131" })
hi(0, "MiniHipatternsHack", { bg = "#e3c18b", bold = true, fg = "#202131" })
hi(0, "MiniHipatternsNote", { bg = "#efb2cf", bold = true, fg = "#202131" })
hi(0, "MiniHipatternsTodo", { bg = "#a7c8fb", bold = true, fg = "#202131" })
hi(0, "MiniIndentscopeSymbol", { fg = "#bec2fa" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#92d8be" })
hi(0, "MiniJump", { sp = "#bec2fa", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#535467" })
hi(0, "MiniJump2dSpot", { bg = "#060714", bold = true, fg = "#ececf3", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#060714", fg = "#d7d8df", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#151524", fg = "#8c8c92" })
hi(0, "MiniMapSymbolCount", { fg = "#8c8c92" })
hi(0, "MiniMapSymbolLine", { fg = "#bec2fa" })
hi(0, "MiniMapSymbolView", { fg = "#bec2fa" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniStarterCurrent", { link = "MiniStarterItem" })
hi(0, "MiniStarterFooter", { link = "Comment" })
hi(0, "MiniStarterHeader", { bold = true, fg = "#bec2fa" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItemBullet", { fg = "#8c8c92" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#e3c18b" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#f5b5a5" })
hi(0, "MiniStarterSection", { fg = "#87d5e7" })
hi(0, "MiniStatuslineDevinfo", { bg = "#383a4c", fg = "#a8a9b0" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#151524", fg = "#a8a9b0" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { bg = "#e3c18b", bold = true, fg = "#202131" })
hi(0, "MiniStatuslineModeInsert", { bg = "#d1baf2", bold = true, fg = "#202131" })
hi(0, "MiniStatuslineModeNormal", { bg = "#c5c6cd", bold = true, fg = "#202131" })
hi(0, "MiniStatuslineModeOther", { bg = "#efb2cf", bold = true, fg = "#202131" })
hi(0, "MiniStatuslineModeReplace", { bg = "#92d8be", bold = true, fg = "#202131" })
hi(0, "MiniStatuslineModeVisual", { bg = "#f5b5a5", bold = true, fg = "#202131" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#202131", bold = true, fg = "#bec2fa" })
hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
hi(0, "MiniTablineHidden", { bg = "#151524", fg = "#a8a9b0" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#bec2fa", bold = true, fg = "#202131" })
hi(0, "MiniTablineModifiedHidden", { bg = "#a8a9b0", fg = "#151524" })
hi(0, "MiniTablineModifiedVisible", { bg = "#a8a9b0", bold = true, fg = "#151524" })
hi(0, "MiniTablineTabpagesection", { bg = "#f5b5a5", bold = true, fg = "#202131" })
hi(0, "MiniTablineVisible", { bg = "#151524", bold = true, fg = "#a8a9b0" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#92d8be" })
hi(0, "MiniTestPass", { bold = true, fg = "#f5b5a5" })
hi(0, "MiniTrailspace", { bg = "#002b1e" })
hi(0, "ModeMsg", { fg = "#f5b5a5" })
hi(0, "MoreMsg", { fg = "#d1baf2" })
hi(0, "MsgArea", { link = "Normal" })
hi(0, "MsgSeparator", { bg = "#535467", fg = "#8c8c92" })
hi(0, "NeoTreeDimText", { fg = "#535467" })
hi(0, "NeoTreeDotfile", { fg = "#a8a9b0" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#535467" })
hi(0, "NeoTreeGitAdded", { fg = "#f5b5a5" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#bcd096" })
hi(0, "NeoTreeGitDeleted", { fg = "#92d8be" })
hi(0, "NeoTreeGitModified", { fg = "#e3c18b" })
hi(0, "NeoTreeGitUnstaged", { fg = "#87d5e7" })
hi(0, "NeoTreeGitUntracked", { fg = "#efb2cf" })
hi(0, "NeoTreeMessage", { bg = "#383a4c", fg = "#c5c6cd" })
hi(0, "NeoTreeModified", { fg = "#d7d8df" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#bec2fa" })
hi(0, "NeoTreeTabInactive", { fg = "#8c8c92" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#535467", fg = "#8c8c92" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#383a4c", fg = "#383a4c" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#bec2fa" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#bec2fa" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceAttr1138", { bg = "#905668", fg = "#ffffff" })
hi(0, "NoiceAttr1826", { fg = "#eebb92" })
hi(0, "NoiceAttr1827", { bg = "#54927f", bold = true, fg = "#20242f" })
hi(0, "NoiceAttr2048", { fg = "#f0b89a" })
hi(0, "NoiceAttr2226", { fg = "#f4b6a1" })
hi(0, "NoiceAttr2659", { fg = "#eeba93" })
hi(0, "NoiceAttr294", { fg = "#d7b9ee" })
hi(0, "NoiceAttr303", { fg = "#8fd9c3" })
hi(0, "NoiceAttr308", { fg = "#f5b5a0" })
hi(0, "NoiceAttr311", { bg = "#231111", fg = "#cdc4c4" })
hi(0, "NoiceAttr3156", { fg = "#f7b699" })
hi(0, "NoiceAttr726", { fg = "#d1b9de" })
hi(0, "NoiceCmdline", { bg = "#202131", fg = "#c5c6cd" })
hi(0, "NoiceCmdlineIcon", { fg = "#a7c8fb" })
hi(0, "NoiceCmdlineIconCalculator", { fg = "#a7c8fb" })
hi(0, "NoiceCmdlineIconCmdline", { fg = "#a7c8fb" })
hi(0, "NoiceCmdlineIconFilter", { fg = "#a7c8fb" })
hi(0, "NoiceCmdlineIconHelp", { fg = "#a7c8fb" })
hi(0, "NoiceCmdlineIconInput", { fg = "#a7c8fb" })
hi(0, "NoiceCmdlineIconLua", { fg = "#a7c8fb" })
hi(0, "NoiceCmdlineIconSearch", { fg = "#e3c18b" })
hi(0, "NoiceCmdlinePopup", { bg = "#202131", fg = "#c5c6cd" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#d1baf2" })
hi(0, "NoiceCmdlinePopupBorderCalculator", { fg = "#d1baf2" })
hi(0, "NoiceCmdlinePopupBorderCmdline", { fg = "#d1baf2" })
hi(0, "NoiceCmdlinePopupBorderFilter", { fg = "#d1baf2" })
hi(0, "NoiceCmdlinePopupBorderHelp", { fg = "#d1baf2" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#d1baf2" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#d1baf2" })
hi(0, "NoiceCmdlinePopupBorderSearch", { fg = "#e3c18b" })
hi(0, "NoiceCmdlinePopupTitle", { fg = "#a7c8fb" })
hi(0, "NoiceCmdlinePrompt", { fg = "#bec2fa" })
hi(0, "NoiceCompletionItemKindClass", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindColor", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindConstant", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindConstructor", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindEnum", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindEnumMember", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindField", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindFile", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindFolder", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindFunction", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindInterface", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindKeyword", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindMethod", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindModule", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindProperty", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindSnippet", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindStruct", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindText", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindUnit", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindValue", { fg = "#efb2cf" })
hi(0, "NoiceCompletionItemKindVariable", { fg = "#efb2cf" })
hi(0, "NoiceConfirm", { bg = "#202131", fg = "#c5c6cd" })
hi(0, "NoiceConfirmBorder", { fg = "#e3c18b" })
hi(0, "NoiceCursor", { bg = "#c5c6cd", fg = "#202131" })
hi(0, "NoiceFormatConfirm", { bg = "#383a4c" })
hi(0, "NoiceFormatConfirmDefault", { bg = "#535467" })
hi(0, "NoiceFormatDate", { fg = "#efb2cf" })
hi(0, "NoiceFormatEvent", { fg = "#535467" })
hi(0, "NoiceFormatKind", { fg = "#535467" })
hi(0, "NoiceFormatLevelDebug", { fg = "#535467" })
hi(0, "NoiceFormatLevelError", { fg = "#92d8be" })
hi(0, "NoiceFormatLevelInfo", { fg = "#a7c8fb" })
hi(0, "NoiceFormatLevelOff", { fg = "#535467" })
hi(0, "NoiceFormatLevelTrace", { fg = "#535467" })
hi(0, "NoiceFormatLevelWarn", { fg = "#e3c18b" })
hi(0, "NoiceFormatProgressDone", { bg = "#bec2fa", fg = "#202131" })
hi(0, "NoiceFormatProgressTodo", { bg = "#383a4c" })
hi(0, "NoiceFormatTitle", { fg = "#bec2fa" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NoiceLspProgressClient", { fg = "#bec2fa" })
hi(0, "NoiceLspProgressSpinner", { fg = "#87d5e7" })
hi(0, "NoiceLspProgressTitle", { fg = "#535467" })
hi(0, "NoiceMini", { bg = "#202131", fg = "#c5c6cd" })
hi(0, "NoicePopup", { bg = "#151524", fg = "#c5c6cd" })
hi(0, "NoicePopupBorder", { bg = "#151524", fg = "#bec2fa" })
hi(0, "NoicePopupmenu", { bg = "#383a4c", fg = "#c5c6cd" })
hi(0, "NoicePopupmenuBorder", { bg = "#151524", fg = "#bec2fa" })
hi(0, "NoicePopupmenuMatch", { fg = "#efb2cf" })
hi(0, "NoicePopupmenuSelected", { bg = "#c5c6cd", blend = 0, fg = "#202131" })
hi(0, "NoiceScrollbar", { bg = "#383a4c", fg = "#c5c6cd" })
hi(0, "NoiceScrollbarThumb", { bg = "#535467" })
hi(0, "NoiceSplit", { bg = "#151524", fg = "#c5c6cd" })
hi(0, "NoiceSplitBorder", { bg = "#151524", fg = "#bec2fa" })
hi(0, "NoiceVirtualText", { fg = "#a7c8fb" })
hi(0, "NonText", { fg = "#535467" })
hi(0, "Normal", { bg = "#202131", fg = "#c5c6cd" })
hi(0, "NormalFloat", { bg = "#151524", fg = "#c5c6cd" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#f5b5a5" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBody529", { bg = "#202131", fg = "#c5c6cd" })
hi(0, "NotifyERRORBorder", { fg = "#92d8be" })
hi(0, "NotifyERRORBorder529", { fg = "#92d8be" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORIcon529", { fg = "#92d8be" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle529", { fg = "#92d8be" })
hi(0, "NotifyINFOBorder", { fg = "#a7c8fb" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#efb2cf" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#e3c18b" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "NvimInternalError", { bg = "#00a44d", ctermbg = 9, ctermfg = 9, fg = "#00a44d" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#f5b5a5" })
hi(0, "NvimTreeFolderIcon", { fg = "#8c8c92" })
hi(0, "NvimTreeGitDeleted", { fg = "#92d8be" })
hi(0, "NvimTreeGitDirty", { fg = "#e3c18b" })
hi(0, "NvimTreeGitMerge", { fg = "#bcd096" })
hi(0, "NvimTreeGitNew", { fg = "#efb2cf" })
hi(0, "NvimTreeGitRenamed", { fg = "#87d5e7" })
hi(0, "NvimTreeGitStaged", { fg = "#f5b5a5" })
hi(0, "NvimTreeImageFile", { fg = "#bcd096" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#bec2fa" })
hi(0, "NvimTreeSpecialFile", { fg = "#bec2fa", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#a7c8fb" })
hi(0, "NvimTreeWindowPicker", { bg = "#535467", bold = true, fg = "#c5c6cd" })
hi(0, "Operator", { fg = "#c5c6cd" })
hi(0, "OutlineDetail", { fg = "#535467" })
hi(0, "OutlineFoldPrefix", { fg = "#e3c18b" })
hi(0, "OutlineIndentEvn", { fg = "#8c8c92" })
hi(0, "OutlineIndentOdd", { fg = "#c5c6cd" })
hi(0, "Pmenu", { bg = "#383a4c", fg = "#c5c6cd" })
hi(0, "PmenuSbar", { link = "Pmenu" })
hi(0, "PmenuSel", { bg = "#c5c6cd", blend = 0, fg = "#202131" })
hi(0, "PmenuThumb", { bg = "#535467" })
hi(0, "PounceAccept", { bg = "#e3c18b", bold = true, fg = "#202131", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#f5b5a5", bold = true, fg = "#202131", nocombine = true })
hi(0, "PounceGap", { bg = "#535467", bold = true, fg = "#202131", nocombine = true })
hi(0, "PounceMatch", { bg = "#c5c6cd", bold = true, fg = "#202131", nocombine = true })
hi(0, "PreProc", { fg = "#a7c8fb" })
hi(0, "Question", { fg = "#d1baf2" })
hi(0, "QuickFixLine", { bg = "#383a4c" })
hi(0, "RainbowDelimiterBlue", { fg = "#d1baf2" })
hi(0, "RainbowDelimiterCyan", { fg = "#efb2cf" })
hi(0, "RainbowDelimiterGreen", { fg = "#f5b5a5" })
hi(0, "RainbowDelimiterOrange", { fg = "#bcd096" })
hi(0, "RainbowDelimiterRed", { fg = "#92d8be" })
hi(0, "RainbowDelimiterViolet", { fg = "#87d5e7" })
hi(0, "RainbowDelimiterYellow", { fg = "#e3c18b" })
hi(0, "RedrawDebugClear", { bg = "#fff2e2", ctermbg = 11 })
hi(0, "RedrawDebugComposed", { bg = "#b63500", ctermbg = 10 })
hi(0, "RedrawDebugRecompose", { bg = "#00a44d", ctermbg = 9 })
hi(0, "References", { fg = "#f5b5a5" })
hi(0, "ReferencesIcon", { fg = "#d1baf2" })
hi(0, "Search", { bg = "#bec2fa", fg = "#202131" })
hi(0, "SignColumn", { fg = "#535467" })
hi(0, "Sneak", { bg = "#bcd096", fg = "#202131" })
hi(0, "SneakLabel", { bg = "#bcd096", bold = true, fg = "#202131" })
hi(0, "SneakScope", { bg = "#ececf3", fg = "#202131" })
hi(0, "Special", { fg = "#efb2cf" })
hi(0, "SpecialKey", { fg = "#535467" })
hi(0, "SpellBad", { sp = "#92d8be", undercurl = true })
hi(0, "SpellCap", { sp = "#efb2cf", undercurl = true })
hi(0, "SpellLocal", { sp = "#e3c18b", undercurl = true })
hi(0, "SpellRare", { sp = "#a7c8fb", undercurl = true })
hi(0, "Statement", { bold = true })
hi(0, "StatusLine", { bg = "#202131", fg = "#a8a9b0" })
hi(0, "StatusLineNC", { bg = "#151524", fg = "#a8a9b0" })
hi(0, "String", { fg = "#f5b5a5" })
hi(0, "Substitute", { bg = "#a7c8fb", fg = "#202131" })
hi(0, "TabLine", { bg = "#151524", fg = "#a8a9b0" })
hi(0, "TabLineFill", { link = "TabLine" })
hi(0, "TabLineSel", { bg = "#151524", fg = "#bec2fa" })
hi(0, "TargetFileName", { fg = "#c5c6cd" })
hi(0, "TelescopeBorder", { bg = "#151524", fg = "#bec2fa" })
hi(0, "TelescopeMatching", { bold = true })
hi(0, "TelescopeMultiSelection", { bg = "#535467" })
hi(0, "TelescopeNormal", { link = "NormalFloat" })
hi(0, "TelescopePromptNormal", { link = "NormalFloat" })
hi(0, "TelescopeSelection", { bg = "#383a4c" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { fg = "#bec2fa" })
hi(0, "Todo", { bg = "#202131", bold = true, fg = "#bec2fa" })
hi(0, "TroubleCount", { bold = true, fg = "#bec2fa" })
hi(0, "TroubleFoldIcon", { bold = true, fg = "#bec2fa" })
hi(0, "TroubleIndent", { fg = "#535467" })
hi(0, "TroubleLocation", { fg = "#a8a9b0" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#c5c6cd" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#c5c6cd" })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", { fg = "#bec2fa" })
hi(0, "Visual", { bg = "#535467" })
hi(0, "VisualNOS", { bg = "#383a4c" })
hi(0, "WarningMsg", { fg = "#e3c18b" })
hi(0, "WhichKey", { fg = "#efb2cf" })
hi(0, "WhichKeyDesc", { fg = "#c5c6cd" })
hi(0, "WhichKeyFloat", { bg = "#151524", fg = "#c5c6cd" })
hi(0, "WhichKeyGroup", { fg = "#92d8be" })
hi(0, "WhichKeySeparator", { fg = "#f5b5a5" })
hi(0, "Whitespace", { fg = "#535467" })
hi(0, "WildMenu", { link = "PmenuSel" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { fg = "#bec2fa" })
hi(0, "diffLine", { bg = "#072148" })
hi(0, "diffNewFile", { link = "DiffAdded" })
hi(0, "gitcommitBranch", { bold = true, fg = "#bcd096" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#e3c18b" })
hi(0, "gitcommitDiscardedType", { fg = "#d1baf2" })
hi(0, "gitcommitHeader", { link = "Title" })
hi(0, "gitcommitOverflow", { fg = "#e3c18b" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#f5b5a5" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#f5b5a5" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#efb2cf" })
hi(0, "htmlArg", {})
hi(0, "htmlBold", { bold = true })
hi(0, "htmlBoldItalic", { bold = true, italic = true })
hi(0, "htmlEndTag", {})
hi(0, "htmlH1", {})
hi(0, "htmlH2", {})
hi(0, "htmlH3", {})
hi(0, "htmlH4", {})
hi(0, "htmlH5", {})
hi(0, "htmlLink", {})
hi(0, "htmlTag", {})
hi(0, "htmlTagName", {})
hi(0, "lCursor", { bg = "#c5c6cd", fg = "#202131" })
hi(0, "lualine_a_command", { bg = "#fad499", bold = true, fg = "#232435" })
hi(0, "lualine_a_inactive", { bg = "#d8d9e1", bold = true, fg = "#232435" })
hi(0, "lualine_a_insert", { bg = "#ffc9b9", bold = true, fg = "#232435" })
hi(0, "lualine_a_normal", { bg = "#d8d9e1", bold = true, fg = "#232435" })
hi(0, "lualine_a_replace", { bg = "#95eafd", bold = true, fg = "#232435" })
hi(0, "lualine_a_terminal", { bg = "#fad499", bold = true, fg = "#232435" })
hi(0, "lualine_a_visual", { bg = "#ffc4e3", bold = true, fg = "#232435" })
hi(0, "lualine_b_command", { bg = "#232435", fg = "#fad499" })
hi(0, "lualine_b_fancy_diagnostics_error_command", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diagnostics_error_inactive", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diagnostics_error_insert", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diagnostics_error_normal", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diagnostics_error_replace", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diagnostics_error_terminal", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diagnostics_error_visual", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diagnostics_hint_command", { bg = "#232435", fg = "#efb2cf" })
hi(0, "lualine_b_fancy_diagnostics_hint_inactive", { bg = "#232435", fg = "#efb2cf" })
hi(0, "lualine_b_fancy_diagnostics_hint_insert", { bg = "#232435", fg = "#efb2cf" })
hi(0, "lualine_b_fancy_diagnostics_hint_normal", { bg = "#232435", fg = "#efb2cf" })
hi(0, "lualine_b_fancy_diagnostics_hint_replace", { bg = "#232435", fg = "#efb2cf" })
hi(0, "lualine_b_fancy_diagnostics_hint_terminal", { bg = "#232435", fg = "#efb2cf" })
hi(0, "lualine_b_fancy_diagnostics_hint_visual", { bg = "#232435", fg = "#efb2cf" })
hi(0, "lualine_b_fancy_diagnostics_info_command", { bg = "#232435", fg = "#a7c8fb" })
hi(0, "lualine_b_fancy_diagnostics_info_inactive", { bg = "#232435", fg = "#a7c8fb" })
hi(0, "lualine_b_fancy_diagnostics_info_insert", { bg = "#232435", fg = "#a7c8fb" })
hi(0, "lualine_b_fancy_diagnostics_info_normal", { bg = "#232435", fg = "#a7c8fb" })
hi(0, "lualine_b_fancy_diagnostics_info_replace", { bg = "#232435", fg = "#a7c8fb" })
hi(0, "lualine_b_fancy_diagnostics_info_terminal", { bg = "#232435", fg = "#a7c8fb" })
hi(0, "lualine_b_fancy_diagnostics_info_visual", { bg = "#232435", fg = "#a7c8fb" })
hi(0, "lualine_b_fancy_diagnostics_warn_command", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diagnostics_warn_inactive", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diagnostics_warn_insert", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diagnostics_warn_normal", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diagnostics_warn_replace", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diagnostics_warn_terminal", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diagnostics_warn_visual", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diff_added_command", { bg = "#232435", fg = "#f5b5a5" })
hi(0, "lualine_b_fancy_diff_added_inactive", { bg = "#232435", fg = "#f5b5a5" })
hi(0, "lualine_b_fancy_diff_added_insert", { bg = "#232435", fg = "#f5b5a5" })
hi(0, "lualine_b_fancy_diff_added_normal", { bg = "#232435", fg = "#f5b5a5" })
hi(0, "lualine_b_fancy_diff_added_replace", { bg = "#232435", fg = "#f5b5a5" })
hi(0, "lualine_b_fancy_diff_added_terminal", { bg = "#232435", fg = "#f5b5a5" })
hi(0, "lualine_b_fancy_diff_added_visual", { bg = "#232435", fg = "#f5b5a5" })
hi(0, "lualine_b_fancy_diff_modified_command", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diff_modified_inactive", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diff_modified_insert", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diff_modified_normal", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diff_modified_replace", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diff_modified_terminal", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diff_modified_visual", { bg = "#232435", fg = "#e3c18b" })
hi(0, "lualine_b_fancy_diff_removed_command", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diff_removed_inactive", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diff_removed_insert", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diff_removed_normal", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diff_removed_replace", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diff_removed_terminal", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_fancy_diff_removed_visual", { bg = "#232435", fg = "#92d8be" })
hi(0, "lualine_b_inactive", { bg = "#232435", fg = "#d8d9e1" })
hi(0, "lualine_b_insert", { bg = "#232435", fg = "#ffc9b9" })
hi(0, "lualine_b_normal", { bg = "#232435", fg = "#d8d9e1" })
hi(0, "lualine_b_replace", { bg = "#232435", fg = "#95eafd" })
hi(0, "lualine_b_terminal", { bg = "#232435", fg = "#fad499" })
hi(0, "lualine_b_visual", { bg = "#232435", fg = "#ffc4e3" })
hi(0, "lualine_c_command", { bg = "#232435", fg = "#d8d9e1" })
hi(0, "lualine_c_inactive", { bg = "#232435", fg = "#d8d9e1" })
hi(0, "lualine_c_insert", { bg = "#232435", fg = "#d8d9e1" })
hi(0, "lualine_c_normal", { bg = "#232435", fg = "#d8d9e1" })
hi(0, "lualine_c_replace", { bg = "#232435", fg = "#d8d9e1" })
hi(0, "lualine_c_terminal", { bg = "#232435", fg = "#d8d9e1" })
hi(0, "lualine_c_visual", { bg = "#232435", fg = "#d8d9e1" })
hi(0, "lualine_x_fancy_macro_command", { bg = "#232435", fg = "#00a44d" })
hi(0, "lualine_x_fancy_macro_inactive", { bg = "#232435", fg = "#00a44d" })
hi(0, "lualine_x_fancy_macro_insert", { bg = "#232435", fg = "#00a44d" })
hi(0, "lualine_x_fancy_macro_normal", { bg = "#232435", fg = "#00a44d" })
hi(0, "lualine_x_fancy_macro_replace", { bg = "#232435", fg = "#00a44d" })
hi(0, "lualine_x_fancy_macro_terminal", { bg = "#232435", fg = "#00a44d" })
hi(0, "lualine_x_fancy_macro_visual", { bg = "#232435", fg = "#00a44d" })
hi(0, "lualine_y_fancy_filetype_ts_icon_command", { bg = "#232435", fg = "#ca5426" })
hi(0, "lualine_y_fancy_filetype_ts_icon_inactive", { bg = "#232435", fg = "#ca5426" })
hi(0, "lualine_y_fancy_filetype_ts_icon_insert", { bg = "#232435", fg = "#ca5426" })
hi(0, "lualine_y_fancy_filetype_ts_icon_normal", { bg = "#232435", fg = "#ca5426" })
hi(0, "lualine_y_fancy_filetype_ts_icon_replace", { bg = "#232435", fg = "#ca5426" })
hi(0, "lualine_y_fancy_filetype_ts_icon_terminal", { bg = "#232435", fg = "#ca5426" })
hi(0, "lualine_y_fancy_filetype_ts_icon_visual", { bg = "#232435", fg = "#ca5426" })
hi(0, "markdownBlockquote", {})
hi(0, "markdownBoldDelimiter", {})
hi(0, "markdownCode", {})
hi(0, "markdownCodeDelimiter", {})
hi(0, "markdownH1", { bg = "#535467", bold = true, fg = "#92d8be" })
hi(0, "markdownH1Delimiter", {})
hi(0, "markdownH2", { link = "rainbow2" })
hi(0, "markdownH2Delimiter", {})
hi(0, "markdownH3", { link = "rainbow3" })
hi(0, "markdownH3Delimiter", {})
hi(0, "markdownH4", { link = "rainbow4" })
hi(0, "markdownH4Delimiter", {})
hi(0, "markdownH5", { link = "rainbow5" })
hi(0, "markdownH5Delimiter", {})
hi(0, "markdownH6", { link = "rainbow6" })
hi(0, "markdownH6Delimiter", {})
hi(0, "markdownHeadingDelimiter", {})
hi(0, "markdownHeadingRule", {})
hi(0, "markdownId", {})
hi(0, "markdownIdDeclaration", {})
hi(0, "markdownItalic", {})
hi(0, "markdownItalicDelimiter", {})
hi(0, "markdownLinkText", {})
hi(0, "markdownListMarker", {})
hi(0, "markdownOrderedListMarker", {})
hi(0, "markdownRule", {})
hi(0, "markdownUrl", {})
hi(0, "markdownUrlDelimiter", {})
hi(0, "markdownUrlTitleDelimiter", {})
hi(0, "rainbow1", { fg = "#92d8be" })
hi(0, "rainbow2", { fg = "#f5b5a5" })
hi(0, "rainbow3", { fg = "#e3c18b" })
hi(0, "rainbow4", { fg = "#d1baf2" })
hi(0, "rainbow5", { fg = "#87d5e7" })
hi(0, "rainbow6", { fg = "#efb2cf" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#202131"
g.terminal_color_1 = "#92d8be"
g.terminal_color_2 = "#f5b5a5"
g.terminal_color_3 = "#e3c18b"
g.terminal_color_4 = "#d1baf2"
g.terminal_color_5 = "#87d5e7"
g.terminal_color_6 = "#efb2cf"
g.terminal_color_7 = "#c5c6cd"
g.terminal_color_8 = "#202131"
g.terminal_color_9 = "#92d8be"
g.terminal_color_10 = "#f5b5a5"
g.terminal_color_11 = "#e3c18b"
g.terminal_color_12 = "#d1baf2"
g.terminal_color_13 = "#87d5e7"
g.terminal_color_14 = "#efb2cf"
g.terminal_color_15 = "#c5c6cd"
