-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "tokyo-cat55"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@diff.delta", { link = "Changed" })
hi(0, "@diff.minus", { link = "Removed" })
hi(0, "@diff.plus", { link = "Added" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@keyword.return", { bold = true, fg = "#d1c98c" })
hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
hi(0, "@lsp.mod.deprecated", { fg = "#f6b2ba" })
hi(0, "@lsp.type.class", { link = "Structure" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@lsp.type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", {})
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.heading.1", { bg = "#505667", bold = true, fg = "#6ac0f3" })
hi(0, "@markup.heading.2", { bg = "#505667", bold = true, fg = "#6ac0f3" })
hi(0, "@markup.heading.3", { bg = "#505667", bold = true, fg = "#dc9cdd" })
hi(0, "@markup.heading.4", { bg = "#505667", bold = true, fg = "#a6d5a8" })
hi(0, "@markup.heading.5", { bg = "#505667", bold = true })
hi(0, "@markup.heading.6", { bg = "#505667", bold = true })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { fg = "#bdc1fa" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@structure", { link = "Structure" })
hi(0, "@symbol", { link = "Keyword" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@text.danger", { link = "ErrorMsg" })
hi(0, "@text.emphasis", { fg = "#a6d5a8", italic = true })
hi(0, "@text.literal", { link = "Comment" })
hi(0, "@text.note", { link = "MoreMsg" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#87d8d3" })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@variable", { fg = "#c3c7cd" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Beacon", { bg = "#eaecf3" })
hi(0, "Bold", { bold = true })
hi(0, "BufferCurrent", { bg = "#1d2231", bold = true, fg = "#a8c9fb" })
hi(0, "BufferCurrentIcon", { bg = "#1d2231" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#353b4c", bold = true, fg = "#a8c9fb" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#505667", bold = true, fg = "#a8c9fb" })
hi(0, "BufferInactive", { bg = "#111624", fg = "#c3c7cd" })
hi(0, "BufferInactiveIcon", { bg = "#111624" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#353b4c", fg = "#c3c7cd" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#505667", fg = "#c3c7cd" })
hi(0, "BufferLineBuffer", { fg = "#898d92" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#c3c7cd" })
hi(0, "BufferLineBufferVisible", { fg = "#c3c7cd" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#89d8ce", fg = "#1a2331" })
hi(0, "BufferLineTabSelected", { bg = "#89d8ce", bold = true, fg = "#1a2331" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#89d8ce", bold = true, fg = "#1a2331" })
hi(0, "BufferVisible", { bg = "#1d2231", bold = true, fg = "#c3c7cd" })
hi(0, "BufferVisibleIcon", { bg = "#1d2231" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#353b4c", bold = true, fg = "#c3c7cd" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#505667", bold = true, fg = "#c3c7cd" })
hi(0, "CccHighlighter002b27", { bg = "#002b27", fg = "#ffffff" })
hi(0, "CccHighlighter007a6d", { bg = "#007a6d", fg = "#ffffff" })
hi(0, "CccHighlighter031b1c", { bg = "#031b1c", fg = "#ffffff" })
hi(0, "CccHighlighter050714", { bg = "#050714", fg = "#ffffff" })
hi(0, "CccHighlighter0e1724", { bg = "#0e1724", fg = "#ffffff" })
hi(0, "CccHighlighter111624", { bg = "#111624", fg = "#ffffff" })
hi(0, "CccHighlighter141e48", { bg = "#141e48", fg = "#ffffff" })
hi(0, "CccHighlighter1a2331", { bg = "#1a2331", fg = "#ffffff" })
hi(0, "CccHighlighter1c2635", { bg = "#1c2635", fg = "#ffffff" })
hi(0, "CccHighlighter1d2231", { bg = "#1d2231", fg = "#ffffff" })
hi(0, "CccHighlighter1f2535", { bg = "#1f2535", fg = "#ffffff" })
hi(0, "CccHighlighter21242f", { bg = "#21242f", fg = "#ffffff" })
hi(0, "CccHighlighter213f1b", { bg = "#213f1b", fg = "#ffffff" })
hi(0, "CccHighlighter29758a", { bg = "#29758a", fg = "#ffffff" })
hi(0, "CccHighlighter333c4c", { bg = "#333c4c", fg = "#ffffff" })
hi(0, "CccHighlighter353b4c", { bg = "#353b4c", fg = "#ffffff" })
hi(0, "CccHighlighter381134", { bg = "#381134", fg = "#ffffff" })
hi(0, "CccHighlighter41942c", { bg = "#41942c", fg = "#ffffff" })
hi(0, "CccHighlighter4c5767", { bg = "#4c5767", fg = "#ffffff" })
hi(0, "CccHighlighter505667", { bg = "#505667", fg = "#ffffff" })
hi(0, "CccHighlighter536a54", { bg = "#536a54", fg = "#ffffff" })
hi(0, "CccHighlighter686446", { bg = "#686446", fg = "#ffffff" })
hi(0, "CccHighlighter7b595d", { bg = "#7b595d", fg = "#ffffff" })
hi(0, "CccHighlighter87d8d3", { bg = "#87d8d3", fg = "#000000" })
hi(0, "CccHighlighter898d92", { bg = "#898d92", fg = "#000000" })
hi(0, "CccHighlighter89d8ce", { bg = "#89d8ce", fg = "#000000" })
hi(0, "CccHighlighter8bd6d3", { bg = "#8bd6d3", fg = "#000000" })
hi(0, "CccHighlighter8fd4d4", { bg = "#8fd4d4", fg = "#000000" })
hi(0, "CccHighlighter90d1f1", { bg = "#90d1f1", fg = "#000000" })
hi(0, "CccHighlighter90d1f2", { bg = "#90d1f2", fg = "#000000" })
hi(0, "CccHighlighter93d3d5", { bg = "#93d3d5", fg = "#000000" })
hi(0, "CccHighlighter94cff4", { bg = "#94cff4", fg = "#000000" })
hi(0, "CccHighlighter94ede8", { bg = "#94ede8", fg = "#000000" })
hi(0, "CccHighlighter95ede2", { bg = "#95ede2", fg = "#000000" })
hi(0, "CccHighlighter97d1d5", { bg = "#97d1d5", fg = "#000000" })
hi(0, "CccHighlighter9b759a", { bg = "#9b759a", fg = "#000000" })
hi(0, "CccHighlighter9bd0d6", { bg = "#9bd0d6", fg = "#000000" })
hi(0, "CccHighlighter9dcce0", { bg = "#9dcce0", fg = "#000000" })
hi(0, "CccHighlighter9fced7", { bg = "#9fced7", fg = "#000000" })
hi(0, "CccHighlightera3cdd7", { bg = "#a3cdd7", fg = "#000000" })
hi(0, "CccHighlightera6aab0", { bg = "#a6aab0", fg = "#000000" })
hi(0, "CccHighlightera6d5a8", { bg = "#a6d5a8", fg = "#000000" })
hi(0, "CccHighlightera7aab0", { bg = "#a7aab0", fg = "#000000" })
hi(0, "CccHighlightera7cbd8", { bg = "#a7cbd8", fg = "#000000" })
hi(0, "CccHighlightera8c9fb", { bg = "#a8c9fb", fg = "#000000" })
hi(0, "CccHighlighteraad4a4", { bg = "#aad4a4", fg = "#000000" })
hi(0, "CccHighlighterabcad9", { bg = "#abcad9", fg = "#000000" })
hi(0, "CccHighlighterabd4a3", { bg = "#abd4a3", fg = "#000000" })
hi(0, "CccHighlighteracd4a4", { bg = "#acd4a4", fg = "#000000" })
hi(0, "CccHighlighterace3ff", { bg = "#ace3ff", fg = "#000000" })
hi(0, "CccHighlighterafc8d9", { bg = "#afc8d9", fg = "#000000" })
hi(0, "CccHighlighterafd49c", { bg = "#afd49c", fg = "#000000" })
hi(0, "CccHighlighterb2c5fb", { bg = "#b2c5fb", fg = "#000000" })
hi(0, "CccHighlighterb3c5fc", { bg = "#b3c5fc", fg = "#000000" })
hi(0, "CccHighlighterb3c7da", { bg = "#b3c7da", fg = "#000000" })
hi(0, "CccHighlighterb6d19c", { bg = "#b6d19c", fg = "#000000" })
hi(0, "CccHighlighterb6eab8", { bg = "#b6eab8", fg = "#000000" })
hi(0, "CccHighlighterb7c5db", { bg = "#b7c5db", fg = "#000000" })
hi(0, "CccHighlighterbae9b5", { bg = "#bae9b5", fg = "#000000" })
hi(0, "CccHighlighterbbc4dc", { bg = "#bbc4dc", fg = "#000000" })
hi(0, "CccHighlighterbdc1fa", { bg = "#bdc1fa", fg = "#000000" })
hi(0, "CccHighlighterbecf95", { bg = "#becf95", fg = "#000000" })
hi(0, "CccHighlighterbfc2dc", { bg = "#bfc2dc", fg = "#000000" })
hi(0, "CccHighlighterc0cf94", { bg = "#c0cf94", fg = "#000000" })
hi(0, "CccHighlighterc1c9c5", { bg = "#c1c9c5", fg = "#000000" })
hi(0, "CccHighlighterc3c1dd", { bg = "#c3c1dd", fg = "#000000" })
hi(0, "CccHighlighterc3c7cd", { bg = "#c3c7cd", fg = "#000000" })
hi(0, "CccHighlighterc4c7cd", { bg = "#c4c7cd", fg = "#000000" })
hi(0, "CccHighlighterc7bfde", { bg = "#c7bfde", fg = "#000000" })
hi(0, "CccHighlightercbbede", { bg = "#cbbede", fg = "#000000" })
hi(0, "CccHighlightercfbcdf", { bg = "#cfbcdf", fg = "#000000" })
hi(0, "CccHighlighterd1c98c", { bg = "#d1c98c", fg = "#000000" })
hi(0, "CccHighlighterd3bbe0", { bg = "#d3bbe0", fg = "#000000" })
hi(0, "CccHighlighterd5d9df", { bg = "#d5d9df", fg = "#000000" })
hi(0, "CccHighlighterd6d5ff", { bg = "#d6d5ff", fg = "#000000" })
hi(0, "CccHighlighterd6dae1", { bg = "#d6dae1", fg = "#000000" })
hi(0, "CccHighlighterd7b9e0", { bg = "#d7b9e0", fg = "#000000" })
hi(0, "CccHighlighterd7dae1", { bg = "#d7dae1", fg = "#000000" })
hi(0, "CccHighlighterd8ffdf", { bg = "#d8ffdf", fg = "#000000" })
hi(0, "CccHighlighterdbb8e1", { bg = "#dbb8e1", fg = "#000000" })
hi(0, "CccHighlighterdfb6e2", { bg = "#dfb6e2", fg = "#000000" })
hi(0, "CccHighlightere3b5e3", { bg = "#e3b5e3", fg = "#000000" })
hi(0, "CccHighlightere5dd9a", { bg = "#e5dd9a", fg = "#000000" })
hi(0, "CccHighlightere6b5df", { bg = "#e6b5df", fg = "#000000" })
hi(0, "CccHighlightere8edf3", { bg = "#e8edf3", fg = "#000000" })
hi(0, "CccHighlightereaecf3", { bg = "#eaecf3", fg = "#000000" })
hi(0, "CccHighlightered10a0", { bg = "#ed10a0", fg = "#ffffff" })
hi(0, "CccHighlighterf0ba94", { bg = "#f0ba94", fg = "#000000" })
hi(0, "CccHighlighterf5b2bf", { bg = "#f5b2bf", fg = "#000000" })
hi(0, "CccHighlighterf6b2ba", { bg = "#f6b2ba", fg = "#000000" })
hi(0, "CccHighlighterf7b2b5", { bg = "#f7b2b5", fg = "#000000" })
hi(0, "CccHighlighterf9c7f9", { bg = "#f9c7f9", fg = "#000000" })
hi(0, "CccHighlighterff0000", { bg = "#ff0000", fg = "#ffffff" })
hi(0, "CccHighlighterffffff", { bg = "#ffffff", fg = "#000000" })
hi(0, "CmpItemAbbr", { fg = "#c3c7cd" })
hi(0, "CmpItemAbbrDefault", { fg = "#c3c7cd" })
hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#898d92" })
hi(0, "CmpItemAbbrMatch", { bold = true })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c3c7cd" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c3c7cd" })
hi(0, "CmpItemKind", { fg = "#c3c7cd" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#87d8d3" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "Normal" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#c3c7cd" })
hi(0, "CmpItemMenuDefault", { fg = "#c3c7cd" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocErrorFloat", { link = "DiagnosticFloatingError" })
hi(0, "CocErrorHighlight", { link = "DiagnosticError" })
hi(0, "CocErrorSign", { link = "DiagnosticSignError" })
hi(0, "CocHintFloat", { link = "DiagnosticFloatingHint" })
hi(0, "CocHintHighlight", { link = "DiagnosticHint" })
hi(0, "CocHintSign", { link = "DiagnosticSignHint" })
hi(0, "CocInfoFloat", { link = "DiagnosticFloatingInfo" })
hi(0, "CocInfoHighlight", { link = "DiagnosticInfo" })
hi(0, "CocInfoSign", { link = "DiagnosticSignInfo" })
hi(0, "CocMarkdownLink", { fg = "#bdc1fa" })
hi(0, "CocMenuSel", { bg = "#505667" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#bdc1fa" })
hi(0, "CocSelectedText", { fg = "#d1c98c" })
hi(0, "CocWarningFloat", { link = "DiagnosticFloatingWarn" })
hi(0, "CocWarningHighlight", { link = "DiagnosticWarn" })
hi(0, "CocWarningSign", { link = "DiagnosticSignWarn" })
hi(0, "ColorColumn", { bg = "#505667" })
hi(0, "Comment", { fg = "#898d92" })
hi(0, "Conceal", { fg = "#94cff4" })
hi(0, "Constant", { fg = "#e3b5e3" })
hi(0, "CurSearch", { bg = "#e3b5e3", fg = "#1a2331" })
hi(0, "Cursor", { bg = "#c4c7cd", fg = "#1a2331" })
hi(0, "CursorColumn", { bg = "#353b4c" })
hi(0, "CursorLine", { bg = "#353b4c" })
hi(0, "CursorLineFold", { fg = "#4c5767" })
hi(0, "CursorLineNr", { bold = true, fg = "#a8c9fb" })
hi(0, "CursorLineSign", { fg = "#4c5767" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#a6d5a8" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#f0ba94" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Comment" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "WarningMsg" })
hi(0, "Definitions", { fg = "#a6d5a8" })
hi(0, "DefinitionsIcon", { fg = "#94cff4" })
hi(0, "Delimiter", { fg = "#f0ba94" })
hi(0, "DiagnosticDeprecated", { sp = "#f6b2ba", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#f6b2ba" })
hi(0, "DiagnosticFloatingError", { bg = "#111624", fg = "#f6b2ba" })
hi(0, "DiagnosticFloatingHint", { bg = "#111624", fg = "#87d8d3" })
hi(0, "DiagnosticFloatingInfo", { bg = "#111624", fg = "#bdc1fa" })
hi(0, "DiagnosticFloatingOk", { bg = "#111624", fg = "#a6d5a8" })
hi(0, "DiagnosticFloatingWarn", { bg = "#111624", fg = "#d1c98c" })
hi(0, "DiagnosticHint", { fg = "#87d8d3" })
hi(0, "DiagnosticInfo", { fg = "#bdc1fa" })
hi(0, "DiagnosticOk", { fg = "#a6d5a8" })
hi(0, "DiagnosticUnderlineError", { sp = "#f6b2ba", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#87d8d3", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#bdc1fa", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#a6d5a8", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#d1c98c", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#3e0615", fg = "#f6b2ba" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#264644", fg = "#87d8d3" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#1c035d", fg = "#bdc1fa" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#212012", fg = "#d1c98c" })
hi(0, "DiagnosticWarn", { fg = "#d1c98c" })
hi(0, "DiffAdd", { bg = "#002b27" })
hi(0, "DiffAdded", { link = "DiffAdd" })
hi(0, "DiffChange", { bg = "#213f1b" })
hi(0, "DiffDelete", { bg = "#381134" })
hi(0, "DiffFile", { bg = "#213f1b" })
hi(0, "DiffRemoved", { link = "DiffFile" })
hi(0, "DiffText", { bg = "#505667" })
hi(0, "Directory", { fg = "#94cff4" })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "EndOfBuffer", { fg = "#4c5767" })
hi(0, "Error", { bg = "#381134" })
hi(0, "ErrorMsg", { fg = "#f6b2ba" })
hi(0, "FinderParam", { fg = "#d1c98c" })
hi(0, "FinderSpinner", { fg = "#a6d5a8" })
hi(0, "FinderSpinnerBorder", { fg = "#a8c9fb" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#f0ba94" })
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { bg = "#111624", fg = "#a8c9fb" })
hi(0, "FloatTitle", { bg = "#111624", bold = true, fg = "#a8c9fb" })
hi(0, "FoldColumn", { fg = "#4c5767" })
hi(0, "Folded", { bg = "#353b4c", fg = "#898d92" })
hi(0, "Function", { fg = "#94cff4" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#98f5ff" })
hi(0, "FzfLuaBufFlagCur", { fg = "#ff4040" })
hi(0, "FzfLuaBufName", { fg = "#ffbbff" })
hi(0, "FzfLuaBufNr", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderBind", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderText", { fg = "#ff4040" })
hi(0, "FzfLuaLiveSym", { fg = "#ff4040" })
hi(0, "FzfLuaPathColNr", { fg = "#98f5ff" })
hi(0, "FzfLuaPathLineNr", { fg = "#90ee90" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#ffebcd" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#b0e2ff" })
hi(0, "GitSignsAdd", { fg = "#a6d5a8" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { fg = "#d1c98c" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { fg = "#f6b2ba" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsStagedAdd", { fg = "#536a54" })
hi(0, "GitSignsStagedAddLn", { fg = "#536a54" })
hi(0, "GitSignsStagedAddNr", { fg = "#536a54" })
hi(0, "GitSignsStagedChange", { fg = "#686446" })
hi(0, "GitSignsStagedChangeLn", { fg = "#686446" })
hi(0, "GitSignsStagedChangeNr", { fg = "#686446" })
hi(0, "GitSignsStagedChangedelete", { fg = "#686446" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#686446" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#686446" })
hi(0, "GitSignsStagedDelete", { fg = "#7b595d" })
hi(0, "GitSignsStagedDeleteLn", { fg = "#7b595d" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7b595d" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7b595d" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7b595d" })
hi(0, "GitSignsUntracked", { fg = "#94cff4" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HeaderGradient1", { fg = "#8ad6d3" })
hi(0, "HeaderGradient10", { fg = "#a6cbd8" })
hi(0, "HeaderGradient11", { fg = "#a9cad9" })
hi(0, "HeaderGradient12", { fg = "#adc9d9" })
hi(0, "HeaderGradient13", { fg = "#b0c8da" })
hi(0, "HeaderGradient14", { fg = "#b3c7da" })
hi(0, "HeaderGradient15", { fg = "#b6c5db" })
hi(0, "HeaderGradient16", { fg = "#b9c4db" })
hi(0, "HeaderGradient17", { fg = "#bcc3dc" })
hi(0, "HeaderGradient18", { fg = "#c0c2dc" })
hi(0, "HeaderGradient19", { fg = "#c3c1dd" })
hi(0, "HeaderGradient2", { fg = "#8dd5d4" })
hi(0, "HeaderGradient20", { fg = "#c6bfde" })
hi(0, "HeaderGradient21", { fg = "#c9bede" })
hi(0, "HeaderGradient22", { fg = "#ccbddf" })
hi(0, "HeaderGradient23", { fg = "#cfbcdf" })
hi(0, "HeaderGradient24", { fg = "#d3bbe0" })
hi(0, "HeaderGradient25", { fg = "#d6b9e0" })
hi(0, "HeaderGradient26", { fg = "#d9b8e1" })
hi(0, "HeaderGradient27", { fg = "#dcb7e1" })
hi(0, "HeaderGradient28", { fg = "#dfb6e2" })
hi(0, "HeaderGradient29", { fg = "#e3b5e3" })
hi(0, "HeaderGradient3", { fg = "#90d4d4" })
hi(0, "HeaderGradient4", { fg = "#93d3d5" })
hi(0, "HeaderGradient5", { fg = "#96d1d5" })
hi(0, "HeaderGradient6", { fg = "#9ad0d6" })
hi(0, "HeaderGradient7", { fg = "#9dcfd6" })
hi(0, "HeaderGradient8", { fg = "#a0ced7" })
hi(0, "HeaderGradient9", { fg = "#a3cdd7" })
hi(0, "HopNextKey", { bold = true, fg = "#a6d5a8", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#f0ba94", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#a6aab0", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#d1c98c", nocombine = true })
hi(0, "HopUnmatched", { fg = "#4c5767" })
hi(0, "HydraAmaranth", { fg = "#e3b5e3" })
hi(0, "HydraBlue", { fg = "#94cff4" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#f0ba94" })
hi(0, "HydraRed", { fg = "#f6b2ba" })
hi(0, "HydraTeal", { fg = "#87d8d3" })
hi(0, "Identifier", { fg = "#f0ba94" })
hi(0, "Ignore", {})
hi(0, "IncSearch", { bg = "#a6d5a8", fg = "#1a2331" })
hi(0, "IndentBlanklineChar", { fg = "#4c5767", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#a8c9fb", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#a8c9fb", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#bdc1fa", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#87d8d3", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#d1c98c", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#f6b2ba", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#94cff4", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#a6d5a8", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#f0ba94", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#e3b5e3", nocombine = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#4c5767", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#4c5767", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "LSOutlinePreviewBorder", { fg = "#a8c9fb" })
hi(0, "LazyButton", { bg = "#353b4c" })
hi(0, "LazyButtonActive", { bg = "#505667" })
hi(0, "LazyComment", { fg = "#898d92" })
hi(0, "LazyCommit", { fg = "#87d8d3" })
hi(0, "LazyCommitIssue", { fg = "#e3b5e3" })
hi(0, "LazyCommitScope", { italic = true })
hi(0, "LazyCommitType", { fg = "#a8c9fb" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyDir", { fg = "#d1c98c" })
hi(0, "LazyH1", { bg = "#505667", bold = true, fg = "#a8c9fb" })
hi(0, "LazyH2", { bold = true })
hi(0, "LazyLocal", { fg = "#e3b5e3" })
hi(0, "LazyNoCond", { fg = "#d1c98c" })
hi(0, "LazyNormal", { bg = "#111624", fg = "#c3c7cd" })
hi(0, "LazyProgressDone", { fg = "#e3b5e3" })
hi(0, "LazyProgressTodo", { fg = "#4c5767" })
hi(0, "LazyProp", { fg = "#94cff4" })
hi(0, "LazyReasonCmd", { fg = "#c3c7cd" })
hi(0, "LazyReasonEvent", { fg = "#e3b5e3" })
hi(0, "LazyReasonFt", { fg = "#e3b5e3" })
hi(0, "LazyReasonImport", { fg = "#d1c98c" })
hi(0, "LazyReasonKeys", { bold = true })
hi(0, "LazyReasonPlugin", { fg = "#87d8d3" })
hi(0, "LazyReasonRuntime", { fg = "#bdc1fa" })
hi(0, "LazyReasonSource", { fg = "#e3b5e3" })
hi(0, "LazyReasonStart", { fg = "#d1c98c" })
hi(0, "LazySpecial", { fg = "#f0ba94" })
hi(0, "LazyTaskError", { fg = "#f6b2ba" })
hi(0, "LazyTaskOutput", { bg = "#1d2231", fg = "#c3c7cd" })
hi(0, "LazyUrl", { fg = "#d1c98c" })
hi(0, "LazyValue", { fg = "#a6d5a8" })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabelPrimary", { bold = true, fg = "#d1c98c", nocombine = true })
hi(0, "LeapLabelSecondary", { bold = true, fg = "#c3c7cd", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#87d8d3", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#a6d5a8", nocombine = true })
hi(0, "LineNr", { fg = "#4c5767" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceText", { bg = "#505667" })
hi(0, "LspSagaAutoPreview", { fg = "#bdc1fa" })
hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
hi(0, "LspSagaCodeActionBorder", { fg = "#a8c9fb" })
hi(0, "LspSagaCodeActionContent", { fg = "#c3c7cd" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#94cff4" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#a8c9fb" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#a8c9fb" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#f0ba94" })
hi(0, "LspSagaFinderSelection", { fg = "#87d8d3" })
hi(0, "LspSagaHoverBorder", { fg = "#a8c9fb" })
hi(0, "LspSagaLspFinderBorder", { fg = "#a8c9fb" })
hi(0, "LspSagaRenameBorder", { fg = "#a8c9fb" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#a8c9fb" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "MasonError", { fg = "#f6b2ba" })
hi(0, "MasonHeader", { bg = "#b2c5fb", bold = true, fg = "#1a2331" })
hi(0, "MasonHeaderSecondary", { bg = "#b2c5fb", bold = true, fg = "#1a2331" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#a8c9fb" })
hi(0, "MasonHighlightBlock", { bg = "#b3c5fc", fg = "#1a2331" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#b2c5fb", fg = "#1a2331" })
hi(0, "MasonHighlightSecondary", { fg = "#94cff4" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#505667", fg = "#1a2331" })
hi(0, "MasonMutedBlockBold", { bg = "#505667", bold = true, fg = "#1a2331" })
hi(0, "MatchParen", { bg = "#bde6bf", fg = "#1a2331" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { bg = "#505667" })
hi(0, "MiniCursorword", { bg = "#505667" })
hi(0, "MiniCursorwordCurrent", { bg = "#505667", underline = true })
hi(0, "MiniFilesFile", { fg = "#c3c7cd" })
hi(0, "MiniFilesTitleFocused", { bg = "#111624", bold = true, fg = "#c3c7cd" })
hi(0, "MiniHipatternsFixme", { bg = "#e6b5df", bold = true, fg = "#1a2331" })
hi(0, "MiniHipatternsHack", { bg = "#aad4a4", bold = true, fg = "#1a2331" })
hi(0, "MiniHipatternsNote", { bg = "#90d1f2", bold = true, fg = "#1a2331" })
hi(0, "MiniHipatternsTodo", { bg = "#b2c5fb", bold = true, fg = "#1a2331" })
hi(0, "MiniIndentscopeSymbol", { fg = "#a8c9fb" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#f6b2ba" })
hi(0, "MiniJump", { sp = "#a8c9fb", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#4c5767" })
hi(0, "MiniJump2dSpot", { bg = "#050714", bold = true, fg = "#e8edf3", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#050714", fg = "#d5d9df", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#111624", fg = "#898d92" })
hi(0, "MiniMapSymbolCount", { fg = "#898d92" })
hi(0, "MiniMapSymbolLine", { fg = "#a8c9fb" })
hi(0, "MiniMapSymbolView", { fg = "#a8c9fb" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniStarterCurrent", { link = "MiniStarterItem" })
hi(0, "MiniStarterFooter", { link = "Comment" })
hi(0, "MiniStarterHeader", { bold = true, fg = "#a8c9fb" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItemBullet", { fg = "#898d92" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#d1c98c" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#a6d5a8" })
hi(0, "MiniStarterSection", { fg = "#e3b5e3" })
hi(0, "MiniStatuslineDevinfo", { bg = "#353b4c", fg = "#a6aab0" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { link = "Normal" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { bg = "#aad4a4", bold = true, fg = "#1a2331" })
hi(0, "MiniStatuslineModeInsert", { bg = "#e6b5df", bold = true, fg = "#1a2331" })
hi(0, "MiniStatuslineModeNormal", { bg = "#b2c5fb", bold = true, fg = "#1a2331" })
hi(0, "MiniStatuslineModeOther", { bg = "#90d1f2", bold = true, fg = "#1a2331" })
hi(0, "MiniStatuslineModeReplace", { bg = "#f6b2ba", bold = true, fg = "#1a2331" })
hi(0, "MiniStatuslineModeVisual", { bg = "#89d8ce", bold = true, fg = "#1a2331" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#1d2231", bold = true, fg = "#a8c9fb" })
hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
hi(0, "MiniTablineHidden", { bg = "#111624", fg = "#a6aab0" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#b3c5fc", bold = true, fg = "#1a2331" })
hi(0, "MiniTablineModifiedHidden", { bg = "#a7aab0", fg = "#0e1724" })
hi(0, "MiniTablineModifiedVisible", { bg = "#a7aab0", bold = true, fg = "#0e1724" })
hi(0, "MiniTablineTabpagesection", { bg = "#89d8ce", bold = true, fg = "#1a2331" })
hi(0, "MiniTablineVisible", { bg = "#111624", bold = true, fg = "#a6aab0" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#f6b2ba" })
hi(0, "MiniTestPass", { bold = true, fg = "#a6d5a8" })
hi(0, "MiniTrailspace", { bg = "#381134" })
hi(0, "ModeMsg", { fg = "#a6d5a8" })
hi(0, "MoreMsg", { fg = "#94cff4" })
hi(0, "MsgArea", { link = "Normal" })
hi(0, "MsgSeparator", { bg = "#505667", fg = "#898d92" })
hi(0, "NeoTreeDimText", { fg = "#4c5767" })
hi(0, "NeoTreeDotfile", { fg = "#a6aab0" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#4c5767" })
hi(0, "NeoTreeGitAdded", { fg = "#a6d5a8" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#f0ba94" })
hi(0, "NeoTreeGitDeleted", { fg = "#f6b2ba" })
hi(0, "NeoTreeGitModified", { fg = "#d1c98c" })
hi(0, "NeoTreeGitUnstaged", { fg = "#e3b5e3" })
hi(0, "NeoTreeGitUntracked", { fg = "#87d8d3" })
hi(0, "NeoTreeMessage", { bg = "#353b4c", fg = "#c3c7cd" })
hi(0, "NeoTreeModified", { fg = "#d5d9df" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#a8c9fb" })
hi(0, "NeoTreeTabInactive", { fg = "#898d92" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#505667", fg = "#898d92" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#353b4c", fg = "#333c4c" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#a8c9fb" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#a8c9fb" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceAttr1138", { bg = "#29758a", fg = "#ffffff" })
hi(0, "NoiceAttr1826", { fg = "#c0cf94" })
hi(0, "NoiceAttr1827", { bg = "#9b759a", bold = true, fg = "#21242f" })
hi(0, "NoiceAttr2048", { fg = "#b6d19c" })
hi(0, "NoiceAttr2226", { fg = "#acd4a4" })
hi(0, "NoiceAttr2659", { fg = "#becf95" })
hi(0, "NoiceAttr294", { fg = "#90d1f1" })
hi(0, "NoiceAttr303", { fg = "#f5b2bf" })
hi(0, "NoiceAttr308", { fg = "#abd4a3" })
hi(0, "NoiceAttr311", { bg = "#031b1c", fg = "#c1c9c5" })
hi(0, "NoiceAttr3156", { fg = "#afd49c" })
hi(0, "NoiceAttr55", { fg = "#f6b2ba" })
hi(0, "NoiceAttr726", { fg = "#9dcce0" })
hi(0, "NoiceCmdline", { bg = "#1d2231", fg = "#c3c7cd" })
hi(0, "NoiceCmdlineIcon", { fg = "#bdc1fa" })
hi(0, "NoiceCmdlineIconCalculator", { fg = "#bdc1fa" })
hi(0, "NoiceCmdlineIconCmdline", { fg = "#bdc1fa" })
hi(0, "NoiceCmdlineIconFilter", { fg = "#bdc1fa" })
hi(0, "NoiceCmdlineIconHelp", { fg = "#bdc1fa" })
hi(0, "NoiceCmdlineIconInput", { fg = "#bdc1fa" })
hi(0, "NoiceCmdlineIconLua", { fg = "#bdc1fa" })
hi(0, "NoiceCmdlineIconSearch", { fg = "#d1c98c" })
hi(0, "NoiceCmdlinePopup", { bg = "#1d2231", fg = "#c3c7cd" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#94cff4" })
hi(0, "NoiceCmdlinePopupBorderCalculator", { fg = "#94cff4" })
hi(0, "NoiceCmdlinePopupBorderCmdline", { fg = "#94cff4" })
hi(0, "NoiceCmdlinePopupBorderFilter", { fg = "#94cff4" })
hi(0, "NoiceCmdlinePopupBorderHelp", { fg = "#94cff4" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#94cff4" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#94cff4" })
hi(0, "NoiceCmdlinePopupBorderSearch", { fg = "#d1c98c" })
hi(0, "NoiceCmdlinePopupTitle", { fg = "#bdc1fa" })
hi(0, "NoiceCmdlinePrompt", { fg = "#a8c9fb" })
hi(0, "NoiceCompletionItemKindClass", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindColor", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindConstant", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindConstructor", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindEnum", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindEnumMember", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindField", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindFile", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindFolder", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindFunction", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindInterface", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindKeyword", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindMethod", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindModule", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindProperty", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindSnippet", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindStruct", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindText", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindUnit", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindValue", { fg = "#87d8d3" })
hi(0, "NoiceCompletionItemKindVariable", { fg = "#87d8d3" })
hi(0, "NoiceConfirm", { bg = "#1d2231", fg = "#c3c7cd" })
hi(0, "NoiceConfirmBorder", { fg = "#d1c98c" })
hi(0, "NoiceCursor", { bg = "#c4c7cd", fg = "#1a2331" })
hi(0, "NoiceFormatConfirm", { bg = "#353b4c" })
hi(0, "NoiceFormatConfirmDefault", { bg = "#505667" })
hi(0, "NoiceFormatDate", { fg = "#87d8d3" })
hi(0, "NoiceFormatEvent", { fg = "#4c5767" })
hi(0, "NoiceFormatKind", { fg = "#4c5767" })
hi(0, "NoiceFormatLevelDebug", { fg = "#4c5767" })
hi(0, "NoiceFormatLevelError", { fg = "#f6b2ba" })
hi(0, "NoiceFormatLevelInfo", { fg = "#bdc1fa" })
hi(0, "NoiceFormatLevelOff", { fg = "#4c5767" })
hi(0, "NoiceFormatLevelTrace", { fg = "#4c5767" })
hi(0, "NoiceFormatLevelWarn", { fg = "#d1c98c" })
hi(0, "NoiceFormatProgressDone", { bg = "#b3c5fc", fg = "#1a2331" })
hi(0, "NoiceFormatProgressTodo", { bg = "#353b4c" })
hi(0, "NoiceFormatTitle", { fg = "#a8c9fb" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NoiceLspProgressClient", { fg = "#a8c9fb" })
hi(0, "NoiceLspProgressSpinner", { fg = "#e3b5e3" })
hi(0, "NoiceLspProgressTitle", { fg = "#4c5767" })
hi(0, "NoiceMini", { bg = "#1d2231", fg = "#c3c7cd" })
hi(0, "NoicePopup", { bg = "#111624", fg = "#c3c7cd" })
hi(0, "NoicePopupBorder", { bg = "#111624", fg = "#a8c9fb" })
hi(0, "NoicePopupmenu", { bg = "#353b4c", fg = "#c3c7cd" })
hi(0, "NoicePopupmenuBorder", { bg = "#111624", fg = "#a8c9fb" })
hi(0, "NoicePopupmenuMatch", { fg = "#87d8d3" })
hi(0, "NoicePopupmenuSelected", { bg = "#c4c7cd", blend = 0, fg = "#1a2331" })
hi(0, "NoiceScrollbar", { bg = "#353b4c", fg = "#c3c7cd" })
hi(0, "NoiceScrollbarThumb", { bg = "#505667" })
hi(0, "NoiceSplit", { bg = "#111624", fg = "#c3c7cd" })
hi(0, "NoiceSplitBorder", { bg = "#111624", fg = "#a8c9fb" })
hi(0, "NoiceVirtualText", { bg = "#264644", fg = "#87d8d3" })
hi(0, "NonText", { fg = "#4c5767" })
hi(0, "Normal", { bg = "#1d2231", fg = "#c3c7cd" })
hi(0, "NormalFloat", { bg = "#111624", fg = "#c3c7cd" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#a6d5a8" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBody317", { bg = "#1d2231", fg = "#242937" })
hi(0, "NotifyERRORBody318", { bg = "#1d2231", fg = "#242937" })
hi(0, "NotifyERRORBody529", { bg = "#1d2231", fg = "#c3c7cd" })
hi(0, "NotifyERRORBorder", { fg = "#f6b2ba" })
hi(0, "NotifyERRORBorder317", { fg = "#262836" })
hi(0, "NotifyERRORBorder318", { fg = "#262836" })
hi(0, "NotifyERRORBorder529", { fg = "#f6b2ba" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORIcon317", { fg = "#262836" })
hi(0, "NotifyERRORIcon318", { fg = "#262836" })
hi(0, "NotifyERRORIcon529", { fg = "#f6b2ba" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle317", { fg = "#262836" })
hi(0, "NotifyERRORTitle318", { fg = "#262836" })
hi(0, "NotifyERRORTitle529", { fg = "#f6b2ba" })
hi(0, "NotifyINFOBody14", { bg = "#1d2231", fg = "#242937" })
hi(0, "NotifyINFOBody154", { bg = "#1d2231", fg = "#242937" })
hi(0, "NotifyINFOBody316", { bg = "#1d2231", fg = "#242937" })
hi(0, "NotifyINFOBorder", { fg = "#bdc1fa" })
hi(0, "NotifyINFOBorder14", { fg = "#232839" })
hi(0, "NotifyINFOBorder154", { fg = "#232839" })
hi(0, "NotifyINFOBorder316", { fg = "#232839" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOIcon14", { fg = "#232839" })
hi(0, "NotifyINFOIcon154", { fg = "#232839" })
hi(0, "NotifyINFOIcon316", { fg = "#232839" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle14", { fg = "#232839" })
hi(0, "NotifyINFOTitle154", { fg = "#232839" })
hi(0, "NotifyINFOTitle316", { fg = "#232839" })
hi(0, "NotifyTRACEBorder", { fg = "#87d8d3" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#d1c98c" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "NvimInternalError", { bg = "#ed10a0", ctermbg = 9, ctermfg = 9, fg = "#ff0000" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#a6d5a8" })
hi(0, "NvimTreeFolderIcon", { fg = "#898d92" })
hi(0, "NvimTreeGitDeleted", { fg = "#f6b2ba" })
hi(0, "NvimTreeGitDirty", { fg = "#d1c98c" })
hi(0, "NvimTreeGitMerge", { fg = "#f0ba94" })
hi(0, "NvimTreeGitNew", { fg = "#87d8d3" })
hi(0, "NvimTreeGitRenamed", { fg = "#e3b5e3" })
hi(0, "NvimTreeGitStaged", { fg = "#a6d5a8" })
hi(0, "NvimTreeImageFile", { fg = "#f0ba94" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#a8c9fb" })
hi(0, "NvimTreeSpecialFile", { fg = "#a8c9fb", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#bdc1fa" })
hi(0, "NvimTreeWindowPicker", { bg = "#505667", bold = true, fg = "#c3c7cd" })
hi(0, "Operator", { fg = "#c3c7cd" })
hi(0, "OutlineDetail", { fg = "#4c5767" })
hi(0, "OutlineFoldPrefix", { fg = "#d1c98c" })
hi(0, "OutlineIndentEvn", { fg = "#898d92" })
hi(0, "OutlineIndentOdd", { fg = "#c3c7cd" })
hi(0, "Pmenu", { bg = "#353b4c", fg = "#c3c7cd" })
hi(0, "PmenuSel", { bg = "#c4c7cd", blend = 0, fg = "#1a2331" })
hi(0, "PmenuThumb", { bg = "#505667" })
hi(0, "PounceAccept", { bg = "#aad4a4", bold = true, fg = "#1a2331", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#89d8ce", bold = true, fg = "#1a2331", nocombine = true })
hi(0, "PounceGap", { bg = "#505667", bold = true, fg = "#1a2331", nocombine = true })
hi(0, "PounceMatch", { bg = "#c4c7cd", bold = true, fg = "#1a2331", nocombine = true })
hi(0, "PreProc", { fg = "#bdc1fa" })
hi(0, "Question", { fg = "#94cff4" })
hi(0, "QuickFixLine", { bg = "#353b4c" })
hi(0, "RainbowDelimiterBlue", { fg = "#94cff4" })
hi(0, "RainbowDelimiterCyan", { fg = "#87d8d3" })
hi(0, "RainbowDelimiterGreen", { fg = "#a6d5a8" })
hi(0, "RainbowDelimiterOrange", { fg = "#f0ba94" })
hi(0, "RainbowDelimiterRed", { fg = "#f6b2ba" })
hi(0, "RainbowDelimiterViolet", { fg = "#e3b5e3" })
hi(0, "RainbowDelimiterYellow", { fg = "#d1c98c" })
hi(0, "RedrawDebugClear", { bg = "#d8ffdf", ctermbg = 11 })
hi(0, "RedrawDebugComposed", { bg = "#007a6d", ctermbg = 10 })
hi(0, "RedrawDebugRecompose", { bg = "#ed10a0", ctermbg = 9 })
hi(0, "References", { fg = "#a6d5a8" })
hi(0, "ReferencesIcon", { fg = "#94cff4" })
hi(0, "Search", { bg = "#a8c9fb", fg = "#1a2331" })
hi(0, "SignColumn", { fg = "#4c5767" })
hi(0, "Sneak", { bg = "#f7b2b5", fg = "#1a2331" })
hi(0, "SneakLabel", { bg = "#f7b2b5", bold = true, fg = "#1a2331" })
hi(0, "SneakScope", { bg = "#eaecf3", fg = "#1a2331" })
hi(0, "Special", { fg = "#87d8d3" })
hi(0, "SpecialKey", { fg = "#4c5767" })
hi(0, "SpellBad", { sp = "#f6b2ba", undercurl = true })
hi(0, "SpellCap", { sp = "#87d8d3", undercurl = true })
hi(0, "SpellLocal", { sp = "#d1c98c", undercurl = true })
hi(0, "SpellRare", { sp = "#bdc1fa", undercurl = true })
hi(0, "Statement", { fg = "#f6b2ba" })
hi(0, "StatusLine", { bg = "#1d2231", fg = "#a6aab0" })
hi(0, "StatusLineNC", { bg = "#111624", fg = "#a6aab0" })
hi(0, "String", { fg = "#a6d5a8" })
hi(0, "Substitute", { bg = "#f0ba94", bold = true, fg = "#1a2331", underline = true })
hi(0, "TabLine", { bg = "#111624", fg = "#a6aab0" })
hi(0, "TabLineSel", { bg = "#111624", fg = "#a8c9fb" })
hi(0, "TargetFileName", { fg = "#c3c7cd" })
hi(0, "TelescopeBorder", { bg = "#111624", fg = "#a8c9fb" })
hi(0, "TelescopeMatching", { bold = true })
hi(0, "TelescopeMultiSelection", { bg = "#505667" })
hi(0, "TelescopeNormal", { link = "NormalFloat" })
hi(0, "TelescopePromptNormal", { link = "NormalFloat" })
hi(0, "TelescopeSelection", { bg = "#353b4c" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { fg = "#a8c9fb" })
hi(0, "Todo", { bg = "#1d2231", bold = true, fg = "#a8c9fb" })
hi(0, "TroubleCount", { bold = true, fg = "#a8c9fb" })
hi(0, "TroubleFoldIcon", { bold = true, fg = "#a8c9fb" })
hi(0, "TroubleIndent", { fg = "#4c5767" })
hi(0, "TroubleLocation", { fg = "#a6aab0" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#c3c7cd" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#c3c7cd" })
hi(0, "VertSplit", { fg = "#a8c9fb" })
hi(0, "Visual", { bg = "#505667" })
hi(0, "VisualNOS", { bg = "#353b4c" })
hi(0, "WarningMsg", { fg = "#d1c98c" })
hi(0, "WhichKey", { fg = "#87d8d3" })
hi(0, "WhichKeyDesc", { fg = "#c3c7cd" })
hi(0, "WhichKeyFloat", { bg = "#111624", fg = "#c3c7cd" })
hi(0, "WhichKeyGroup", { fg = "#f6b2ba" })
hi(0, "WhichKeySeparator", { fg = "#a6d5a8" })
hi(0, "Whitespace", { fg = "#4c5767" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { fg = "#a8c9fb" })
hi(0, "bg_.bg1_fg_.bg1_", { bg = "#2f3442", fg = "#2f3442" })
hi(0, "bg_.bg1_fg_a6aab0_", { bg = "#2f3442", fg = "#a6aab0" })
hi(0, "bg_.bg2_fg_.bg2_", { bg = "#414653", fg = "#414653" })
hi(0, "bg_.bg2_fg_.blue_", { bg = "#414653", fg = "#6ac0f3" })
hi(0, "bg_.bg2_fg_a6aab0_", { bg = "#414653", fg = "#a6aab0" })
hi(0, "bg_.blue_fg_.bg_", { bg = "#6ac0f3", fg = "#1d2231" })
hi(0, "bg_.blue_fg_.blue_", { bg = "#6ac0f3", fg = "#6ac0f3" })
hi(0, "bg_.cyan_fg_1d2231_", { bg = "#98ebe6", fg = "#1d2231" })
hi(0, "bg_.green_fg_1d2231_", { bg = "#bde6bf", fg = "#1d2231" })
hi(0, "bg_1d2231_fg_1d2231_", { bg = "#1d2231", fg = "#1d2231" })
hi(0, "bg_1d2231_fg_a6aab0_", { bg = "#1d2231", fg = "#a6aab0" })
hi(0, "bg_a6aab0_fg_1d2231_", { bg = "#a6aab0", fg = "#1d2231" })
hi(0, "diffLine", { bg = "#141e48" })
hi(0, "diffNewFile", { link = "DiffAdded" })
hi(0, "gitcommitBranch", { bold = true, fg = "#f0ba94" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#d1c98c" })
hi(0, "gitcommitDiscardedType", { fg = "#94cff4" })
hi(0, "gitcommitHeader", { link = "Title" })
hi(0, "gitcommitOverflow", { fg = "#d1c98c" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#a6d5a8" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#a6d5a8" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#87d8d3" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlBoldItalic", { bold = true, italic = true })
hi(0, "incline__gui_bold", { bold = true })
hi(0, "incline__gui_bolditalic", { bold = true, italic = true })
hi(0, "incline__guibg_353b4c", { bg = "#353b4c" })
hi(0, "incline__guibg_51a0cf__guifg_000000", { bg = "#51a0cf", fg = "#000000" })
hi(0, "incline__guibg_dddddd__guifg_000000", { bg = "#dddddd", fg = "#000000" })
hi(0, "lCursor", { bg = "#c4c7cd", fg = "#1a2331" })
hi(0, "lualine_a_command", { bg = "#bae9b5", bold = true, fg = "#1c2635" })
hi(0, "lualine_a_inactive", { bg = "#d7dae1", bold = true, fg = "#1c2635" })
hi(0, "lualine_a_insert", { bg = "#95ede2", bold = true, fg = "#1c2635" })
hi(0, "lualine_a_normal", { bg = "#d7dae1", bold = true, fg = "#1c2635" })
hi(0, "lualine_a_replace", { bg = "#d6d5ff", bold = true, fg = "#1c2635" })
hi(0, "lualine_a_terminal", { bg = "#bae9b5", bold = true, fg = "#1c2635" })
hi(0, "lualine_a_visual", { bg = "#ace3ff", bold = true, fg = "#1c2635" })
hi(0, "lualine_b_command", { bg = "#1f2535", fg = "#e5dd9a" })
hi(0, "lualine_b_fancy_diagnostics_error_command", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diagnostics_error_inactive", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diagnostics_error_insert", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diagnostics_error_normal", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diagnostics_error_replace", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diagnostics_error_terminal", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diagnostics_error_visual", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diagnostics_hint_command", { bg = "#1f2535", fg = "#87d8d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_inactive", { bg = "#1f2535", fg = "#87d8d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_insert", { bg = "#1f2535", fg = "#87d8d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_normal", { bg = "#1f2535", fg = "#87d8d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_replace", { bg = "#1f2535", fg = "#87d8d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_terminal", { bg = "#1f2535", fg = "#87d8d3" })
hi(0, "lualine_b_fancy_diagnostics_hint_visual", { bg = "#1f2535", fg = "#87d8d3" })
hi(0, "lualine_b_fancy_diagnostics_info_command", { bg = "#1f2535", fg = "#bdc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_inactive", { bg = "#1f2535", fg = "#bdc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_insert", { bg = "#1f2535", fg = "#bdc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_normal", { bg = "#1f2535", fg = "#bdc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_replace", { bg = "#1f2535", fg = "#bdc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_terminal", { bg = "#1f2535", fg = "#bdc1fa" })
hi(0, "lualine_b_fancy_diagnostics_info_visual", { bg = "#1f2535", fg = "#bdc1fa" })
hi(0, "lualine_b_fancy_diagnostics_warn_command", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_inactive", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_insert", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_normal", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_replace", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_terminal", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diagnostics_warn_visual", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diff_added_command", { bg = "#1f2535", fg = "#a6d5a8" })
hi(0, "lualine_b_fancy_diff_added_inactive", { bg = "#1f2535", fg = "#a6d5a8" })
hi(0, "lualine_b_fancy_diff_added_insert", { bg = "#1f2535", fg = "#a6d5a8" })
hi(0, "lualine_b_fancy_diff_added_normal", { bg = "#1f2535", fg = "#a6d5a8" })
hi(0, "lualine_b_fancy_diff_added_replace", { bg = "#1f2535", fg = "#a6d5a8" })
hi(0, "lualine_b_fancy_diff_added_terminal", { bg = "#1f2535", fg = "#a6d5a8" })
hi(0, "lualine_b_fancy_diff_added_visual", { bg = "#1f2535", fg = "#a6d5a8" })
hi(0, "lualine_b_fancy_diff_modified_command", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diff_modified_inactive", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diff_modified_insert", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diff_modified_normal", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diff_modified_replace", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diff_modified_terminal", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diff_modified_visual", { bg = "#1f2535", fg = "#d1c98c" })
hi(0, "lualine_b_fancy_diff_removed_command", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diff_removed_inactive", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diff_removed_insert", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diff_removed_normal", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diff_removed_replace", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diff_removed_terminal", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_fancy_diff_removed_visual", { bg = "#1f2535", fg = "#f6b2ba" })
hi(0, "lualine_b_inactive", { bg = "#1f2535", fg = "#d6dae1" })
hi(0, "lualine_b_insert", { bg = "#1f2535", fg = "#b6eab8" })
hi(0, "lualine_b_normal", { bg = "#1f2535", fg = "#d6dae1" })
hi(0, "lualine_b_replace", { bg = "#1f2535", fg = "#f9c7f9" })
hi(0, "lualine_b_terminal", { bg = "#1f2535", fg = "#e5dd9a" })
hi(0, "lualine_b_visual", { bg = "#1f2535", fg = "#94ede8" })
hi(0, "lualine_c_command", { bg = "#111624", fg = "#d6dae1" })
hi(0, "lualine_c_inactive", { bg = "#111624", fg = "#d6dae1" })
hi(0, "lualine_c_insert", { bg = "#111624", fg = "#d6dae1" })
hi(0, "lualine_c_normal", { bg = "#111624", fg = "#d6dae1" })
hi(0, "lualine_c_replace", { bg = "#111624", fg = "#d6dae1" })
hi(0, "lualine_c_terminal", { bg = "#111624", fg = "#d6dae1" })
hi(0, "lualine_c_visual", { bg = "#111624", fg = "#d6dae1" })
hi(0, "lualine_x_fancy_macro_command", { bg = "#1f2535", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_inactive", { bg = "#1f2535", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_insert", { bg = "#1f2535", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_normal", { bg = "#1f2535", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_replace", { bg = "#1f2535", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_terminal", { bg = "#1f2535", fg = "#ff0000" })
hi(0, "lualine_x_fancy_macro_visual", { bg = "#1f2535", fg = "#ff0000" })
hi(0, "lualine_y_fancy_filetype_ts_icon_command", { bg = "#1f2535", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_inactive", { bg = "#1f2535", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_insert", { bg = "#1f2535", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_normal", { bg = "#1f2535", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_replace", { bg = "#1f2535", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_terminal", { bg = "#1f2535", fg = "#41942c" })
hi(0, "lualine_y_fancy_filetype_ts_icon_visual", { bg = "#1f2535", fg = "#41942c" })
hi(0, "rainbow1", { fg = "#f6b2ba" })
hi(0, "rainbow2", { fg = "#a6d5a8" })
hi(0, "rainbow3", { fg = "#d1c98c" })
hi(0, "rainbow4", { fg = "#94cff4" })
hi(0, "rainbow5", { fg = "#e3b5e3" })
hi(0, "rainbow6", { fg = "#87d8d3" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#111624"
g.terminal_color_1 = "#f6b2ba"
g.terminal_color_2 = "#a6d5a8"
g.terminal_color_3 = "#d1c98c"
g.terminal_color_4 = "#94cff4"
g.terminal_color_5 = "#e3b5e3"
g.terminal_color_6 = "#87d8d3"
g.terminal_color_7 = "#b1b6be"
g.terminal_color_8 = "#1a2331"
g.terminal_color_9 = "#f696a3"
g.terminal_color_10 = "#bde6bf"
g.terminal_color_11 = "#e4dc9d"
g.terminal_color_12 = "#6ac0f3"
g.terminal_color_13 = "#dc9cdd"
g.terminal_color_14 = "#98ebe6"
g.terminal_color_15 = "#c3c7cd"
