# tokyo-cat
[colors]
foreground = "#c3c7cd"
background = "#111624"
selection_bg = "#c3c7cd"
selection_fg = "#111624"
cursor_fg = "#111624"
cursor_bg = "#c3c7cd"

ansi = ["#353b4c", "#f6b2ba", "#a6d5a8", "#d1c98c", "#94cff4", "#e3b5e3", "#87d8d3", "#c3c7cd"]
brights = ["#353b4c", "#f6b2ba", "#a6d5a8", "#d1c98c", "#94cff4", "#e3b5e3", "#87d8d3", "#c3c7cd"]
