return {
  --   "jay-babu/mason-null-ls.nvim",
  --   event = { "BufReadPre", "BufNewFile" },
  --   dependencies = {
  --     "williamboman/mason.nvim",
  --     "jose-elias-alvarez/null-ls.nvim",
  --   },
  -- config = function()
  --
  --   local null_ls = require('null-ls')
  --
  --   null_ls.setup({
  --     sources = {
  --       -- all sources go here.
  --       null_ls.builtins.formatting.ruff,
  --       null_ls.builtins.diagnostics.ruff,
  --     }
  --   })
  --   require("mason-null-ls").setup({
  --     ensure_installed = nil,
  --     automatic_installation = false,
  --   })
  -- end,
}
